### ISSUE TITLE
Device's back button incorrectly changes color of tab icon

### ISSUE THREAD

**Issue by abbyad** [medic/medic#1212]
The previous tab can have a colored icon instead of it being white or black as it should be.

_To reproduce_
- use medic-android
- tap to switch to another tab (eg go from the Messages to the Contacts tab)
- use the device's back button

Going from the Messages to the Contacts tab, then back, you should notice that the active tab is now Messages, which is correct. The issue is that the icon on the Contacts tab is now salmon, instead of white like the other inactive tabs.

**Comment by abbyad** [comment]
Example of the issue, recreated here in desktop mode - although it is not an issue on desktop:

![image](https://cloud.githubusercontent.com/assets/789512/9533130/f6c0d6d8-4cdd-11e5-8061-8e4ff699139b.png)

**Comment by garethbowen** [comment]
That's the hover style, which is weird, seeing you can't hover on a touch device. It'll be Chrome trying to be clever. We could just remove all hover styles on mobile.

**Comment by browndav** [comment]
Very deprioritized.

**Comment by alxndrsn** [comment]
Looks like removing the `:hover` styles on mob could be the simplest approach - there doesn't seem to be a way to de-hover via JS, even triggering `mouseout`, `blur`, `ontouchend` on the relevant elements.
