### ISSUE TITLE
Phone number validation failure displays same error message whatever the cause

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#1373]
# Current behaviour

If phone number validation fails, the error message is currently the same whatever the reason for the validation failure.

> Phone number not valid

(This may have been updated to something more descriptive in #1372, but it will still be the same message whatever the failure.)
# Desired behaviour

If the number is not valid, the message should be e.g.

> Not a valid phone number

If the phone number is not unique, the message should be e.g.

> This phone number is already assigned to another contact.
## N.B.

These error messages are likely already available in API. If that is the case, then the old values should be re-used

**Comment by estellecomment** [comment]
Enketo has a single constraint per field, and from digging into the code, it looks like it would be a huge undertaking to add a second one. 
@alxndrsn also [asked about it](https://github.com/enketo/enketo-core/issues/334)

We could fiddle with just the displaying of messages, without changing the underlying enketo validation.
However, the validation function, which checks if phone number is unique, doesn't have access to the whole form field (only the value being validated). So it can't manipulate the field's display (e.g. set css classes).

So I don't see a way to do this that's not hideously hacky, or requires a large amount of work on Enketo.
