### ISSUE TITLE
Send Message dropdown looks weird on wide-thin screens

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#1380]
# Observed:

<img width="1280" alt="screen shot 2015-10-05 at 16 10 48" src="https://cloud.githubusercontent.com/assets/191496/10282725/8ff83aaa-6b7c-11e5-8544-90b9a6fcb236.png">
# Expected:

On thinner screens, this looks more reasonable:

<img width="1280" alt="screen shot 2015-10-05 at 16 13 13" src="https://cloud.githubusercontent.com/assets/191496/10282745/a56aec20-6b7c-11e5-9458-0f0d58543d36.png">

And also on wider screens:

<img width="1280" alt="screen shot 2015-10-05 at 16 13 02" src="https://cloud.githubusercontent.com/assets/191496/10282733/9b2e099a-6b7c-11e5-9e42-0c8039c0d529.png">

Related to #1263

**Comment by abbyad** [comment]
@newtewt can you check see if this still a problem?

**Comment by newtewt** [comment]
This is no longer an issue because we show a dialog with a field to select who to send to and the message.

![image](https://user-images.githubusercontent.com/10531066/54547542-4ee65100-497c-11e9-9f2d-2c683350c301.png)
