### ISSUE TITLE
Provide a user interface for configuring task generation

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#1397]
Currently you have to go through app_settings. Instead we should provide a quick easy way to do it in Configuration.

We should be able to get it down to just the "when" block and hard code the type definitions and "then" block. It'd also be good to do validation immediately so syntax errors are reported up front.

**Comment by abbyad** [comment]
This is superseded for now by the declarative configuration. A UI for setting up tasks, targets and profiles is being considered and a new issue will be opened when that is put on the roadmap.
