### ISSUE TITLE
Allow configuration of ContactSchema through the admin UI

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#1401]
Currently the contact schema is hardcoded for LG.  To make this configurable for different projects, we'll need to:
- [ ] add default config for contact schema
- [ ] update contact schema service to read from this config
- [ ] make this config editable from UI

**Comment by garethbowen** [comment]
Before starting on this we should decide on whether the current approach of generating xforms is the preferred approach. If not we may not need to define a contact schema at all.

**Comment by abbyad** [comment]
Just a heads up that we'd want to show Age even if we are storing date of birth, so the solution for this issue should allow for that.

**Comment by garethbowen** [comment]
This is made obsolete by configurable hierarchy.
