### ISSUE TITLE
Add a FALLBACK page in login's appcache

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#1419]
When the app is offline, we could have a `FALLBACK` option for the login page.

Notes:
- login may not already have an appcache
- adding login stuff to the main appcache might make app loading feel quicker, as it could happen in the background of the login form

**Comment by abbyad** [comment]
@alxndrsn is this still needed?

**Comment by alxndrsn** [comment]
Yes, it would still have benefits.

**Comment by garethbowen** [comment]
Won't fix - appcache is gone.
