### ISSUE TITLE
[select2] send-message dialog has weird alignment

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#1536]
<img width="683" alt="screen shot 2015-11-05 at 14 07 12" src="https://cloud.githubusercontent.com/assets/191496/10969161/d68a606c-83c6-11e5-9dbc-9a3eafc813b8.png">

This issue may be very specific to the content - it looks like it _almost_ fits on a single line.  Possibly a bug upstream.

**Comment by alxndrsn** [comment]
This is an upstream bug.

**Comment by alxndrsn** [comment]
Filed upstream at https://github.com/select2/select2/issues/3906

**Comment by garethbowen** [comment]
Closing as ancient. It's been closed as stale upstream...
