### ISSUE TITLE
[android] app accepts any location request

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#1603]
Instead the app should first check that the location request domain matches the configured domain for the app.

**Comment by nice-snek** [comment]
hi frand @garethbowen, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
@alxndrsn What's the concern here? XSS?

**Comment by alxndrsn** [comment]
Or if the user browses to a site outside of medic.

**Comment by garethbowen** [comment]
Sold. Let's patch it sometime.

**Comment by garethbowen** [comment]
Closing as a duplicate of the medic-android issue.
