### ISSUE TITLE
Validate that user's contacts are a descendant of their place

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#1688]
Using the Configuration > Users page you can create a user whose contact is not a descendant of their place. This is problematic because that contact won't be replicated to the local pouchdb. Then when the family is created we look up the user's contact, which returns a 404 and adding the family fails, as in #1654.

Validate on save that the user's contact is indeed a descendant of their place.

**Comment by diannakane** [comment]
and/or improve UI of drop-down options in any of our select person/place fields in contacts to improve clarity of hierarchy

**Comment by garethbowen** [comment]
Duplicate of #4502
