### ISSUE TITLE
Rework verification of reports display

### ISSUE THREAD

**Issue by diannakane** [medic/medic#1846]
We are rethinking how we represent that a report has been verified, taking into consideration the need for bulk delete/edit (Issue 1000). 

Initial conversation about validate button and creating space for checkboxes to select multiple messages can be found here: https://medic.slack.com/archives/design/p1449524198000002

Dianna's initial mocqup brainstorm found here: https://moqups.com/joshnesbit/1fF4IwJA/p:a8f18193a

Note that validating is a manager function only, and could likely be implemented in the web app initially, until we have a manager smartphone app version designed, then I could imagine them wanting to validate on-the-go.

**Comment by garethbowen** [comment]
The verification workflow has been updated recently so after discussion with @amandacilek I'm going to close this as obsolete.
