### ISSUE TITLE
Redesign filters / search

### ISSUE THREAD

**Issue by diannakane** [medic/medic#1847]
There are likely two (or more) issues here, but for the sake of documenting the conversation thus far: 

In discussing bulk delete (issue 1000), we want to improve the way that users can search or filter reports in order to bulk delete / edit them. Most of bulk delete will be done by managers/trainers in the web app, though filtering applies to both the reports tab (primarily: bulk delete) and contacts tabs (primarily: bulk message). Improving these filters is lower priority than the issue 1000 but we wanted to think about them together. 

In the CHW mobile app, filters and search are most relevant to the Contacts tab since CHWs will have less interaction with their history/reports tab in general and less need to filter their reports since they can only view the ones they have submitted. In the contacts tab, filters can help them identify important types of patients, such as "high risk pregnancies." There are important usability considerations that must be met in order for these to be utilized by CHWs. One option is to preset a number of "quick search" filters in our design phase. 

There are a few exploratory mockups for using filters in the mobile app here:
for contacts: https://moqups.com/joshnesbit/1fF4IwJA/p:af597fa84
for reports: https://moqups.com/joshnesbit/1fF4IwJA/p:aa5c8f123

**Comment by abbyad** [comment]
The mockup links are now broken. @diannakane can you replace them and prioritize this issue with @MaxDiz?

**Comment by amandacilek** [comment]
It sounds like this request is to "Add filters to the Contacts tab", is that correct, Dianna? Definitely something we've discussed more than once. The biggest question will be in deciding which sort of filters to offer, and whether the options change depending on the user role or user hierarchy etc.

We might also bundle adding "sort" functionality in here as well. We have a sort function for UHC mode only right now. What if we made it available to everyone, and had other options (sort alphabetical, sort by date last visited, sort by high risk etc).

**Comment by MaxDiz** [comment]
@amandacilek do you have any documentation for the sort function applied to UHC currently?

**Comment by amandacilek** [comment]
@MaxDiz I'm not quite sure what you mean by "documentation". 

The original ticket to add sorting to UHC mode is #4752. Configuration documentation was added here: https://github.com/medic/medic-docs/blob/master/configuration/app-settings.md#optional-settings

The original design spec is here: https://docs.google.com/document/d/1y5g_Oi4a-3pQbwwTwPEsWX0jF7AJML2lnH9XsVhb_yA/edit but this is a little outdated and some changes were made since (default sort for UHC mode is by date last visited, not alphabetically, and the final UI of the sort options in the dropdown ended up looking a little different).

**Comment by amandacilek** [comment]
We haven't forgotten about adding search and filters to other pages but those conversations will be addressed as they come up in relation to solving other projects and workflows. I'm going to close this ticket because this is an outdated request.
