### ISSUE TITLE
Develop stories about use of the "verify" button

### ISSUE THREAD

**Issue by diannakane** [medic/medic#2001]
We want to revisit how partners and teams are using the "verify" or "validate" function in our history tab. 

The original idea for this function came from health facility managers that wanted a way to mark certain records as having been reviewed before compiling their reports. 

We want to understand if this function is still useful to partners and if any projects have utilized it for a different purpose.

**Comment by garethbowen** [comment]
Verification has been reworked recently making this issue obsolete.
