### ISSUE TITLE
Log user statistics on key user interactions to the database

### ISSUE THREAD

**Issue by SCdF** [medic/medic#2031]
We have a lot of unanswered questions about how CHPs truly use the app. It would be great if we could log some useful pieces of information in pouch, so that when they were online it would sync. We then could take a look at that data and make better decisions.

Examples include:
- Does startup / warmup time matter? Statistic to record would be every time they start the app.
- Are CHPs often off network, or are they always off network, or do they bounce between being off and on? Statistic would be network connection change (may require android app integration)

**Comment by SCdF** [comment]
@alxndrsn and I had a discussion yesterday to recall our earlier discussion in Kampala about this, as well as discuss the realistic need for user statistics.

## Do we even want analytics?

Here is the main point I think we need to discuss: **while statistics are cool, they are not free, in either bandwidth, time or complexity**:
 - *so* We should only add them if we are trying to answer a specific question?
 - *or* We should add as many as we can think of that might be useful, because you never know what they will turn up?

**DISCUSS.**

----

For context, here are some questions that Alex and I have thought about that might be useful for us to have answers to, as well as the corresponding thing you'd check for:
 1. **Does the user restart the app a lot?** :: record app starts
 2. **Is the user often online?** :: Polling / change based information on network quality (off / on, or off / ?G / wifi)
 3. **Do users use contact search?** :: each tap of the search button, perhaps with # results returned, perhaps completion ratio (search->contact tap:search->search/search->scroll etc)
 4. **Do uses use the history page** :: navigations to the history page, perhaps more details of their interactions with it
 5. **How well users use forms?**
    - **Do users abandon forms?** :: ratio of opened tasks : cancelled form
    - **Are users filling in forms efficiently?** :: time it takes to complete a for
    - **Do users fill in forms real-time or leave it until later?** :: times that forms are filled in (nb: we already have this data remotely)

## [tech aside] How we could do front-loaded analytics

Have a framework that allows you to push a analytic name and either nothing (which would generate a timestamp) or an arbitrary piece of JSON (which you'd presume contained a timestamp).

These pieces of data would get stored in a pouch local document, which could look something like this:

```
_local/stats: {
    "events": {
        "key": // array of timestamps or json documents 
    },
    "started": // timestamp
}
```

Where `key` is the name of your event.

Every time you pushed a statistic it would check to see if `started` occurred >24hrs ago, in which case it would copy the document to new non-local pouch document so that it would eventually sync up to couch, and then create a new version in `_local`.

## [tech aside] How we could deploy analytics we care about

Instead of front-loading a bunch of analytics that you *might* care about we could only deploy analytics when we want to ask and answer a very specific question. For example we might want to find out "Do CHPs use the history page?"

We could achieve this by potentially still using the framework described above, but instead of hard-coding analytics:
 - Change the replication sync to accept a new type of document, a 'statistic-request' document
 - That document would be ddoc-like, and contain Javascript that would execute either when downloaded or upon angular boot (for existing ones / reload reasons)
 - The code would be able to hook into angular and do things like watch state changes etc
 - When we are done caring about that analytic you'd delete it from couch, which would propogate down to pouch, and the analytic would stop being recorded.

**Comment by estellecomment** [comment]
+1 for not collecting data we aren't using, for user privacy reasons. (and, as you mentioned, it's not free in our case.)

**Comment by SCdF** [comment]
On #2170 Gareth just asked an interesting question:

> Can we remove the back button altogether and have mobile users rely on the phone's back button? Have we seen which actual user's prefer to use? 

This is a good "live" example of something that could benefit from being able to deploy analytics to prod for a couple of weeks, as it would probably help answer this question quite nicely.

**Comment by alxndrsn** [comment]
> Can we remove the back button altogether and have mobile users rely on the phone's back button? Have we seen which actual user's prefer to use?

We could.  From my limited experience, the FBB doesn't really get used.  Perhaps this is in part because historically it was very hard to touch successfully?  Or perhaps because it mostly does exactly the same as the HBB.  But:
* what we have currently is fairly close to the [recommended Android navigation](https://developer.android.com/design/patterns/navigation.html), except that our HBB behaviour is not "temporal"
* if you remove FBB, an iOS version of the app would become tricky

> This is a good "live" example of something that could benefit from being able to deploy analytics to prod for a couple of weeks, as it would probably help answer this question quite nicely.

Seems inoffensive enough that measuring it would seem like a lot of effort to me.

**Comment by SCdF** [comment]
^^ you probably want this comment on the other ticket. I didn't mean to bring the discussion over here, just saw an example I thought was interesting :-)

**Comment by henokgetachew** [comment]
+1 because it would help answer lots of usability questions.

**Comment by estellecomment** [comment]
Like what?

**Comment by henokgetachew** [comment]
I guess I can't say it any better than @SCdF above. Others could be like being able to answer things such as: after the introduction of a certain feature (after roll out of version x.xx), do the users tend to use the app less/more? How many users open the app at least once a day?  Which page never gets visited by users?

**Comment by SCdF** [comment]
So where we got to before was: we should have concrete questions that we are trying to answer (and ideally only a run for a certain amount of time), and then we can look at implementing a framework to allow for those questions to be answered.

I think it would be a great improvement, I'd just want at least one concrete question to start off with.

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by sglangevin** [comment]
@SCdF I agree that this is important. I'm thinking mark as scheduled and get it on the radar for later in the year when we can think about how we might do this and what types of questions we are most interested in answering. Thoughts?

**Comment by SCdF** [comment]
@sglangevin I still agree with my previous comment: I think we'd want some questions to answer first before we built it :-) There is some technical work done in comments above, so that's argument for not closing the ticket, but it's not exactly ground-breaking stuff, so honestly I'd be happy with it going either way.

**Comment by sglangevin** [comment]
I'll leave this open and scheduled for now so that we can revisit discussions later in the year.

**Comment by SCdF** [comment]
Just to make sure this doesn't get lost, @diannakane / @sglangevin here is some conversations we've already had about usage analytics from a technical perspective. It's probably handy to link to this from whatever design discussion is occurring.

**Comment by sglangevin** [comment]
We've had some more recent discussions about trying to get data on client side performance using a usage analytics framework. As we scale, this could be a valuable investment and could help make sure that health workers are getting an app that performs well over time. Would be useful to try to roll this out to a small group at first and see what we learn.

**Comment by SCdF** [comment]
@garethbowen I've cleaned up our code a little, please take a look at your earliest convenience.

**Comment by garethbowen** [comment]
@SCdF Back to you.

**Comment by garethbowen** [comment]
Is this something we should include in 3.2.0 or put off till 3.3.0 (or later)? I'm leaning towards putting it in 3.2.0 as it's not overly risky.

**Comment by diannakane** [comment]
My only concern is delaying start on 3.3 which contains time-sensitive features.

**Comment by garethbowen** [comment]
@diannakane The development on this is already complete so 3.3.0 won't be delayed either way.

**Comment by ngaruko** [comment]
![image](https://user-images.githubusercontent.com/6979995/53689751-920fc400-3dc1-11e9-8789-353450e5edf8.png)



![image](https://user-images.githubusercontent.com/6979995/53689766-e7e46c00-3dc1-11e9-9fe8-425958335cbc.png)

Fast forward one month





one more month


Metrics
