### ISSUE TITLE
Show project dashboard within webapp

### ISSUE THREAD

**Issue by abbyad** [medic/medic#2219]
_As a manager I want to access the external project dashboard from the webapp so that I can easily go between the drilled down view of my data and my high level dashboard._

We've had this and [similar requests from many partners](https://github.com/medic/medic-projects/issues/138), basically to access the project dashboard directly from our webapp. The simplest version of this would be a button/link that opens the dashboard in another tab. The more complex, but ideal scenario would be to embed the project dashboard directly in the webapp's Analytics tab. 

The goal of this issue is to mockup up the user experience of an embedded dashboard, keeping in mind what is feasible with our dashboard tool.

cc @diannakane, @michaelkohn

**Comment by alxndrsn** [comment]
Should this be **`1 - Scheduled`**, or should it be removed from the Milestone?

**Comment by garethbowen** [comment]
I vote for removing it as it hasn't been touched in 5 milestones...

**Comment by abbyad** [comment]
Closing as ancient. We are also moving from partner level dashboards having lists of patients/CHWs to having workflows in the app with Tasks where possible.
