### ISSUE TITLE
Import full data set

### ISSUE THREAD

**Issue by abbyad** [medic/medic#2238]
We need to be able to fully set up an instance with realistic data for testing (eg #2121, #1872, #1836, #2152) as well as demos. Right now this could be done manually, but is very time consuming and not practical.

Here are the known components, some of which are already automated and documented, others not:
- **Settings:** can already be loaded via [this script](https://github.com/medic/medic-projects/blob/master/scripts/upload_app_settings.sh), or [this script](https://github.com/medic/medic-projects/blob/master/scripts/update_tasks.sh) if pulling in rules.
- **Contacts:** can be added manually or by importing via the Contacts tab UI. The later requires careful creation of JSON for the People and Places, which is **not easily done**. This should be replaced with something simpler, perhaps using `Contacts` API endpoint.
- **Messages:** can be loaded using a [script](https://github.com/medic/medic-webapp/blob/develop/scripts/load_messages.js).
- **Forms:** can be added via [script](https://github.com/medic/medic-webapp/blob/develop/scripts/upload_xform.sh), as is currently being done for new projects
- **Form Submissions:** could be meticulously crafted and uploaded via couch, but this is **not practical for general use.** We should look at simplifying this step.
- **Users:** being automated with #2046 

Aside from the individual components we should look at the best way to do the entire setup, which can then be used in our e2e testing or for preparing live demos. Having API endpoints for Contacts, Messages, and Forms also makes it easier for integrations with 3rd party systems (eg OpenMRS, DHIS2).

**Comment by mandric** [comment]
An example of how we are importing users: https://github.com/medic/medic-projects/issues/1819

I have low level import process stuff over here, hoping to build a UI for it one day. https://github.com/medic/medic-bulk-utils/

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by sglangevin** [comment]
@abbyad are pieces of this being accomplished by the move to medic-configurer? And/or can we add these components to medic-configurer? Sounds like there is API work here as well that might be part of our integrations work. It would help if we could prioritize the items in this list to see where we might want to start. Putting this in the backlog for now.

**Comment by abbyad** [comment]
A lot of this is covered by medic-conf, but not all. We should update the list of imports for the components to see what gaps are still missing.

**Comment by abbyad** [comment]
Closing as this has now been fully covered within medic-conf.
