### ISSUE TITLE
Have to manually navigate to /medic/login after upgrade

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#2526]
In a logged-in browser, there is no notification when the server has upgraded from 0.4 to 2.x.  This is expected, but on hard-refreshing the page, I was not redirected to the login page.  Instead, I saw the following:

<img width="1259" alt="screen shot 2016-07-21 at 11 55 24" src="https://cloud.githubusercontent.com/assets/191496/17021665/bd786a48-4f49-11e6-854f-07d5c68e60b4.png">

From here, I had to manually browse to `/medic/login`, from where I was immediately forwarded to webapp in an authorised session.

**Comment by nice-snek** [comment]
hi frand @estellecomment, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint. :parrot_conga::parrot_conga::parrot_conga:

**Comment by estellecomment** [comment]
@browndav @ngamita @bishwas-medic Is this something you saw happening when upgrading? If not I'll just close

**Comment by bishwas-medic** [comment]
Yeah, I had the same issue with a logged in session after the upgrade from v0.4 to v2.x. The webapp showed a loading error (forgot the exact error message). The console displayed this error:
<img width="573" alt="screen shot 2017-05-09 at 9 43 57 am" src="https://cloud.githubusercontent.com/assets/13689284/25939505/ae1af06c-3665-11e7-8e0f-0d7bba249852.png">

I'll DM you the instance name.

**Comment by garethbowen** [comment]
Closing as ancient.
