### ISSUE TITLE
Plan for testing XForms used for app workflows

### ISSUE THREAD

**Issue by abbyad** [medic/medic#2701]
We need to figure out an effective and efficient way for tech leads to test forms. Opening this issue for discussion of approaches, not to implement a test system.

_**Edit:** Focus on forms in this issue. Removed testing of task/target rules from this issue_

**Comment by garethbowen** [comment]
We have a rules testing framework that will help here: #1836

**Comment by abbyad** [comment]
Thanks, that is helpful.  Looks like https://github.com/medic/medic-webapp/issues/2503 covers what we need for the rules when it is complete:
> This ticket is complete when there is reasonable coverage of LG's rules, what is written is understandable by tech leads / rules writers, and could be duplicated / used as a base of understanding for other 2.x deployments.

I'll rename this issue to focus on testing the forms, where the guts of health protocol lives. For LG there are about 580 test cases for the Assessment form alone, so an efficient plan would help make sure that the protocols are properly implemented.

**Comment by alxndrsn** [comment]
> For LG there are about 580 test cases for the Assessment form alone

Is this list available somewhere?  Are there other examples, that we can see>

**Comment by abbyad** [comment]
Here is the test plan ([private Google Sheet](https://docs.google.com/spreadsheets/d/19UCse090W4aklxEVh1sMZQntad3K3xua7h0twWcUk3U/edit)) for a current project.

**Comment by alxndrsn** [comment]
Basic framework for testing xforms implemented at https://github.com/alxndrsn/xformunit

**Comment by sglangevin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Loop back with Alex/Stefan regarding automated testing](https://trello.com/c/C71deZVg/138-loop-back-with-alex-stefan-regarding-automated-testing)

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by sglangevin** [comment]
This is definitely relevant. Marking as scheduled and adding to our Q2 tracking list.

**Comment by estellecomment** [comment]
@abbyad Does this issue include testing the scheduled SMS sending? 
If yes, then could you edit the OP to specify that? 
If no, could you also edit the OP to specify (:D) , and reopen #2117 which does covers it.
Thanks!

**Comment by garethbowen** [comment]
@abbyad Would you consider this done now?

**Comment by abbyad** [comment]
I believe so! @kennsippell can you provide a link to the appropriate form test framework in case someone lands here looking for it?

**Comment by kennsippell** [comment]
https://github.com/medic/medic-conf-test-harness

View the API documentation [here](https://htmlpreview.github.io/?https://raw.githubusercontent.com/medic/medic-conf-test-harness/blob/master/out/index.html).
