### ISSUE TITLE
Update prompt should appear only when there is 'real change'

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#3050]
Not sure how easy this can be (to implement) but I guess it would be a good idea to prompt users to update if and only if there was a 'real change'. Example, if you go to Configuration, Settings >> click Submit button (Basic) without touching the form, you still get prompted to reload and when you do so (click Update button), an error is thrown in the console (not sure if that's related or).

![image](https://cloud.githubusercontent.com/assets/6979995/21967495/3a6ba396-dbed-11e6-80ae-d1485d39d7ce.png)

Console:
![image](https://cloud.githubusercontent.com/assets/6979995/21967502/492d5f46-dbed-11e6-9ac0-b00daef6140a.png)

**Comment by SCdF** [comment]
The bug here is that the ddoc gets updated even if there are no changes. This may be reasonably hard to fix, and probably while incorrect, is not a massive deal.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues) before the end of this sprint.
```
--..,_                        _,.--.
       ''.'.                .''__ o  ';__.
          '.'.            .'.''  '---''  '
            '.''--....--''.'
              ''--....--''
```

**Comment by alxndrsn** [comment]
Would it work just to disable the Submit button if no changes have been made?

**Comment by sglangevin** [comment]
Ideally we wouldn't have the prompt at all unless changes were made. If the Submit button is disabled, is the user expected to hit Cancel? Or the HBB? Seems like it could be weird UX.

**Comment by alxndrsn** [comment]
@sglangevin sorry for not being clearer: I mean the submit button on the app_settings page should be disabled unless there are real changes.  That way, no ddoc "update" will be pushed to users.

Unless @SCdF was referring to a different mechanism of ddoc updating... if it's done from a script, the script should probably reject the upload if there were no changes.

**Comment by sglangevin** [comment]
> I mean the submit button on the app_settings page should be disabled unless there are real changes. That way, no ddoc "update" will be pushed to users.

Ah, makes sense.

**Comment by nice-snek** [comment]
hi frand @garethbowen, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by garethbowen** [comment]
This is low priority - it's merely annoying.

**Comment by garethbowen** [comment]
Ready for AT in `113-warn-config-overwrite`.

This is being done as it's a useful component of a larger feature that didn't quite make it in to 3.7.0. It's worth ATing this component and getting it out now, and then shipping the other parts in 3.8.0.

**Comment by ngaruko** [comment]
LGTM.
