### ISSUE TITLE
Registering for a SMS schedule can start mid-group

### ISSUE THREAD

**Issue by abbyad** [medic/medic#3093]
If the first messages of a group are in the past we should not be sending the latter messages of the group. Instead, the first scheduled messages that should be sent are the first messages of the next group.

Otherwise, when registering a patient that is midway through a scheduled SMS group you can get a "Did the person attend their visit?" message without a "Please tell Maria to go their ANC visit".

**Comment by abbyad** [comment]
That is possible for new projects, but may be difficult to appropriate change the text for all projects. Even then we'll find situations which are not ideal, especially since facility based tasks are now being created based on these groups. A nurse may be asked to follow up on a visit that the CHW was never notified about - or that did not make sense for the patient to attend to begin with. The latter scenario has the potential to skew Analytics results too.

**Comment by abbyad** [comment]
We should find out if there are any situations where getting the final messages of a group without the initial messages is preferred to not getting them at all.

**Comment by sglangevin** [comment]
I'm pretty sure this issue exists in prior versions as well - I remember encountering this in DIY testing.

**Comment by abbyad** [comment]
Ya, it has long been like this - but doesn't mean it shouldn't be done differently :)

[Here](https://github.com/medic/medic-sentinel/blob/9d10a71b229c3f4b5f92d4b77ec08be0cb1231e2/lib/schedules.js#L119-L122) it ignores scheduled messages past due, without considering where it fits in the group.

**Comment by diannakane** [comment]
I agree -- I think we'll struggle to write all messages to make sense if received at any point in time out of context. It makes sense to me to have a rule where a group of messages must be sent in full, from reminder through to follow-up. If you register halfway through a reminder window, can we set the system to initiate the messages from the start, even if a follow-up gets sent immediately afterwards? 

If that can't be done, we could also consider a late registration "welcome" message suggesting that you refer the woman immediately and submit forms to log previous visits while they wait for the next cycle of reminders to start.

**Comment by nice-snek** [comment]
hi frand @browndav, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by browndav** [comment]
Leaving as-is.

**Comment by abbyad** [comment]
Responding to https://github.com/medic/medic-webapp/issues/3093#issuecomment-276456943, you would want a partial group to be sent our for the delivery schedule. For example, if a pregnancy is registered really late (after the 38 week delivery message), you would still want the 40 week delivery notice and follow-up messages to show.

If this issues is "fixed" we could split off each message into a separate group so that they are not inadvertently omitted.

**Comment by garethbowen** [comment]
I sent the same registration SMS twice.

Firstly, with `start_mid_group` configured as undefined:

![Screenshot from 2019-05-15 16-23-35](https://user-images.githubusercontent.com/2064938/57748438-0eae0f80-772e-11e9-9f78-511b55074dc1.png)

And then with `start_mid_group: true`:

![Screenshot from 2019-05-15 16-25-02](https://user-images.githubusercontent.com/2064938/57748439-0f46a600-772e-11e9-98de-736430892931.png)

AT passed!
