### ISSUE TITLE
Include a gateway user in Standard configuration by default

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3151]
This would save one extra step of configuration when setting up a Standard instance.

**Comment by nice-snek** [comment]
hi frand @SCdF, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by SCdF** [comment]
@alxndrsn what is involved here? Standard configuration is a collection of app settings and forms right? How could we include a default user? Or are you suggesting we write a migration script / init check to add a gateway user if it doesn't already exist?

**Comment by alxndrsn** [comment]
I'm not fussed _how_ it's implemented, but I think there should be a gateway user set up out-of-the-box or as part of the initial setup process (I think there is a wizard for this).

**Comment by SCdF** [comment]
@abbyad / @browndav do you two have any thoughts about this? It's hard to tell where it should live: it is something we should be adding to the standard setup script? Or is this something medic-os is supposed to do somehow?

I'm not sure how our current single admin user is setup honestly.

**Comment by abbyad** [comment]
Doing this via a script is not ideal since creating users with medic-api also creates a Place and Person for the user -- it was not designed for creating gateway users. 

If we want to create the gateway user automatically then it could be done by concierge. @browndav can provide more details on that. 

Alternatively we could just have a seed image for Standard that is a snapshot of an instance that is already configured, and includes a gateway user. cc @henokgetachew

**Comment by browndav** [comment]
I'd prefer we not use images of preconfigured instances; that'll cause reuse of (locally-configured) service account passwords and host keys. We already create a number of CouchDB users for use by local services; is wouldn't be that hard to add a `gateway` user if we can document the requirements here.

**Comment by SCdF** [comment]
@alxndrsn can you document the requirements for @browndav. It sounds easy and like a nice thing to smooth over, so scheduled.

**Comment by alxndrsn** [comment]
I think this should do it:
```
username: `gateway`
role: `gateway`
```

**Comment by browndav** [comment]
It looks like this needs two distinct steps:

- [ ] Patch concierge to add the appropriate gateway user on first run
- [ ] Backpatch existing machines by creating the account via shell script (and I have one)

**Comment by garethbowen** [comment]
This should be done but it's not a priority right now. Moving out of the milestone.

**Comment by browndav** [comment]
Picking this up, I'm working right in the proper area (for the Docker stuff) to get a quick win here.

**Comment by abbyad** [comment]
@browndav is this still in progress, or completed already?

**Comment by garethbowen** [comment]
Closing as ancient.
