### ISSUE TITLE
Simple server-side SMS status monitoring

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3249]
It would be helpful for diagnosing problems if there were a query or two that would show:

* all WO messages in a particular state
* recent time differences for state transitions (pending -> sent -> delivered)
* SMS status ratio - pending:sent:delivered:failed

Even if this was just a command-line script or two that a tech can run.

**Comment by bishwas-medic** [comment]
We have been discussing a very similar feature. PMs were asking if there could be a way to look at all pending or stuck messages from a single page. Design team has been working on something very similar: https://github.com/medic/medic-projects/issues/669
cc @ranjuts

**Comment by sglangevin** [comment]
Yeah, there is an open request for a UI to view some of this information. This is something the design team is looking at in Q2, so it would be great to have a script as a start, and we could also build any necessary infrastructure to support this if time.

**Comment by mandric** [comment]
> - all WO messages in a particular state

https://github.com/medic/medic-api#get-apiv1messages

**Comment by alxndrsn** [comment]
Appending all status updates to an event stream (couch/flat file/whatever) could make for very easily-parsable data.

**Comment by garethbowen** [comment]
Duplicate of #649
