### ISSUE TITLE
Trying to send a message when logged out is weird

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3254]
# 1. let your session time out

# 2. compose an SMS message

<img width="382" alt="screen shot 2017-03-16 at 18 41 33" src="https://cloud.githubusercontent.com/assets/191496/23997135/40a9cdd2-0a78-11e7-87f7-1ccb74812eb5.png">

# 3. click _Send_

# 4. see that the send box has collapsed and the button disappeared

<img width="391" alt="screen shot 2017-03-16 at 18 41 37" src="https://cloud.githubusercontent.com/assets/191496/23997134/40a53d62-0a78-11e7-99fa-63afb76de6e1.png">

# 5. look in the console to find your error

<img width="859" alt="screen shot 2017-03-16 at 18 41 40" src="https://cloud.githubusercontent.com/assets/191496/23997133/404bb71a-0a78-11e7-9bf6-6975d54aa8b6.png">

**Comment by SCdF** [comment]
@alxndrsn what is your expected behaviour?

My vote would be what I believe we've tried to do everywhere else, which is detecting 401s and redirecting to the login page.

**Comment by alxndrsn** [comment]
Any kind of clear feedback via the regular UI would be acceptable.  @SCdF your suggestion seems reasonable.

**Comment by SCdF** [comment]
Yeah I think we've had conversations in the past about not kicking people to the login page, and instead presenting some kind of login modal, or interstitial login page. But the login page is easier, and easier to support on both desktop and mobile.

**Comment by garethbowen** [comment]
@alxndrsn I assume this was when logged in as admin?

**Comment by alxndrsn** [comment]
> I assume this was when logged in as admin?

That's possible, but worth checking before working on this.  I should have recorded the account type at the time of creating this issue :-\

**Comment by garethbowen** [comment]
This should be fixed by #3919 - adding to AT to make sure.

**Comment by ngaruko** [comment]
**Before**
![image](https://user-images.githubusercontent.com/6979995/60403486-3419ae80-9bf2-11e9-9a66-7030dcf211c5.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/60403526-aab6ac00-9bf2-11e9-93e0-988019d5460a.png)

  Again, would have been better to have a warning `session expired message` before kicking user out. But I guess this could be rather a ticker for an improvement!
