### ISSUE TITLE
Not showing login screen if logged out until refresh

### ISSUE THREAD

**Issue by abbyad** [medic/medic#3299]
A spinner shows if the user is logged out or timed out, but nothing indicating to the user that they need to log back in. I would expect this to show the login page eventually, if not immediately, then redirect back to the current page after login.

![image](https://cloud.githubusercontent.com/assets/789512/24360641/de43e590-12d5-11e7-8b4f-11740884e585.png)

**Comment by sglangevin** [comment]
@abbyad what user were you logged in as? Had you logged yourself out or were you logged out automatically for some reason? If you have steps to reproduce, please share.

**Comment by abbyad** [comment]
I don't know exact steps, but I was likely logged in as `admin`. I had my computer in sleep mode and had this message when I came back to this tab a couple days later. I don't remember logging out from another tab, but when trying to reproduce by logging out via a different tab I get similar console output except that it doesn't attempt to reconnection.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by garethbowen** [comment]
Related: #3254

**Comment by nice-snek** [comment]
hi frand @${assignee}, U is coot

Please close or schedule before the end of this sprint. See [triaging old issues](https://github.com/medic/medic-docs/blob/master/md/dev/workflow.md#triaging-old-issues).

Nice Snek

**Comment by nice-snek** [comment]
hi frand @sglangevin, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by sglangevin** [comment]
This one keeps coming up for triage but doesn't seem to be a high priority.

**Comment by garethbowen** [comment]
This should be fixed by #3919 - adding to AT to make sure.

**Comment by ngaruko** [comment]
Fixed with #3919 . Suggestion for improvement - Send a warning to the user that the session has expired (or is about to expire). How useful and hard to implement is this feature @garethbowen ?

**Comment by garethbowen** [comment]
Yes it would be very useful and not too hard to implement. Issue raised: https://github.com/medic/medic/issues/5772
