### ISSUE TITLE
Marking a report as verified is slow

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3466]
Seen on: Samsung Galaxy V2

Clicking the tick in the action bar when viewing an existing report takes a couple of seconds to process.  This is uncharacteristically slow for this handset.  This functionality may be doing something suboptimally.

**Comment by sglangevin** [comment]
Is there a deployment that is using this feature on mobile? If not, then I'd prioritize this behind other scheduled bugs.

**Comment by alxndrsn** [comment]
I don't even know what this feature's for, so I agree its performance is not high priority.

**Comment by sglangevin** [comment]
Cool. I'll add this to the backlog of bugs for now and we'll schedule it when we can (or bump it up in priority if we have a project that needs it).

**Comment by garethbowen** [comment]
I think the process is something like... click the link, get the report, mark the report verified, update the database (possibly remote?), get the changes listener notification, get the report, rebuild the UI.

With read status we fake it by immediately setting the style as read assuming the rest of the process will work, then the changes listener and everything else still happens it just has no visible effect.

**Comment by nice-snek** [comment]
hi frand @alxndrsn, please [triage](https://github.com/medic/medic-docs/blob/master/development/workflow.md#triaging-old-issues) before the end of this sprint.

**Comment by alxndrsn** [comment]
If this is still a bug, then it should still be addressed at some point.

**Comment by garethbowen** [comment]
This is worth fixing because we're actually starting to use this feature now that #4529 is released.

The easiest fix is probably just to use a spinner so it's clear that it's working and then change the icon when it succeeds.

**Comment by ngaruko** [comment]
LGMT
The response is reasonably quick and there is a spinner showing for a split second.
