### ISSUE TITLE
Remove enketo form generation feature

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#3570]
We have a [large and complicated function](https://github.com/medic/medic-webapp/blob/master/static/js/services/enketo-translation.js#L132) to generate an xform for editing contacts which is no longer used as far as I know. Instead all projects use custom made forms.

Remove the code for generating xforms.

**Comment by garethbowen** [comment]
@abbyad @sglangevin Can you please confirm that this feature isn't being relied on by any current projects?

**Comment by sglangevin** [comment]
Not that I know of, but instead of removing it can we bundle the Standard forms with the web app? That would be convenient for projects.

**Comment by garethbowen** [comment]
> can we bundle the Standard forms with the web app?

Yes that's my preferred approach so projects have something useful out of the box and can tweak or replace as needed.

**Comment by sglangevin** [comment]
Cool. Do we need to open a new issue for that? Or can we re-purpose this one?

**Comment by garethbowen** [comment]
This one is enough IMO.

**Comment by browndav** [comment]
Appears relevant; keeping.

**Comment by garethbowen** [comment]
Done as part of #3639
