### ISSUE TITLE
Document Update Conflict caused error in accept_patient_report transition

### ISSUE THREAD

**Issue by SCdF** [medic/medic#3640]
Report is this one: https://ohw-dhading.app.medicmobile.org/_couch/_utils/document.html?medic/b074803dc1ce31e3259d9627d4f2cd46

I have a full copy of each version up until the conflict gets noted.

In brief though:

_rev 1 has an error:
```
       {
           "code": "sys.facility_not_found",
           "message": "sys.facility_not_found"
       }
```
Then _rev2 has no errors, and a bunch of successful transitions:
```
   "transitions": {
       "default_responses": {
           "last_rev": 2,
           "seq": 1355779,
           "ok": true
       },
       "update_sent_by": {
           "last_rev": 2,
           "seq": 1355779,
           "ok": true
       },
       "update_clinics": {
           "last_rev": 2,
           "seq": 1355779,
           "ok": true
       }
   },
```
Then _rev 3 has the DUC error and a failed transition:
```
       {
           "code": "accept_patient_reports_error",
           "message": "Document update conflict."
       }
..
       "accept_patient_reports": {
           "last_rev": 3,
           "seq": 1355785,
           "ok": false
       }
```

**Comment by sglangevin** [comment]
Is this happening consistently on that instance or only sometimes? cc @bishwas-medic

**Comment by bishwas-medic** [comment]
This is the first time I've seen that error appearing in any instance. Haven't found other reports with the same error. Nothing further has been reported by the PM or partners.

**Comment by garethbowen** [comment]
Closing as ancient. Reopen if this happens again.
