### ISSUE TITLE
Re-write permissions data structure to be object properties instead of an array to avoid duplicates

### ISSUE THREAD

**Issue by SCdF** [medic/medic#3762]
Currently our permissions are stored something like this:
```js
[{
  name: "foo"
  blah: ..
},
  name: "bar"
  blah: ..
}]
```

This causes us problems periodically because it allows for the same permission to appear more than once. A better data structure would be one that enforces this rule:

```js
{
 foo: { blah: .. },
 bar: { blah: .. }
}
```

**Comment by abbyad** [comment]
This is also a problem for [derived configs](https://github.com/medic/medic-conf#derived-configs), because it is hard to override settings in this format. In the case of `permissions`, we can only add duplicate settings which could have unpredictable results.

The `permissions` are currently in this form:
```
    "permissions": [
      {
        "name": "can_view_reports_tab",
        "roles": [
          "national_admin"
        ]
      },
      {
        "name": "can_view_reports",
        "roles": [
          "national_admin",
          "district_admin"
        ]
      },
```

From the perspective of a configurer it would be easier if it were something like the following:
```
    "permissions": {
      "can_view_reports_tab": [
        "national_admin"
      ],
      "can_view_reports": [
        "national_admin",
        "district_admin"
      ],
      ...
    }```

**Comment by newtewt** [comment]
I ran into an issue where the old version of permissions was being used on gamma.dev. Nothing is displayed in the UI but the error below was in the console.  Would we want this to be backwards compatible or just show an error? @SCdF  @abbyad  @wtekeu 

 ```
Error fetching settings TypeError: roles.includes is not a function
    at authorization-permissions.js:18
    at Array.map (<anonymous>)
    at makeRoleModel (authorization-permissions.js:15)
    at authorization-permissions.js:34
    at Array.forEach (<anonymous>)
    at authorization-permissions.js:31
    at processQueue (angular.js:17914)
    at angular.js:17962
    at Scope.$digest (angular.js:19075)
    at Scope.$apply (angular.js:19463)
```

**Comment by abbyad** [comment]
Good find @newtewt. We shouldn't be breaking compatibility in a minor so we should still support the old format, as well as put a deprecation notice in documentation and perhaps logs as well.

**Comment by abbyad** [comment]
Yeah, that would definitely solve the problem. Good to hear that there is a migration already!

**Comment by ngaruko** [comment]
> We've discussed adding some sort of schema validation to medic-conf so it doesn't let you upload configurations that aren't valid

Has this  schema validation been implemented @garethbowen or shall we close this and open another issue for that? Also, we used to ship the app with certain `default` permissions, but at the moment, most of restricted users' basic permissions (like view/create contacts ) are disabled by default. Is this a result of this change or rather something to do with the configuration?

**Comment by garethbowen** [comment]
We haven't implemented the schema validation - I'm still trying to work out if it's a good idea so I haven't raised an issue for it.

We still ship with default permissions for restricted users including view contacts - see here: https://github.com/medic/medic/blob/master/api/src/config.default.json#L108 . I think your configuration got corrupted when you downgraded from 3.4 to 3.3 so you might need to start with a fresh instance to test this. A new DB on your local machine should work fine.
