### ISSUE TITLE
401s should always redirect to the login page

### ISSUE THREAD

**Issue by SCdF** [medic/medic#3919]
There are lots of places now where 401s just result in console errors, and we don't catch them properly until the user does a hard refresh.

This may be a bug in PouchDB, or our use of it, because when there are replication errors `$q` complains about a "Possibly unhandled rejection".

The correct angular thing is to implement this in inbox.js:

```js
  inboxControllers.config(
    function(
      $httpProvider
    ) {
      'ngInject';

      $httpProvider.interceptors.push(function() {
        return {
          'responseError': function(rejection) {
            console.log('RESPONSE ERROR DETECTED', rejection);
            // Then we'd ideally like to
            // Session.navigateToLogin();
          }
        };
      });
  });
```

However, it looks like PouchDB doesn't end up using `$http` as its interface (I would think it would, which is why we care about `pouchdb-angular`, but maybe not), so this doesn't do anything for PouchDB initiated requests (ie 99% of them).

We should either:
 - Work out why our promise chains are broken, fix them, and put rejection handling there (perhaps patch PouchDB to allow for configuring a hook to deal with errors generically)
 - Go Deeper™, and muck around with prototypes. See things like this: https://stackoverflow.com/questions/25335648/how-to-intercept-all-ajax-requests-made-by-different-js-libraries

**Comment by SCdF** [comment]
Ideally while we're here this is a perfect time to implement a popup re-authentication mechanism. User's shouldn't have to reload the page just to refresh their cookie.

**Comment by wtekeu** [comment]
Ended up overriding PouchDB.fetch: https://github.com/medic/medic/blob/ce136cff9340f6a36216004ab5472cf901f18a29/webapp/src/js/controllers/inbox.js#L59-L68
The two solutions suggested (service worker, fetch option) were too complex or not doable.
- service worker: we will need to exchange/broadcast a message with the page in order to redirect to login since service worker do not have access to the DOM
- fetch option: it seems you can alter the request (for instance alter/add headers) but not intercept the response.

**Comment by SCdF** [comment]
AT:
 - The app should smoothly redirect you to the login page in all situations where you're online and your credentials have expired
 - This should happen for both online and offline users
 - For example, if an offline user comes online and replicates, but their creds have expired, they should be redirected back to the login page
 - For example, if an online user has been idle for awhile and tries to perform an action but their creds have expired, they should be redirected back to the login page

**Comment by garethbowen** [comment]
@wtekeu Can you please confirm which of these related issues (if any) are fixed or made obsolete by this solution? #1978 #3254 #3299

**Comment by dianabarsan** [comment]
I gave this a go and I found that 

1. Every type of automatic (background) replication will redirect any type of user to the login page without warning and without being triggered by the user interacting with the app. If it's not too difficult, I think it would be much less intrusive to show a popup that informs the user that they have been logged out - similar to the one we use to prompt users to refresh once the app is updated. 

2. Admin app is not included in this update.

**Comment by wtekeu** [comment]
In other terms, it takes care of #3254 #3299 but not #1978 .. should not be too difficult to do the same for admin

**Comment by garethbowen** [comment]
@wtekeu I think it probably makes #1978 obsolete, right? They will be redirected to the login page pretty quickly once their session expires.

**Comment by wtekeu** [comment]
@garethbowen Sorry I misread #1978 thinking it was about the admin app when it was about admin users .. yes it takes care of #1978 as well .. but not the admin app as @dianabarsan mentioned.

**Comment by garethbowen** [comment]
I think the issue @dianabarsan found probably means this doesn't pass AT. @wtekeu Could you please have a look at solving this for the admin app too?

**Comment by garethbowen** [comment]
Ready for AT in `3919-401s-should-always-redirect-to-the-login-page`. It'd be good to AT these issues at the same time: #1978 #3254 #3299

**Comment by ngaruko** [comment]
LGTM.
Tested by clearing cache, cookies and offline data while logged in - 
**before**
![image](https://user-images.githubusercontent.com/6979995/60403369-4f83ba00-9bf0-11e9-8ac2-4a4940f1fac0.png)
 
**After**
![image](https://user-images.githubusercontent.com/6979995/60403346-12b7c300-9bf0-11e9-92f1-7b7853a7eafb.png).
No warning/message that `session expired` though, but I guess this is good enough for this ticket.

**Comment by garethbowen** [comment]
@ngaruko Did you also test this in the admin app?

**Comment by ngaruko** [comment]
@gareth, the admin page seems to work well. However, I am seeing an error with offline users... 
Steps to reproduce:
1 - login as restricted
2 - Disconnect the internet
3 - delete cache, cookies and offline data
4 - click on `contacts` tab

(I would expect this to also  send user to login page)
what happens:
* Spinner showing and error in console:
```DOMException: "A mutation operation was attempted on a database that did not allow mutations." Possibly unhandled rejection: {} inbox.js:3:524433
    a http://localhost:5988/js/inbox.js:3
    require<[771]</</< http://localhost:5988/js/inbox.js:3
    c http://localhost:5988/js/inbox.js:3
    $digest http://localhost:5988/js/inbox.js:3
    evalAsync http://localhost:5988/js/inbox.js:3
    completeTask http://localhost:5988/js/inbox.js:3
    r http://localhost:5988/js/inbox.js:3
```

![image](https://user-images.githubusercontent.com/6979995/60404574-44d02180-9bfe-11e9-80e2-684acfb040b1.png)

**Comment by garethbowen** [comment]
@ngaruko I don't think that's a valid use case as you've wiped out the app. What you need to be doing is testing what happens if the session expires. The easiest way to replicate that is to _just_ delete the session cookie and nothing else.
