### ISSUE TITLE
Filter bar is big on Tasks page, but has no content

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#3935]
On the main _Tasks_ list, the filter bar takes up lots of space, but never has content.

Ideally, it would be shrunken like on the _About_ page.

**Comment by alxndrsn** [comment]
@garethbowen Is this a bug, or is it deliberately big because clicking through to a task might have filter bar content?

**Comment by garethbowen** [comment]
@alxndrsn When you select a task it gets the title of the task. It could be shrunk until you select a task. Maybe we should just wait till the nav redesign in 3.1 when it'll be changed completely anyway?

**Comment by sglangevin** [comment]
I think we should just leave this one for now. We'll be changing all of the navigation really soon anyway, so it doesn't seem worth changing.

**Comment by alxndrsn** [comment]
🤷‍♀️ If no one minds, I might fix this when I have a spare 10 minutes.
