### ISSUE TITLE
Webapp doesn't work offline at root URLs

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4004]
# Observed

https://alpha.dev.medicmobile.org <-- will *not* work offline
https://alpha.dev.medicmobile.org/medic/_design/medic/_rewrite/ <-- *will* work offline

## Environment

* desktop chrome

# Expected

Both URLs should work when accessed offline.

**Comment by garethbowen** [comment]
I have no idea why we're exposing the `medic/_design/medic/_rewrite/` bit - surely our app should just be available at the root URL?

**Comment by Jodge** [comment]
#5361

**Comment by garethbowen** [comment]
Closing as a duplicate.
