### ISSUE TITLE
Remove `lie` from production bundle

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4014]
`enketo-core` [imports `lie`](https://github.com/medic/medic-webapp/blob/master/package-lock.json#L2387).  I suspect we already have a polyfill for `Promise`, so we should be able to exclude this via [an override in `Gruntfile.js`](https://github.com/medic/medic-webapp/blob/master/Gruntfile.js#L53-L72).

**Comment by garethbowen** [comment]
Angular depends on `Q` for its `$q` service so we could use that. It's a little risky to switch out internal dependencies so it would have to be a significant saving to make it worthwhile.

**Comment by SCdF** [comment]
NB: In 3.0 we'll be in a position to not even need anyone's Promise polyfil, so it may be worth excising them all then.

**Comment by garethbowen** [comment]
Closing this. I'm not comfortable switching implementations which aren't guaranteed compatible, and I don't think this will save much of dem bits anyway.
