### ISSUE TITLE
Need variable default value for XForm field

### ISSUE THREAD

**Issue by abbyad** [medic/medic#4105]
In order to get a default value into a field it is possible to use the `default` column in XLSform. This value however is static, and cannot change based on other field values. To have a "variable" default for a text area we are using `calculate`, which worked in Enketo but unlikely supported in base ODK. The calculate would in effect prepopulate the field, which could then be edited by the user. It was used as such in Standard to allow a nurse to edit the "default" message that was to be sent to the CHW -- and that default message would be different based on previous information in the form, and language as well. 

As of `2.13` this method no longer works (as reported by @mukesh2006). Any edits to the text area are not saved with the form, likely since the field's value is recalculated on the page flip as part of https://github.com/medic/medic-webapp/issues/3870, overwriting the edits. This can be seen in the form's summary page since it shows the default message, not the edited one. 

We might be able to find another way to do this in the XForm, but would still likely using a non documented bug/feature of the ODK implementation. We should look for, or create, a supported way to do have variable default values.

**Comment by abbyad** [comment]
@alxndrsn I didn't put the `bug` label, but we do have live projects that can no longer not use existing forms as they previously did. Let us know if there is a quick fix or another way to do this. In the meantime, we will look at modifying all the Standard forms to avoid this issue until it is resolved.

CC @sglangevin, @derickl, @jillrshah

**Comment by alxndrsn** [comment]
Can you just put the default value straight into the model?

**Comment by abbyad** [comment]
That's what the `default` column in XLSform does, but it cannot (yet) be variable. Do you know of another way that supports a variable default?

**Comment by alxndrsn** [comment]
No.  Do we have a simple form which isolates the behaviour?

**Comment by abbyad** [comment]
[Here is a shortened form](https://github.com/medic/medic-webapp/files/1644119/issue_4105.zip) that would show the behaviour. The form has the full functionality as it was used pre 2.13, with choice items used to select and translate the default values of the text area.

**Comment by abbyad** [comment]
This may be of use here: https://opendatakit.github.io/xforms-spec/#setting-a-static-value-when-a-nodes-value-changes

It looks like it may be supported by Enketo already, in which case we are set. Otherwise we may need to look at implementing it but at least it gives us a standard way to proceed rather than cutting our own.

**Comment by sglangevin** [comment]
This has a workaround for current projects that is being deployed with version 2.14 shortly.

**Comment by abbyad** [comment]
Deprioritized this issue since we haven't had any other urgent need for it in the last 18 months.

**Comment by abbyad** [comment]
Since there isn't an urgent need for this, we are better off using (or implementing) Actions & Events, as per #4131.
