### ISSUE TITLE
Write example test for tech lead form testing

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4118]
Things to consider:
* page objects
* assert which page you're on
* intuitive setting of values, probably by model name, w/o form name included
* assert fields, sections visible/hidden
* clear error messages, ease of debugging

**Comment by sglangevin** [comment]
This doesn't need to be a requirement for 2.15.0, from my perspective. Let's consider moving this to a later release.

**Comment by alxndrsn** [comment]
Potential candidate for a first test: https://github.com/medic/medic-projects/issues/3828

**Comment by garethbowen** [comment]
Done.
