### ISSUE TITLE
Show meaningful error when 'username' is already taken

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#4209]
When creating a new user, if the user name is already in the database, the UI shows `Error updating user` message. It would be good to have a more meaningful error as it is in the console (` "Username "data" already taken."`. 
![image](https://user-images.githubusercontent.com/6979995/36398169-9e4c85b0-162a-11e8-9669-c9e26f303abf.png)

**Comment by garethbowen** [comment]
@peter-ochieng How's this issue going?

**Comment by peter-ochieng** [comment]
@garethbowen Am working on implementing PR review changes from Diana, hope to finish by end of day.

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.4`

**Comment by ngaruko** [comment]
I am seeing this error @dianabarsan and the submit button hangs there forever. Please note that I checked this on my local since our test instances are still on 3.3 pending AT/RT. So they might some environmental factors affecting this, but I don't have any problem updating an existing user or creating a user with a unique name.
![image](https://user-images.githubusercontent.com/6979995/52382730-4e37e080-2adb-11e9-95dc-def0cf36a47b.png)

**Comment by dianabarsan** [comment]
@ngaruko can you please tell me which version you are testing this on?

**Comment by ngaruko** [comment]
@dianabarsan Tested on latest `master` on my local machine.

**Comment by dianabarsan** [comment]
@ngaruko This is caused by https://github.com/medic/medic/commit/317864546ed0c1776eb3a9e03759d9c62c232c4e which updates the `Translate` service in `Webapp`, which this feature now uses incorrectly. I assume that the working branch for this feature was created earlier than this change, but was merged after.

**Comment by ngaruko** [comment]
Thanks @dianabarsan. I will push it back and check if @peter-ochieng could rework on this to be work with the new changes

**Comment by ngaruko** [comment]
Hi @peter-ochieng . This works on `master` which is at 3.5 but does not work on 3.4 (as seen on `gamma.dev`). Maybe the fix needed to be back-ported?
![image](https://user-images.githubusercontent.com/6979995/53306442-f6c6ac80-38f1-11e9-955f-94aea709aeee.png)

**Comment by peter-ochieng** [comment]
Hi @ngaruko I back-ported the fix to `3.4.0`
If you can have a look,Thanks

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/53444725-cb6bcb00-3a73-11e9-876d-e75cb8ce6803.png)

**Comment by garethbowen** [comment]
`3.4.x` commit: https://github.com/medic/medic/commit/214edb286bef64fb67df83c2e8d6850f47575812
