### ISSUE TITLE
Refactor sms api endpoint status updates to use medic-sms/sms-messages view

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4368]
Using this view to map WO messages, using the message's UUID as the key, should be more efficient and a bit more sane than the current approach.

**Comment by garethbowen** [comment]
Scheduling so this can be fixed at the same time as the other scheduled gateway fixes.

**Comment by garethbowen** [comment]
There's not much info here so I'm not sure but I've done some serious refactoring here as part of https://github.com/medic/medic/issues/5604 so I'm going to close this.
