### ISSUE TITLE
Fix training data script references non-existent view

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4404]
Referenced here: https://github.com/medic/medic-webapp/blob/master/scripts/data_deletion/delete_training_data_utils.js#L132
Not evident here: https://github.com/medic/medic-webapp/tree/master/ddocs/medic/views

This code looks like it's called by two scripts:
1. `scripts/data_deletion/delete_training_data.js`
2. `scripts/data_deletion/delete_training_data_for_group.js`

**Comment by alxndrsn** [comment]
@SCdF any ideas about this?  You were the last person to touch this file, but it doesn't look like a significant change...

**Comment by SCdF** [comment]
Do you mean about why it's calling a non-existent view? No idea, I imagine something got refactored and it got missed. We'd have to pickaxe our way into the depths of git and work it out

**Comment by garethbowen** [comment]
No AT required.
