### ISSUE TITLE
Require or enforce disk encryption in android wrapper

### ISSUE THREAD

**Issue by ghost** [medic/medic#4451]
https://github.com/medic/medic-projects/issues/3863

**Comment by SCdF** [comment]
@browndav I think the real issue can be pulled out of medic projects, it's not an active security problem per se, just a conversation about additional security.

If you agree we should close this and transplant the conversation onto a new normal ticket.

**Comment by garethbowen** [comment]
Closing as it's not likely to get support from projects.
