### ISSUE TITLE
Cannot send multiple scheduled messages at same time

### ISSUE THREAD

**Issue by abbyad** [medic/medic#4498]
As seen in https://github.com/medic/medic-webapp/issues/4453#issuecomment-385440778, messages from a group cannot be sent at the same time. Only one message per group goes from `scheduled` to `pending` when [due_tasks.js](https://github.com/medic/medic-webapp/blob/ba2715130682cf6f7cd60b15868c1a57a4824304/sentinel/schedule/due_tasks.js) is run (every 5 minutes).

This can lead to puzzling behaviour, as seen below, where scheduled messages are not going to `pending` when you may expect them to:
![image](https://user-images.githubusercontent.com/789512/39436941-7455b3b6-4c6d-11e8-9b7c-2bf139530285.png)

We should decide if this is a bug that needs to be fixed, otherwise document accordingly.

## Steps to reproduce
1. Upload a config with multiple scheduled messages going out at the same time, or within a 5 minute span.
1. Submit a form that triggers the schedule.
1. Observe the `scheduled` time vs `pending` time for each message.

## What should happen
All scheduled messages should go from `scheduled` to `pending` within 5 minutes of the scheduled sending time.

## What does happen
If there is more than one message that should go to pending in a 5 minute span only the first one goes to `pending`. The others go to pending one at a time every subsequent 5 minutes.

**Comment by garethbowen** [comment]
Yeah I noticed that too - it's due to [sentinel uniquing on the doc id](https://github.com/medic/medic-webapp/blob/master/sentinel/src/schedule/due_tasks.js#L48). AFAICT it's been around for a while and it probably doesn't crop up much in the wild but it does seem unnecessary.

**Comment by dianabarsan** [comment]
Ready for AT on `4498-multiple-due-tasks`.
Please do not merge post AT, a shared lib needs to be published and dependencies updated.

**Comment by ngaruko** [comment]
LGTM.
To @dianabarsan for a merge

**Comment by dianabarsan** [comment]
Merged.
