### ISSUE TITLE
Invalid report not being replicated to facility user

### ISSUE THREAD

**Issue by jillrshah** [medic/medic#4621]
Related to (https://github.com/medic/medic-webapp/issues/3437), submitting an incorrect report _D 1234 F_ is not seen by the facility-user, but incorrect reports _D 123456 F_ and _D 12345 F_ are - even though there aren't patients with any of those IDs. Seems to be a case that slipped past AT in medic-webapp.

**Steps to reproduce**:
 - _Submit Delivery text form in Standard configuration with too short Medic ID_

**What should happen**:
 - _As a facility-based user higher in the hierarchy than the CHW that submitted the report, I should see the invalid report and the auto-reply that is scheduled to the CHW._

**What actually happens**:
 - _I don't see it as a facility-based user but do see it as an admin user._

_https://standard-release.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/f582533b5bd76da19cf8d3dae6011eb0_

**Environment**:

- Instance: standard-release.dev.medicmobile.org
- Browser: Chrome
- Client platform: Mac
- App: webapp
- Version: 2.14.3

**Comment by ngaruko** [comment]
LGTM
Report showing higher in the hierarchy with `invalid` flags
![image](https://user-images.githubusercontent.com/6979995/53535979-77dba900-3b69-11e9-9245-3a9be4fcc7c5.png)
