### ISSUE TITLE
SIH integration

### ISSUE THREAD

**Issue by SCdF** [medic/medic#4813]
See this doc for details: https://docs.google.com/document/d/1Ygpi5JzVKYbfWF-uEIc1RCvAPSGq-ut0N8cHMSn5eXY/edit#

@maremegaye is the design contact, @Fatoufall is the PM contact.

We need to have a closed loop flow between us and SIH. We're going to use Sentinel (my boy!), triggered based on docs coming in via data/sms from the CHW, as well as inbound JSON docs coming from SIH itself, to both trigger api calls to SIH (from the former) and trigger SMS back to the CHW (from the latter).

We should:
 - Work out exactly what we want to send to SIH when a referral happens, come up with an example JSON and provide it to them so they can build their api
 - Work out what we'd like them to send us back for the different actions that can happen and create JSON forms with example JSON, provide it to them and configure those forms into [the shared dev instance](https://github.com/medic/medic-projects/issues/4844). SIH can then use [the records api](https://github.com/medic/medic-webapp/tree/master/api#post-apiv2records) to send us these JSON forms
 - build a sentinel transition that take incoming referral reports from a CHW, convert them into a SIH api request and send them along
 - build a sentinel transition that manages the JSON forms created above, and sends SMS' to CHWs based on rules described in the linked document

Things we need for a referral:
 - An identifier for the referral. Should be unique across the whole instance. This makes it easy for impact to link referrals and loop closing actions (the patient arriving at the facility etc) together. We would send this to SIH allowing them to send it back to us.
 - An identifier for the patient. Could be the patient UUID, or their shortcode[1]. Again, we would send this to SIH allowing them to send it back to us. Also lets them re-use / overwrite existing patient records in their system
 - Demographics for the patient: name, dob, sex
 - The CHW who is responsible for them: name, area maybe (check with SIH folks)
 - The referral data itself: danger signs etc, work with @maremegaye to come up with this (also see #4812)

[1] Remember that the patient may already exist, but this might also be the first time the server is hearing about them, because the CHW could be offline when they are created. If we can fit it maybe we pass the UUID in the referral SMS from the CHW and then send that as well.

**Comment by garethbowen** [comment]
> build a sentinel transition that take incoming referral reports from a CHW, convert them into a SIH api request and send them along

If this can't be done in a generic way, consider building out a plugin architecture so transitions can be deployed separately to the main app so we don't end up with this project specific transition in the main app.

> build a sentinel transition that manages the JSON forms created above, and sends SMS' to CHWs based on rules described in the linked document

If we can use the report submission APIs to receive information from SIH then I think we already have sufficient configurability to send custom SMS messages to CHWs when reports are received without having to write a custom transition.

**Comment by SCdF** [comment]
> If we can use the report submission APIs to receive information from SIH then I think we already have sufficient configurability to send custom SMS messages to CHWs when reports are received without having to write a custom transition.

I don't think we necessarily do, but it would be something the dev would have to investigate and discover along the way, and may be able to mitigate by working with SIH (if they think it's worth moving the complexity onto SIH's side of the fence). For example, when the pharmacy sends a list of medications it could fulfil the intention was to check against the report sent by the doctor to determine if an alert had to be sent to the CHW. We could move that to SIH (ie have them tell us if there is a problem), but it would be a discussion.

**Comment by SCdF** [comment]
Their API documentation (or at least some of it, depending on how quickly you ask for it) available on request

**Comment by Fatoufall** [comment]
@garethbowen for your question and mitigation "For example, when the pharmacy sends a list of medications it could fulfil the intention was to check against the report sent by the doctor to determine if an alert had to be sent to the CHW.": 

SIH is OK to check and send us an alert with missing medications.
Let me know if you have any question

They're are waiting for a test environment to start testing @rosteve

**Comment by derickl** [comment]
@Fatoufall, once the feature is released, @medic/site-reliability-engineering will set up the test environment.

**Comment by SCdF** [comment]
@derickl this was not my intention, though I realise that is not communicated in this ticket, but instead this one: https://github.com/medic/medic-projects/issues/4844

Basically, we should setup a 3.x environment so we can then deploy branches to it whenever we want via horti, to allow us to develop and test the relationship between the two servers in a quick and agile fashion.

**Comment by diannakane** [comment]
@reginamutuku 
The latest update is that @SCdF sent API examples to SIH, they sent back a very brief and incomplete api doc of their own; Alex has been working on SMS sending from the android wrapper. 

The issues related to this integration (#4844  #4811  #4812  #4813) are scheduled in 3.3. We are hopeful that development will be done by end of the year, though some of the issues may still be in acceptance testing. We have not been given a deployment date for this integration - do you know of one?

**Comment by Fatoufall** [comment]
@diannakane please provide any additional question about SIH they are very responsive and willing to help to move forward. Last monday @SCdF had no additional question but let me know and I will follow up

@rosteve is setting up a test instance with the help of Henok this week 

The deployment is scheduled first week of January when we will be back from vacation (January 7th) 
I would need to know what is the dependencies between dev and TL to be able to archieve this knowing that we all will  be on vacation by mid- December

**Comment by SCdF** [comment]
Note: this ticket is kind of general, so we're going to use it for tracking our end-to-end progress.

The SMS portion of this work has been delayed until a later release.

So this ticket now broadly covers
 - Adding support for *sending* data to SIH: the details of which are dealt with in #5499 
 - Making sure we can *receive* data from SIH: the details of which are dealt with so far in #5589 (if we encounter more issues we'll raise more tickets)
 - Testing this flow end to end with co-operation with SIH

**Comment by abbyad** [comment]
Sounds good, thanks @SCdF.

@Fatoufall do you have an issue for the configuration of the integration itself, and the work related to forms and tasks?

**Comment by Fatoufall** [comment]
@senseibara followed up on this and can update us

**Comment by garethbowen** [comment]
I believe the only part left in this issue is:

> Testing this flow end to end with co-operation with SIH

Assigning to @michaelkohn to try it out!

**Comment by kennsippell** [comment]
@senseibara Is unable to test this on mobile due to #5646. I am rebasing the branch in an attempt to get a working build for AT.

**Comment by kennsippell** [comment]
@senseibara  Actually, I just realized I did a weird thing here by rebasing a 3.5 change on top of a 3.6 change. So this actually still isn't a valid branch for AT. I'll have to revisit and publish versions of these shared-lib packages.

**Comment by kennsippell** [comment]
@senseibara Ready for testing!

**Comment by senseibara** [comment]
hey @kennsippell , i could push it to the instance and i am able to test now , thanks you so much 👍🏽

**Comment by ngaruko** [comment]
> hey @kennsippell , i could push it to the instance and i am able to test now , thanks you so much 👍🏽

Does this mean we can close this @senseibara ?

**Comment by kennsippell** [comment]
@ngaruko I think it means AT has begun, not that it has completed. @senseibara?

**Comment by senseibara** [comment]
hey @ngaruko , kenn is right about AT , it is going on and we found some points we need to correct

**Comment by senseibara** [comment]
Working now as expected, except for the sms solution that is not included in this release.

**Comment by newtewt** [comment]
As @senseibara  has tested the end to end nature of all the work I'm closing this ticket. The individual code/feature tickets will remain open as they're being tested. Specifically #5499  I believe is the last one open relating to this.
