### ISSUE TITLE
Add support for malnutrition reporting to standard

### ISSUE THREAD

**Issue by eljhkrr** [medic/medic#4815]

**Comment by eljhkrr** [comment]
@medic/quality-assurance I'm not able to move this into the QA queue for 3.6. Please AT when you get a chance on the `nutrition` branch.

**Comment by ngaruko** [comment]
LGTM...
During Child Nutrition Screening, select ‘yes’ to “Do you want to enroll into a treatment program?*”
![image](https://user-images.githubusercontent.com/6979995/60861386-666c8100-a26e-11e9-97a9-28461e962daf.png)![image](https://user-images.githubusercontent.com/6979995/60861412-84d27c80-a26e-11e9-9372-2b6a965f42e0.png)

The Nutrition follow up for  will be available to that child:
![image](https://user-images.githubusercontent.com/6979995/60861415-8734d680-a26e-11e9-9028-56051de8200d.png)

**Comment by ngaruko** [comment]
However, the branch has conflicts that need to be resolved before merging. Can u have a look and resolve these @eljhkrr ? Then we are good to go.. 👍

**Comment by garethbowen** [comment]
I've fixed the conflict. @ngaruko Is this ready to merge once the build passes?

**Comment by garethbowen** [comment]
Merged.
