### ISSUE TITLE
Allow sentinel transitions to run synchronously against incoming SMS messages

### ISSUE THREAD

**Issue by SCdF** [medic/medic#4857]
Currently the flow for an SMS with a default response is slower than it could be:
 - CHW sends an SMS to the gateway, which takes it and puts it in it's queue
 - Gateway wakes up every minute and sends the SMS to Medic, gets any existing SMS to send back and closes the connection
 - Sentinel asynchronously updates the SMS report to add a default response
 - 1 minute later Gateway talks to Medic, finds this response and sends it out.

We should look into extracting sentinel into a shared lib that we can run in realtime when receiving new SMS. This means we will any resulting SMS as part of the same request.

Combined with #4858 this could greatly increase the responsiveness of SMS.

**Comment by dianabarsan** [comment]
Being such a heap of work, I decided to break this up into multiple pieces:

- [x] Remove Nano from Sentinel
- [ ] Add E2E tests for every Sentinel transition
- [ ] Pulling all transitions out in a shared library
- [ ] Updating Sentinel to use Shared transitions
- [ ] Update API to apply transitions on incoming messages

**Comment by dianabarsan** [comment]
Ready for AT on `4857-detached-sentinel-bis` branch.

**Comment by ngaruko** [comment]
LGTM.
Tested by sending a message via the admin portal and `/api/sms ` and quickly moving to the app message tab to see the result. Messages are sent instantly.
Back to you @dianabarsan for merging!

**Comment by dianabarsan** [comment]
There is one new library to be published and updates to be made so the branch is using the new library. Will merge once I get to a good connection.
