### ISSUE TITLE
Schedules are not cleared for offline contacts/reports

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#4885]
When working offline, a report submitted about a person that is not yet replicated will never be bound to that person by `patient_id` field.
As a consequence, this report will never be considered a `registration` and it's schedule will not be cleared by any clearing mechanism. 

**Steps to reproduce**:
 - Login with an offline user (on `gamma.dev` for example)
 - Go offline
 - Create a new person
 - Submit a pregnancy for this person
 - Go online and allow replication to happen
 - Create a new pregnancy for the same user

**What should happen**:
 - Scheduled tasks from the first report should be `cleared`

**What actually happens**:
 - Scheduled tasks from the first report are `scheduled`

I think we should expand our searching for registrations by checking for the `patient_uuid` field as well. 
I am not aware of what value `medic-client/registered_patients` provides now versus say `medic-client/reports_by_subject` (which indexes by `patient_id`, `patient_uuid` and `place_id`). 
Is there any situation where we'd want to _only_ obtain sms/online reports? If not, maybe we could retire `registered_patients` entirely.

**Comment by ngaruko** [comment]
LGTM.
Tested on `gamma.dev ...v3.4`
