### ISSUE TITLE
Allow a different header label for the list of people on the place profile between different places in the hierarchy

### ISSUE THREAD

**Issue by jillrshah** [medic/medic#4926]
On a place profile, there is a header that describes the list of people in that place. For health systems where the lowest grouping in hierarchy is a family, this header is often "Family Members." However, it seems that this is the same for upper levels in the hierarchy as well. For example, the health center will then show the list of people presumably working at this health center as "Family Members." Of course, we can genericize this label such that it would be "People" but it's more ideal to be able to customize this label per hierarchy label.

**Comment by garethbowen** [comment]
This could be related to the flexible hierarchy feature ( #3639 ).

**Comment by garethbowen** [comment]
This should also be used for the button to create a new person:

![screenshot from 2018-10-31 13-41-05](https://user-images.githubusercontent.com/2064938/47759035-a740ed00-dd12-11e8-8b82-5a28bb4d0ccf.png)

**Comment by garethbowen** [comment]
Done as part of #3639
