### ISSUE TITLE
Improve design and usability of admin app

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#4960]
There are a bunch of small fixes which would improve the UX of the admin app significantly. There is a [design spec](https://docs.google.com/document/d/1LED2FNqt-zCR0MqfTAWYWwHS5eliRpoC0JsrVyuh9_w/edit) of which these can be implemented right away:

- Layout
  - [ ] Set the maximum width for the site content to 1440px so it doesn't look terrible on wide screens.
  - [ ] Add a gap of 30px between the bottom of the header and the start of any page content
- Font
  - [ ] Change the font throughout to Noto Sans
  - [ ] Change the default font size to 16px
- Header
  - [ ] Reduce the header size to @font-extra-large
  - [ ] Change the text in the header to "App settings"
  - [ ] Reduce the height of the header space to 64px tall
- Navigation
  - [ ] Change the background colour of the sidenav area to @background-color
  - [ ] Change the default inactive page text colour from blue to the default text colour
  - [ ] Change the active page styling from an underline to #38464D
  - [ ] Remove the outline when selecting a page
- Settings page > Advanced tab
  - [ ] Add space between text and input boxes (phone number and messaging window sections)
- Languages page
  - [ ] Add space between icons and text in each accordion menu
- Forms page
  - [ ] If easy enough to do, increase the size of the “Choose file” button, or ideally, make it match the other blue buttons
- Targets page
  - [ ] Add space between the two buttons

**Comment by Jodge** [comment]
**Add a gap of 30px between the bottom of the header and the start of any page content**
Already body and header have padding of _20px_ respectively

**Comment by amandacilek** [comment]
Hi @Jodge here is how I was hoping the sizing/spacing would change (old on left, new on right):

![admin - header sizes](https://user-images.githubusercontent.com/26235957/48148134-e8368580-e26d-11e8-89d4-fc859b11ef38.png)

> Already body and header have decent padding of 20px respectively. should that be increased to 30px? 
I would say **yes**, increase to 30px.

> This is really close to 64px do we really need to break down the px to reach target 64px?
I'm not exactly sure what you are describing here. I would like the overall height of the grey header area reduced quite dramatically, (more than 4px).

**Comment by Jodge** [comment]
**increase the size of the “Choose file” button, or ideally, make it match the other blue buttons**
This is dependent largely on the `os` you are using. Example on `mac pc` it appears in a small font but on `linux` platform it appears normal.
Solution involves setting the input type file to `hidden` and create a custom `label for` html tag for it with appropriate `styling`. The only drawback to this method is that the name of the file being uploaded with no longer be shown hence the need for some `js function` to display it.

Do we need all this hassle? I don't think so

**Comment by garethbowen** [comment]
> Do we need all this hassle? I don't think so

I agree. I mentioned this when discussing with @amandacilek that fixing this is actually challenging. Happy to leave it as is for now and we can revisit it at a later date.

**Comment by ngaruko** [comment]
LGTM atm. But In will leave it to you @amandacilek to have a final look, and close it if you are satisfied.

**Comment by amandacilek** [comment]
These updates look good but I'd like to request one small edit. Can we please have the grey background color of the navigation extend all the way to the bottom of the screen?
![screen shot 2019-01-08 at 3 57 00 pm](https://user-images.githubusercontent.com/26235957/50866250-14e64680-135e-11e9-817b-e64ad18c1651.png)

**Comment by amandacilek** [comment]
And if it is easy, could we please add more empty space above the first link "Settings"? As much space as there is between the other links. If you prefer I can make this a new ticket.

**Comment by ngaruko** [comment]
Thanks @amandacilek. I knew I am more visually challenged and that you would pick up something I missed .... I think this could be fixed in this ticket @garethbowen,  if you think it is an easy-win?

**Comment by garethbowen** [comment]
Let's do it. @Jodge Can you add the two improvements Amanda has asked for?

**Comment by Jodge** [comment]
@garethbowen Ok, I'm on it

**Comment by amandacilek** [comment]
Whoops I noticed one more thing. We need to make it clear in the navigation which page you are currently on. Right now the active page momentarily has an underline, but this underline disappears as soon as you click anywhere else.

We could either:
- Style the "active" page with an underline, and ensure it always displays
- Or if the above is problematic, highlight the active page in some other way, such as changing the background color behind the active page, or adding a little vertical bar on the left like we do in the app, or both.

![admin-navigation](https://user-images.githubusercontent.com/26235957/50921340-a3110a00-13fc-11e9-8776-824e53c7c3aa.jpg)

**Comment by garethbowen** [comment]
That PR is back to you @Jodge 

Could you also have a look at this latest request from Amanda?

**Comment by Jodge** [comment]
Ok, just did a PR submission for it

**Comment by ngaruko** [comment]
I will leave this to you @amandacilek to close off once you are satisfied with the look and feel of the pages.

**Comment by amandacilek** [comment]
> I will leave this to you @amandacilek to close off once you are satisfied with the look and feel of the pages.

I was using gamma.dev to review, but I don't see any of these improvements (navigation background, active page styling) there. Could you please tell me what I need to do to refresh my view and see the latest? Or, could you please add a screenshot of what it looks like now?

**Comment by Jodge** [comment]
> I think the width of the navigation space used to be about 200px but now the width looks like it was just reduced to about 172px or so.

@garethbowen this is a ripple effect by padding-left of 10px and the solid 5px border-left on the LHS navigation section. The antidote will be do increase the width of the _navigation sidebar_ to `220px`

**Comment by garethbowen** [comment]
@Jodge Yes I think increasing the width makes sense and avoids a few line breaks, at least in English.

**Comment by garethbowen** [comment]
Merged and ready for AT.

**Comment by ngaruko** [comment]
The styling is now consistent @amandacilek , except one case: `targets > add target`, which is a second level hyperlink
![image](https://user-images.githubusercontent.com/6979995/51715803-15d9e080-209f-11e9-8092-2190ad328a55.png)

Please have a second look and let us know if you are happy with the look and feel of the admin portal as it is.  One thing @dianabarsan mentioned is that ` the admin area is aligned to the left  with header still being centered`.

**Comment by amandacilek** [comment]
Yes, the active page styling now remains even after clicking on different tabs within a page. Thank you for fixing this. I'm a little unclear about that case you mention, Bede. Why can't the active page styling remain when clicking on a second level hyperlink?

I agree with Diana that we need to fix the header alignment. Before, the page content was centered on the screen, so the header made sense, but now the page is left-aligned again. I don't have a strong preference one way or the other but we definitely need to make sure the header layout matches whatever alignment we choose. I think I remember @garethbowen saying he preferred site content to be left-aligned as this made the coding easier. If the page content remains left-aligned, then please also left-align the title "App Settings" and move the "Application" and "Log out" links to the far right.

**Comment by ngaruko** [comment]
> I'm a little unclear about that case you mention, Bede. Why can't the active page styling remain when clicking on a second level hyperlink?

It could be @amandacilek . I just mentioned that it was the only case where we lose stying... and it is the only instance where we lose track of the page (or styling). Please have another look and let @Jodge know if you think it needs more work. It shouldn't too big of a job IMO. The form I am referring to is [App Settings >> Targets >> Add Target](https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite#/targets/edit/): 
![image](https://user-images.githubusercontent.com/6979995/51953070-c2510380-249f-11e9-88c1-1cd0a34789c0.png)

**Comment by garethbowen** [comment]
@ngaruko I fixed this in the last commit - it's now ready for review again.

**Comment by ngaruko** [comment]
LGTM - Closing
![image](https://user-images.githubusercontent.com/6979995/52185729-57307400-2887-11e9-9145-7f03fcf4b93f.png)
