### ISSUE TITLE
Write a script that collects all aggregate docs from users' meta dbs

### ISSUE THREAD

**Issue by SCdF** [medic/medic#4968]
Once #2031 is live we'll be generating aggregate telemetry docs and storing them in user meta dbs.

This location is intentional to reduce churn in the main DB, but is a pain since there are now as many DBs with telemetry docs in them as there are users.

Write a script that finds all user meta dbs (`_all_dbs`, filtered by whatever the regex is), and finds all the telemetry docs in that (they all have `"type": "telemetry"`), and.... does something with them.

Once we have them it's up for discussion, but maybe for now just pipe them out to stdout. We can then combine that with other scripts / functions later depending on what we want.

**Comment by SCdF** [comment]
Great idea.

Also, since writing this ticket I realised what we would use them for, which is the performance monitoring described in [this part of the Racing Stripe](https://docs.google.com/document/d/1OhAuHdaWBoNA0rTSDMAu9g88rqVHIWJQckdYQHmx3eU/edit#heading=h.z4vz46y2cdlu).

I don't think this necessarily changes the requirements of this ticket, they could still be put somewhere neutral and then picked up by that work in a separate script / piece of work.

**Comment by kennsippell** [comment]
Is there a comprehensive plan for how to build this monitoring system? How will we present telemetry data to project staff? Will we have configurable alerting? Do we want to track not just performance, but also user engagement and user behaviour stats? How will all of this be presented. It seems like doing this properly is a huge investment...

Before we get too deep into building our own custom telemetry system we might want to draw up a full plan for what we need. It would be interesting to see how much of our requirements are satisfied by existing telemetry systems like [offline google analytics](https://developers.google.com/web/updates/2016/07/offline-google-analytics) which is supported for offline progressive web apps with service workers (us).

**Comment by garethbowen** [comment]
The telemetry implementation is definitely a baby step. It'd been on the back burner for a while (years) waiting for a complete solution and we felt it was better to start with something basic and get it collecting data. It can definitely be replaced by a third party implementation at a later date but it's not a high priority right now.

The initial use case was gathering data that developers could analyse to confirm and start to debug reports of slow app start times. This way we can find out exactly which users are being affected.

Even if we do end up replacing the telemetry implementation at some point the script described in this issue will still be useful for collecting feedback docs so we should continue with this as is.

**Comment by SCdF** [comment]
> Before we get too deep into building our own custom telemetry system we might want to draw up a full plan for what we need.

Unfortunately attempting this is what caused it to not go anywhere for years, as Gareth suggests.

TBC I'm cool with replacing it with whatever, whenever. I'm mostly interested in it existing at all, and then people seeing the data and caring about it, which will hopefully spur interest in putting the effort in you suggest. I think this approach also allows us to be a bit more exploratory with understanding how it can be helpful. In the past we kept on getting stuck on working out exactly what it was and wasn't for we never got to actually having any data in the first place.

**Comment by garethbowen** [comment]
@newtewt This is "Done" - can the issue be closed now?
