### ISSUE TITLE
Change medic-os PR merge strategy to squash

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic#4972]
Seeing merge commits in recent git history suggests the repo settings should be changed.

**Comment by garethbowen** [comment]
This would mean squashing is the only option - you wouldn't be able to merge individual commits without submitting two separate PRs. I think this makes sense as the only time I don't squash is when the UI defaults to the wrong option and I forget to check.

@abbyad @SCdF What do you think?

**Comment by abbyad** [comment]
Are we talking about changing it throughout all repos or just `medic-os`? Either way, I am fine with it. We can add a note in our workflow docs on either how to avoid unnecessary merge commits, or how to merge fast forward.

**Comment by garethbowen** [comment]
Done.
