### ISSUE TITLE
Memory leak when switching between tabs

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5050]
This is a script which switches between the messages and contacts tab every 5 seconds.

```JavaScript
setInterval(() => $('#messages-tab').click(), 5000);
setTimeout(() => setInterval(() => $('#contacts-tab').click(), 5000), 2000);
```

I did the following:

1. Load WebApp
1. Navigate to all tabs to ensure view warming.
1. Trigger GC
1. Measure Heap size and DOM Node Count.
1. Start the script
1. Wait some duration
1. Trigger GC
1. Measure Heap size and DOM Node Count.

Results after waiting 10 minutes:

Metric | Before | After
-- | -- | --
Heap | 163MB | 195 MB
DOM Nodes | 17,000 | 410,000

A second run for 5 minute without live-list drawing in contacts tab:

Metric | Before | After
-- | -- | --
Heap | 126MB | 327MB
DOM Nodes | 17,000 | 200,000

Measures imply some sort of resource leak. This was on Chrome 70, so could be bogus. Worth investigating further.

**Comment by SCdF** [comment]
@kennsippell were the chrome dev tools open or closed when you did these tests?

**Comment by kennsippell** [comment]
@SCdF Open. I haven't attempted to measure precisely, but still appears to be a leak (slower) when closed. You have good reading on the impact of DevTools on this?

**Comment by SCdF** [comment]
@kennsippell definitely not a good reading, but I have noticed that leaving dev tools open overnight in our app (so not changing tabs, just completely idle, and against an idle local DB) can often cause huge amounts of ram usage for the tab and often a lot of cpu usage.

However, I have not put effort into replicating or isolating this-- sometimes I just wake up after working on webapp the day before and my laptop fan goes nuts. I have just always presumed that dev tools === slow + dodginess. That could be a bad presumption though...

**Comment by dianabarsan** [comment]
@kennsippell I've pushed some changes to a [branch](https://github.com/medic/medic-webapp/tree/5050-fix-mem-leaks), as an attempt to fix some of these memory leaks. 
I've touched Messages, Contacts and Reports. 

If you find the time, could you please checkout and re-run the tests with these changes? Thanks in advance!

**Comment by kennsippell** [comment]
@dianabarsan Added most recent measures into the PR.

**Comment by dianabarsan** [comment]
To AT, follow these steps:

1. Login as a restricted user with a healthy number of docs (they need to have data in all tabs for the test to be valid!) in some incognito browser - this is important as any extensions you may have would possibly interfere with the results
2. Visit all tabs and let them load completely
3. Go to Messages tab
4. Open DevTools and go to Performance tab, _force garbage collection_ and then open Performance monitor (Settings -> More tools -> Performance monitor)
5. In performance monitor, make sure it registers JS heap size, DOM nodes and JS event listeners. These are the metrics we will follow.
6. Switch to console and run this script, __closing DevTools__ after it starts:

```
(() => {
  let i = 0;
  const mInterval = setInterval(() => {
    if (i % 5 === 0) $('#messages-tab').click();
    if (i % 5 === 1) $('#tasks-tab').click();
    if (i % 5 === 2) $('#reports-tab').click();
    if (i % 5 === 3) $('#contacts-tab').click();
    if (i % 5 === 4) $('#analytics-tab').click();
    if (++i > 100) {
      clearInterval(mInterval);
    }
  }, 2500);
})();
```

(2500ms was enough of a timeout to load any tab completely on my PC, but you can increase this interval if it's too low).

7. Let the script do it's thing. When it's done repeat from step 4, recording the 3 metrics after every iteration. Repeat as many times as you like, maybe at least 4 times.

8. Compare metrics across iterations. Slight variations are normal. It's very important to force garbage collection before recording. 
There is also more information/discussions on the PR: https://github.com/medic/medic-webapp/pull/5073#issuecomment-445877319

**Comment by ngaruko** [comment]
Start

![image](https://user-images.githubusercontent.com/6979995/53677947-fe84b780-3d1c-11e9-9e62-12afa655490c.png)
**Run 1**
![image](https://user-images.githubusercontent.com/6979995/53678012-dea1c380-3d1d-11e9-9a41-5b698a5d244e.png)

**Run 2**
![image](https://user-images.githubusercontent.com/6979995/53678078-ef066e00-3d1e-11e9-9314-fd118ed4aaef.png)

**Run 3**
![image](https://user-images.githubusercontent.com/6979995/53678166-fda15500-3d1f-11e9-98be-f7e5e883d1ab.png)

**Run 4**
![image](https://user-images.githubusercontent.com/6979995/53678621-a2269580-3d26-11e9-99da-46290f7e87c6.png)

**Run 5**
![image](https://user-images.githubusercontent.com/6979995/53678765-5ecd2680-3d28-11e9-82d1-44bc57af97fd.png)

**Comment by dianabarsan** [comment]
@ngaruko 
Are you sure you are following the steps exactly, including running the tests with a closed dev tools in an **incognito** browser? 
I ran them again, myself, on gamma.dev with a restricted user and these are my results:

![mem-no-leak](https://user-images.githubusercontent.com/35681649/53691899-87d4d200-3d8f-11e9-84ec-c40255aff805.png)

A total of 6 runs, for the last 2 I included the performance status before clicking on the garbage collect button too. 

Can you please tell me how and where you are testing this, so I can try to replicate?

**Comment by ngaruko** [comment]
![image](https://user-images.githubusercontent.com/6979995/53701996-50d1ef80-3e67-11e9-88b4-5f988578e73b.png)

![image](https://user-images.githubusercontent.com/6979995/53702106-4fed8d80-3e68-11e9-807b-673efbdd45f1.png)

![image](https://user-images.githubusercontent.com/6979995/53702235-9a233e80-3e69-11e9-9959-051f0c4378d7.png)

(after GC)
![image](https://user-images.githubusercontent.com/6979995/53702244-b0c99580-3e69-11e9-9332-e7cfd3725e87.png)


![image](https://user-images.githubusercontent.com/6979995/53702397-474a8680-3e6b-11e9-82e3-d3f28a02087f.png)

![image](https://user-images.githubusercontent.com/6979995/53702511-a3fa7100-3e6c-11e9-915d-56cad14ed164.png)

![image](https://user-images.githubusercontent.com/6979995/53702572-61856400-3e6d-11e9-8ab0-1e4820767d83.png)

==
![image](https://user-images.githubusercontent.com/6979995/53702650-16b81c00-3e6e-11e9-9519-eafb6fbd921f.png)

![image](https://user-images.githubusercontent.com/6979995/53702714-c8574d00-3e6e-11e9-8d5c-bd425dbcf637.png)

![image](https://user-images.githubusercontent.com/6979995/53702878-91823680-3e70-11e9-9c78-427672f1f29e.png)

**Comment by dianabarsan** [comment]
Running the test 4 times on gamma.dev, logged in as the user indicated by @ngaruko 

![mem-no-leak](https://user-images.githubusercontent.com/35681649/53716569-039d5000-3e5e-11e9-9cd2-7640f2423e62.png)

**Comment by ngaruko** [comment]
LGTM
Thanks @dianabarsan 
![image](https://user-images.githubusercontent.com/6979995/53799239-d1473c00-3f9e-11e9-8148-17258cf05461.png)
