### ISSUE TITLE
Task titles on overdue tasks only are appearing red

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5057]
This issue was discovered while creating the CHT Demo. Unsure if this affects all projects/instances or just some.

Currently: On the main LHS Tasks list, if a task is overdue, the task title (second line of text) is displaying red in color.

What it should be: All task titles should be the normal black color, no matter if they are due in the future, due today, or overdue.

Note: This has nothing to do with the optional third line of text to indicate high risk. The third line of text, if applicable, should remain, and always be, red.

![screen shot 2018-11-30 at 9 29 15 am](https://user-images.githubusercontent.com/26235957/49304873-71626600-f482-11e8-8720-c4ada761c8b3.png)

**Comment by wtekeu** [comment]
@amandacilek does this apply to contacts list as well? ("Last visit unknown" or when last visited date is overdue)

**Comment by amandacilek** [comment]
No, I'd like to keep the text on the contacts page as-is (if UHC mode is turned on, and if date last visited is unknown or over 30 days, the date text should be red).

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev v3.3` by submitting a delivery report, thus generating a `postnatal visit` task and setting the system date to the future to make the task look overdue.
![image](https://user-images.githubusercontent.com/6979995/53312326-7a47c400-3919-11e9-88cb-16811f7225a9.png)
