### ISSUE TITLE
PouchDB replication _bulk_get requests no longer batched

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5076]
Since the upgrade to PouchDB `7.0.0` (in 3.1.0), replication `_bulk_get` requests are no longer batched (in standard PouchDB 100 docs limit). 
This is caused by [this commit](https://github.com/pouchdb/pouchdb/commit/2987c56311ae2d170d7c1d856470894f760a819a), which changes the moment `onChange` events are emitted.
Instead of being emitted sequentially, thus allowing the replicator to split the changes into batches, all `onChange` events are emitted at once and their processing delayed until `nextTick`. 
Together with the fact that our filtered replication ignores PouchDB limit of 100 changes per request, means that, for initial replication at least, there will be a single `_bulk_get` request to get all docs (potentially thousands). 

Do you think this could be a problem, @garethbowen? I'm afraid of timeouts specifically.

**Comment by garethbowen** [comment]
Yes that's concerning. Can you remember why we don't limit the changes feed? It seems like limiting changes to 100 would be good for the server scalability and help the client reliably finish the initial replication (thought it may take slightly longer on a good connection).

We may need to change the initial replication code to keep trying until it's caught up rather than relying on a single request to complete but it seems like a better design.

What do you think?

**Comment by dianabarsan** [comment]
There are a couple of reasons we don't (rather didn't) limit the changes feed:

1. Pre 3.0 - Because we would batch the requests made to CouchDB with 100 `doc_ids` to take advantage of the optimizations done to that path in Couch 1.x, then we would merge the results and return everything. Together with the fact that seq-s cannot be reliably compared and sorted, it would have been impossible to generate a correct last_seq to return. 
2. Post 3.0 - Because when querying with `_doc_ids` filter and `limit`, the `last_seq` returned was not reliable (when doing next queries following received last_seq, many changes were skipped). 
**NB** I have tested and found this bug on Couch 1.x, Couch 2.0, Couch 2.1 and Couch 2.2.
**It appears to have been fixed in Couch 2.3 !! :tada:**

I will run some more tests in Couch 2.3 to make extra sure that last_seq's are indeed reliable, if they are, there are no impediments into returning batched changes!

**Comment by garethbowen** [comment]
@dianabarsan Is this ready for AT?

**Comment by dianabarsan** [comment]
@newtewt please hold off acceptance testing, I found a bug regarding this implementation that I have to fix. 

The bug is in regards to appending changes which are being received by the continuous feed while the upstream feed had not yet completed. 
These changes are, at the moment, added to the response, even if they are out of place, and their seq-s could cause PouchDB to set the incorrect checkpoint.

**Comment by dianabarsan** [comment]
This seems to have hit Muso in 3.2 while trying to sync users with large numbers of docs (one user had 20k docs, the other had 12k docs). 
Alternatively, the `_all_docs` request fails with a timeout and aborts replication OR (worse) the following `_bulk_get` request times out and PouchDB falls back to getting docs one by one (thinking that _bulk_get is not implemented in Couch), and resulting with a console full of `ERR_INSUFFICIENT_RESOURCES` errors.

**Comment by garethbowen** [comment]
@dianabarsan I've merged this in to `master` (3.4.0 at the time of writing). The backport is a little complicated because there are multiple PRs to do, so I thought it'd be better to leave it to the expert - would you mind backporting it? I'm happy to review the backport if you think that's worth it.

**Comment by dianabarsan** [comment]
Yea, sure, absolutely. I already have a (now outdated) PR for the 3.3 branch, which I will update tomorrow morning first thing.

**Comment by garethbowen** [comment]
Backported to `3.3.x` - ready for AT!

**Comment by newtewt** [comment]
This is looking good. I'm able to replicate large users on phones and interrupt replication and pick back up.
