### ISSUE TITLE
Remove the places card on the RHS from your home place

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5092]
Remove the "places" card on the RHS profile of a user's home place. This card duplicates the info in the main list on the LHS, and is not necessary.

![places card - example 1](https://user-images.githubusercontent.com/26235957/49770470-5f11d480-fc99-11e8-84d0-8023d71c5188.png)
![places card - example 2](https://user-images.githubusercontent.com/26235957/49770471-5f11d480-fc99-11e8-96d3-4b1e42fc8a57.png)

**Comment by wtekeu** [comment]
@amandacilek I have deployed the master branch locally and I have created bunch of districts, health centers, areas, people and user (admin, chw, district manager) but I don't get the UIs that you attached. This is what I get:

<img width="1195" alt="screen shot 2018-12-14 at 2 51 21 pm" src="https://user-images.githubusercontent.com/1445164/50024250-be305b80-ffaf-11e8-9403-5d9833440ae3.png">

<img width="1197" alt="screen shot 2018-12-14 at 2 52 35 pm" src="https://user-images.githubusercontent.com/1445164/50024304-e9b34600-ffaf-11e8-95e9-e054479fa5bc.png">

So my question: what do I need to do to reproduce your screens?

**Comment by amandacilek** [comment]
Hi Willy, the images I attached are fake mockups, so may not be exactly reproduce-able. What we want to do is get rid of the card on the RHS that duplicates the items shown in the LHS list. 

In the first screenshot that you uploaded, the section that we would desire to remove is the third one on the RHS titled "Health centers" with "Health 1" underneath it. 

In the second screenshot that you uploaded, I do not see an equivalent section on the RHS. If it _were_ there, it would have a title like "Places" or "Families" with "Father 1 Area 1", "Mother 1 Area 1" and "Willy Area 1" underneath it. However, this second screenshot that you uploaded looks strange in other ways as well so I'm not sure that this is a good example (the titles of both hierarchy levels say "area" which is odd, and I didn't think we ever displayed individual people on the LHS except when searching).

**Comment by amandacilek** [comment]
I know I probably need to clarify the technical request but I'm struggling to figure out how to explain it. I think we only want to hide the "Places" card for users who are "Regional user - restricted to their place". We don't want to hide the card for users who are "National manager - access to all docs", because those users rely on the Places card to navigate deeper into the hierarchy.

Here is the situation I am referring to where we DON'T want to hide the "Places" card:
![screen shot 2018-12-14 at 1 38 40 pm](https://user-images.githubusercontent.com/26235957/50028791-a6ec7080-ffa5-11e8-8704-737ff462563f.png)

@garethbowen @abbyad I'm tagging you both here to see if you have a better way to explain the request in more technical terms, since I'm struggling to.

**Comment by ngaruko** [comment]
Can I push this to to you @amandacilek just to confirm that it is was you wanted before closing it?
Thanks

**Comment by abbyad** [comment]
@ngaruko, I don't think @amandacilek is set up to do AT on this, so if you can share relevant screenshots (eg from different levels of the hierarchy) it would make it easier for her to confirm.

**Comment by ngaruko** [comment]
LGTM
`Places` card not displaced for restricted users
![image](https://user-images.githubusercontent.com/6979995/53460442-04bb2f80-3aa2-11e9-8c4b-c8556ba5d98f.png)

but accessible for admin
![image](https://user-images.githubusercontent.com/6979995/53460496-37fdbe80-3aa2-11e9-84f4-031a3db94803.png)
