### ISSUE TITLE
All reports synced doesn't notice new reports

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5108]
To reproduce:
 - Be an offline user
 - Be fully synced (You can click the sync button to do this)
 - Create a new report

What should happen:
 - The sync status should say that you are now not fully synced (because this new report hasn't replicated yet)

What does happen:
 - It thinks you are fully synced

Offline user view:
![image](https://user-images.githubusercontent.com/583851/50080804-d63cf080-01e4-11e9-87bc-52c8e9e28393.png)

Online user view:
![image](https://user-images.githubusercontent.com/583851/50080811-d9d07780-01e4-11e9-99d4-5a0ae1ff7e47.png)

MacOS Chromium latest, master codebase.

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/52686507-e2f67e80-2fb2-11e9-9ea7-8d587cb4b70e.png)
