### ISSUE TITLE
Translation key should be mandatory

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5120]
**Steps to reproduce**:
1. Go to the [add translation form](https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite#/translation/application)
2. leave `translation key` blank.
3. submit form
 _
 

**What should happen**:
 - _User should get an error in the UI when you hit submit without a translation key._

**What actually happens**:
 - _The form is submitted successfully, which adds an empty row to the translations table
![image](https://user-images.githubusercontent.com/6979995/50664715-ee997180-1012-11e9-9afe-ed00b5c54293.png)
 _

- Instance: _(gamma-b.dev.medicmobile.org, etc)_
- Browser: _(Firefox, Chrome)_
- Client platform: _( MacOS)_
- App: _(webapp, admin)_
- Version: _(3.2.x, 3.4.x, etc)_

**Comment by abbyad** [comment]
@ngaruko, please edit the issue to include the relevant bits from the other issue so that this issue is readable on it's own. Thanks!

**Comment by ngaruko** [comment]
LGTM
Back to you @garethbowen 
![image](https://user-images.githubusercontent.com/6979995/54964860-e843e180-4fd2-11e9-855a-13769828411e.png)

**Comment by garethbowen** [comment]
Already merged. Closing.

**Comment by garethbowen** [comment]
The key can't be renamed for any translations, so that's fine. I chose to change the styling because I wanted them to stand out.

Already merged. Closing.
