### ISSUE TITLE
We should be able to add Keys with no translations

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5121]
**Steps to reproduce**:
1. Go to the add translation form
2. add a translation key but leave all translations blank.
3. submit form 
 
**What should happen**:
 - None of the keys are mandatory so you should be able to submit, but we should update the translation list UI to show the key with some styling (maybe italics?) so it's not just left blank..

**What actually happens**:
 - the translation is not actually created, only an empty row in the translations table 
![image](https://user-images.githubusercontent.com/6979995/50664942-c100f800-1013-11e9-9c05-c6a9d6da92d6.png)
. 

- Instance: _(gamma-b.dev.medicmobile.org, etc)_
- Browser: _(Firefox, Chrome)_
- Client platform: _( MacOS)_
- App: _(webapp, admin)_
- Version: _(3.2.x, 3.4.x, etc)_

**Comment by abbyad** [comment]
@ngaruko, please edit the issue to include all the relevant info so that this issue is readable on it's own. Thank you!

**Comment by ngaruko** [comment]
LGTM.
Two things though
a) the format looks different from the rest of the keys (unbold and italic it seems)
b) the key cannot be renamed (in edit mode)

Are these expected behaviors @garethbowen 

![image](https://user-images.githubusercontent.com/6979995/54965134-11b13d00-4fd4-11e9-9f32-c39d17e4dde0.png)

**Comment by garethbowen** [comment]
The key can't be renamed for any translations, so that's fine. I chose to change the styling because I wanted them to stand out.

Already merged. Closing.
