### ISSUE TITLE
Improvements to the report summary page UI

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5123]
A few improvements to the task summary UI (the last page the user sees before clicking submit):

- **1. Increase the margin above main section headers (H1)** so that there is more blank space between the end of one section and the start of a new section. Currently the sections are all squished together and it is not necessarily clear which section a colored bar belongs to.
![task-summary-header-spacing](https://user-images.githubusercontent.com/26235957/50254952-e3084280-03a4-11e9-9085-0e847c41e60c.jpg)

- **2. Change the font sizes for H1 and H2** so that the sizes conform more to expected hierarchy rules. The size of H1 should be increased to 18px, and the size of H2 should be decreased to 20px.
- **3. Increase the height of the horizontal colored bar to 40px.**
- **4. Ensure that the icon on the left is vertically centered** within the colored bar.
![task-summary-h1-h2](https://user-images.githubusercontent.com/26235957/50316939-cf74de80-046d-11e9-9e98-4866b93639f9.jpg)

- **5. Adjust the alignment of H3 text** so that the text is not indented. It should be left-aligned instead.
- **6. Ensure that there is a consistent left margin of 20px** between the far left edge of the form and the beginning of any left-aligned text.
![task-summary-h3-align](https://user-images.githubusercontent.com/26235957/50316989-14991080-046e-11e9-8da8-2ac0da04e309.jpg)

**Comment by garethbowen** [comment]
> 1. Increase the margin above main section headers (H1)

Done.

> 2. Change the font sizes for H1 and H2

Done.

> 3. Increase the height of the horizontal colored bar to 40px.

I didn't do this because I wanted it to be relative to the font, rather than a fixed height. By making the font larger it's also made the coloured bar larger so I think this is roughly the same as what was intended.

> 4. Ensure that the icon on the left is vertically centered within the colored bar.

Done.

> 5. Adjust the alignment of H3 text

It should only be centred if the centred appearance is also applied, so it's configurable.

> 6. Ensure that there is a consistent left margin of 20px

@amandacilek I couldn't replicate this - what form were you using?

**Comment by garethbowen** [comment]
Ready for AT in `5123-enketo-summary-updates`

**Comment by newtewt** [comment]
On smaller phone screens the icon is overlapping in the headers. See screenshot. 


![Screenshot_20190807-143105](https://user-images.githubusercontent.com/10531066/62626919-65bf1d00-b8f6-11e9-8309-df829e56e01e.png)

**Comment by garethbowen** [comment]
@newtewt Good spotting. Ready for review again.

**Comment by newtewt** [comment]
Looks good!
