### ISSUE TITLE
Only send tombstone deletes when document is still deleted

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5186]
If a document is deleted and then re-added (once or repeated), the deletes should not be included in the offline changes feed - even if the deleted `rev` is lower, PouchDB replication still considers the last rev it has received as winning. 

Discovered after fixing https://github.com/medic/medic-webapp/issues/5078 (send form deletes to offline users). 
When updating forms, medic-conf first deletes existent forms and then uploads new ones.

**Comment by dianabarsan** [comment]
To AT (and simulate an action that is likely to happen), run medic-conf on a test instance to re-upload forms. Then, initial-replicate as a restricted user and make sure all forms have been downloaded.

**Comment by newtewt** [comment]
I'm seeing the forms download correctly after multiple pushes with medic-conf
