### ISSUE TITLE
Work out how to run CI tests for outside collaborators

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5198]
Currently the travis build fails when testing a PR from a contributor outside of Medic. This is due to [these users not having access to the secure environment variables](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) we use to publish to the testing staging server.

>  [4mRunning "couch-push:testing" (couch-push) task[24m
> [31m>> [39mError: Invalid URI "undefined/_couch/builds_testing/_all_docs"
> [31m>> [39mError: Invalid URI "undefined/_couch/builds_testing/_all_docs"
> [33mWarning: Task "couch-push:testing" failed. Use --force to continue.[39m

https://api.travis-ci.org/v3/job/475430272/log.txt

Find a way to execute all CI stages on PRs from non-Medic contributors.

**Comment by isaacholeman** [comment]
I was wondering if we could start using  a tag to track  issues like this that are directly intended to support a more collaborative community and lower barriers to entry for new devs and people who aren’t working for Medic Mobile. Something like _FOSS Community_ or _CHT Community_? @garethbowen @abbyad @CescaGarrett

**Comment by vimemo** [comment]
hi @garethbowen, would you please take a look at these updates:
https://github.com/medic/medic/pull/5572/files

and the travis error:
https://travis-ci.org/medic/medic/jobs/515369022

Hope you can see something obvious.
Thank you.

**Comment by garethbowen** [comment]
@vimemo Here's the log with the problem: https://api.travis-ci.org/v3/job/515369021/log.txt . In particular:

```
[4mRunning "couch-push:testing" (couch-push) task[24m
[31m>> [39mError: Invalid URI "undefined/_couch/builds_testing/_all_docs"
[31m>> [39mError: Invalid URI "undefined/_couch/builds_testing/_all_docs"
[33mWarning: Task "couch-push:testing" failed. Use --force to continue.[39m
```

I think the issue is that the code you added is not being run in the compile stage because the compile stage defines its own before_script which overrides where you made your change. What this means is when the compile completes it tries to upload the built package into the testing db but the URL is still undefined.

You'll need that block of code you wrote to be executed for the compile stage only because the other stages should only read from the db so don't need the credentials.

**Comment by garethbowen** [comment]
Merged. No AT required.
