### ISSUE TITLE
Translations for new bootstrapper states added by purging

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5224]
The bootstrapper uses its own translation system because it executes before Angular is loaded. Since the translation of keys added to this system won't be caught through the normal translation workflow, I'm adding an item to track these translations.

Purging added three new states for the bootstrapper which should be translated:
- "Checking data…"
- "Cleaned ${n} documents (${percent}% complete)…"
- "Optimising…"
- "Downloading App..."

[] Spanish
[] Swahili
[] Nepali 
[] French
[] Hindi

**Comment by garethbowen** [comment]
@jillrshah Are you able to follow up with someone to get these translated?

**Comment by jillrshah** [comment]
Just confirming that you want the translations for these three terms for those languages and I should just paste them here rather than using POEditor? @kennsippell

**Comment by jillrshah** [comment]
(Any specific reason you don't want Hindi?)

**Comment by kennsippell** [comment]
Yep that's correct - please just paste the translations here and we need to manually put them in place for this part of the app.

Good question about Hindi. Would you translate all of these statements for Hindi?

`Fetching info (10 docs)…`
`Loading app…`
`Checking data…`
`Cleaned 10 documents (5% complete)…`
`Optimising…`
`Loading rules…`
`Starting app…`
`Loading error, please check your connection.`
`Try again`

**Comment by jillrshah** [comment]
Sounds good! Please give me a few days, I'll aim to get done by regional teams by end of week or early next week.

**Comment by jillrshah** [comment]
Hi @garethbowen @kennsippell - translations in this Google Doc. Downloading app will be added by tomorrow (sorry, missed that one because added later and last week got away from me). https://docs.google.com/spreadsheets/d/1FB0o9hXeyWrxNJwq4KmOhtOvuSUfxRIq_JlygdVp-Yk/edit

**Comment by jillrshah** [comment]
All translations are up to date in the file referenced above. Thanks!

**Comment by garethbowen** [comment]
Great, thanks! I'll get right on this.

**Comment by garethbowen** [comment]
Merged to `master` and backported to `3.4.x` and `3.3.x`

**Comment by garethbowen** [comment]
@newtewt Yes it should work right away. It's based on the language set for the user which is stored in the userCtx cookie, so have a look there and see if it's set right.

When you say:

> I see the english version of loading app and then it switches to the translation eventually.

At what point does it switch?

**Comment by newtewt** [comment]
I have attached a video that shows the messages in English and then Spanish translations. 


[translation-startup.mov.zip](https://github.com/medic/medic/files/2814582/translation-startup.mov.zip)

**Comment by garethbowen** [comment]
Very helpful, thanks. The translations in the "startup" phase are handled completely separately from the translations in the app. It looks like the former is just not working. I'll have a look.

**Comment by newtewt** [comment]
@SCdF  I've seen it every-time so far when on the purge-upgrade-muso instance. Albeit I've only had a chance to replicate a few times so far this morning.

**Comment by garethbowen** [comment]
Fixed in master and ready for AT once more.

**Comment by garethbowen** [comment]
On further inspection it's not in the "userCtx" cookie, it's set in the "locale" cookie instead. This is only set once you start the app so doesn't work for initial replication. To check this if you refresh the app it should show in Spanish next time through. However it's most important that it works for the first load because this is the one that'll do the initial replication and take the longest!

We should change the API login code to set the "locale" cookie as well as the "userCtx" and session cookies.

**Comment by garethbowen** [comment]
PURGE_INIT is a very short time between when the reports have been collated and the first reports have been purged. Slower devices may take time here. @SCdF I wonder if we should move it to before the `reportsByContact` call, or maybe remove it altogether?

STARTING_APP is shown between bootstrapping (initial replication, purging, etc) and angular taking over and rendering its states.

You can force these to show by putting debug points in the JS code. Alternatively get a really slow device and try that...

**Comment by SCdF** [comment]
> PURGE_INIT is a very short time between when the reports have been collated and the first reports have been purged. Slower devices may take time here. @SCdF I wonder if we should move it to before the reportsByContact call, or maybe remove it altogether?

Yeah that's a great point, and I don't know why I didn't do this in the first place. That event sure fire once we've decided that we are going to purge.

I've made a note to do this, I presume it's not critical though?

@newtewt if you want me to do this today (it's not hard, I just have other priorities) ping me on Slack and I'll get it done :-)
