### ISSUE TITLE
Clarify and streamline process for investigating e2e flakey test failures

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5228]
There were four issues related to flakey e2e tests in v3.4. Investigating these failures is something devs spend time doing and we can be more productive as a team by improving how our e2e tests run and how failures are reported.

A few potential improvements to look at:

* Can we have an easy flag or command which which runs e2e tests in chrome instead of headless to tests are visible?
* Travis uploads some log files to s3. Several devs (myself included) don't know what is getting uploaded or how to access the files.
* Can we get a screenshot at the time of the flakey test failure?
* Can we see the chrome console at the time of the failure?
* Can we see a full dump of the DOM at the time of the failure?
* Bonus points if e2e tests fail because of errors in the console logs during the test.
* There are some tips/tricks for investigating e2e test failures (like enabling protractor's control flow and [this](https://github.com/gabduss/runProtractorVsCodeExtension) vscode extension). A quick doc capturing these tips might be helpful. Maybe a new section in [this](https://github.com/medic/medic-docs/blob/master/development/testing.md) or alike.

**Comment by garethbowen** [comment]
> Can we have an easy flag or command which which runs e2e tests in chrome instead of headless to tests are visible?

Yeah, makes sense. Maybe `grunt e2e-chrome` or something? I'll have a look.

> Travis uploads some log files to s3. Several devs (myself included) don't know what is getting uploaded or how to access the files.

They're getting uploaded to: https://s3.console.aws.amazon.com/s3/buckets/medic-e2e/

You will need AWS access to see them. Unfortunately it's currently broken due to https://github.com/medic/medic-webapp/issues/4877

> Can we get a screenshot at the time of the flakey test failure?

That is supposed to work, both locally and uploaded to s3. Is it not working now?

> Can we see the chrome console at the time of the failure?

I think there's a way to log the entire console and then that could be accessible just like api and sentinel logs. I'll work on this too.

> Can we see a full dump of the DOM at the time of the failure?

Not sure. I'll have a look.

> Bonus points if e2e tests fail because of errors in the console logs during the test.

I'm worried this will lead to flakiness. We could give it a try and see...

> There are some tips/tricks for investigating e2e test failures.  A quick doc capturing these tips might be helpful...

I'm on it!

**Comment by kennsippell** [comment]
> That is supposed to work, both locally and uploaded to s3. Is it not working now?

I think it works now with https://github.com/medic/medic-webapp/commit/ee8406b5ab9c016f50fbf2161b85a59c44693dba. I think I just mostly never knew about it.

> Can we see the chrome console at the time of the failure?

I think we have this already with the existing reporting extension for jasmine.

**Comment by garethbowen** [comment]
Two PRs to review please @kennsippell

**Comment by garethbowen** [comment]
I think most of this is done. @kennsippell Are you happy for this to be closed, or are you holding out for anything else in particular?

**Comment by garethbowen** [comment]
Code review please @kennsippell 

This logs the browser console to a file in tests/logs. We have lots of severe log items so we can't fail the build on them unless we figure out a long allow list. This should at least make debugging possible.

**Comment by kennsippell** [comment]
Sweetness
