### ISSUE TITLE
Resources doc re-downloaded on every change in list pages

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5229]
Every time a change updates the LiveList, or when paginating, the `resources` doc and all it's attachments are re-downloaded (Contacts, Reports and Tasks use LiveList).
This seems unnecessary since there already is a change watcher for the document.

**Comment by ngaruko** [comment]
Any clue on how to AT this @dianabarsan ?

**Comment by dianabarsan** [comment]
@ngaruko 
You should make sure that the `resources` doc only gets requested if needed.
So login as admin, open the network tab and search for `resources` and refresh the app. Upon load, the `resource` doc should be downloaded **once**. Then navigate to reports or people and paginate, add new reports and so on, keeping an eye on the network tab to make sure that the `resources` doc is not redownloaded. 
As a last check, update the `resources` doc (change an icon or something obvious) and make sure that the change is picked up (the doc should get redownloaded at this point) and the UI is updated accordingly.

**Comment by ngaruko** [comment]
LGTM-
Initial load: ![image](https://user-images.githubusercontent.com/6979995/53474535-30eea480-3ad2-11e9-8727-4d8ae913ef93.png)

Upon adding one icon
![image](https://user-images.githubusercontent.com/6979995/53474692-a5c1de80-3ad2-11e9-913a-957aafa695a0.png)

**Comment by dianabarsan** [comment]
@bede yes, online users would need to download this doc on every page refresh. Maybe this has changed since the Service Worker was added in 3.5, but for 3.4 this would be expected behavior.
