### ISSUE TITLE
Pass user context to the purge function

### ISSUE THREAD

**Issue by abbyad** [medic/medic#5246]
In conversations about facility-based workflows we are seeing that the purge function needed by a CHW could be different than that needed by their supervisors or facility-based users. We are seeing this requirement for closed-loop referrals where facility staff are using the mobile app in offline mode to have tasks about their patients, but only need very specific reports to do their work. If they have all the reports for all their patients they would have too many docs on their device for it to function properly. As a result, we should make sure to pass the user's context information (ie lineage, role) to the purge function so that we can purge based on that context information.

_This is a follow up to #5048, and came up via discussion about partner requirements with @SCdF_

**Comment by garethbowen** [comment]
@abbyad @SCdF What fields do you think we need here?

- user roles are the easiest and most useful
- contact and facility doc IDs are quite easy but not very useful
- hydrated contact lineage is a little more tricky but potentially useful if we want to allow different purging rules for different branches of the hierarchy
- anything else?

I'll implement it to be forwards compatible so we can add more of this information in a future release without breaking existing purge functions.

**Comment by SCdF** [comment]
Agree on user roles being the most obvious. Also agree on contact and facility ids not being that useful. However, I see value in just aping the `userCtx` object as much as possible.

> hydrated contact lineage is a little more tricky but potentially useful if we want to allow different purging rules for different branches of the hierarchy

Presumably you're talking about doing this without using a view, but instead using the object map of contacts to link in that way?

I think if we wanted to do this we might as well also take the time to convert the user's contact and facility ids into real docs as well using the same code flow.

However, that would almost certainly slow performance down by a reasonable large amount, what with all the Object tree rewriting, so we'd have to test for that and see if we wanted to take the hit.

My vote would be just roles for now, and we can look at more beefy features when we move to server side and initial replication purging performance is less of a concern.

**Comment by abbyad** [comment]
Although having access to everything sounds nice, taking the performance hit may not be worthwhile. Now that we have the ability to add custom roles I think it would be good to rely on that rather, and not enabling purge rules that are specific to people/place UUIDs.

**Comment by garethbowen** [comment]
The implementation looks reasonably straightforward so I'll backport this to 3.3.0.

**Comment by garethbowen** [comment]
Code review please @SCdF . Feel free to leave merging and backporting to me.

**Comment by SCdF** [comment]
@garethbowen sorry I saw the PR notification before the comment... I already merged, but will leave backporting to you :-)

**Comment by garethbowen** [comment]
Backported to `3.3.x`. Thanks!

**Comment by newtewt** [comment]
Looks good. I'm conditioning my purge based on the roles included from the user context object.
