### ISSUE TITLE
Country code and Gateway phone number fields shouldn't be required

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5249]
In the App Settings console > Settings page > Basic tab, neither the default country code nor the gateway phone number should be required fields.

These two fields are for SMS contexts but there are some projects that don't even have a gateway so they should not be required.

**Comment by ngaruko** [comment]
LGTM...
_**Before**_
![image](https://user-images.githubusercontent.com/6979995/51943814-5a8ac080-247f-11e9-8b1c-200979554ed2.png)


**_After (v3.4)_**
![image](https://user-images.githubusercontent.com/6979995/51943848-6d04fa00-247f-11e9-880c-8a8f020b016e.png)
