### ISSUE TITLE
Adding or deleting languages should update the UI without needing to refresh

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5250]
In App settings > Languages page > Languages tab, adding or deleting a language is not initially reflected in UI until navigating away from the tab and then coming back to it.

**Steps to reproduce**:
 - Go to the Languages tab and look at what languages are currently displayed
 - Use the blue button to add a new test language
 - After you click "Submit", look again at what languages are currently displayed. There is no new addition.
- If you navigate to the second "Application text" tab, and then back to the "Languages" tab, finally the new test language will appear in the UI

**What should happen**:
 - As soon as you click "Submit" on the add new language dialogue window, the Languages tab should update to show the new language in the list.

**What actually happens**:
 - Currently, the Languages tab does not update with the new language until navigating away and coming back.

**Setup**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome
- Client platform: MacOS
- App: admin app

The same thing happens when deleting a language.

**What should happen**:
 - As soon as you click "Delete" on the "Are you sure you want to delete this record?" confirmation window, that particular language should disappear from the list.

**What actually happens**:
 - Currently, even after clicking "Delete", the deleted language remains displayed in the list. It does not disappear until navigating away from the Languages tab and then returning.

**Comment by ngaruko** [comment]
LGTM  - UI auto refresh
