### ISSUE TITLE
E2E tests which login as restricted user are blocked by service worker on Chrome 71

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5267]
In #5219, a purge test which logs in as a restricted user is being disabled. 
The reason for disabling this test is detailed [here](https://github.com/medic/medic-webapp/pull/5219#issuecomment-456569431).
When Chrome 72 moves from beta to stable, this test should be re-enabled.

Impactful for #5214.

**Comment by garethbowen** [comment]
@kennsippell Chrome 72 is now stable... from a recent build:

> Unpacking google-chrome-stable (72.0.3626.81-1) over (62.0.3202.94-1) ...

I'll leave you to tidy this up in the SW PR.

**Comment by kennsippell** [comment]
Fixed no that Chrome 72 is stable.
