### ISSUE TITLE
Bootstrap failed retry button doesn't work

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5270]
1. Navigate to webapp 3.4 (master)
2. Login as restricted user.
3. Go offline during initial replication.
4. Click "Try again"

Observed error:

```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-6i0jYw/zxQO6q9fIxqI++wftTrPWB3yxt4tQqy6By6k=' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
```

Reported by @kennsippell

**Comment by garethbowen** [comment]
This is a regression from #5082

**Comment by ngaruko** [comment]
This seems to work atm. However, I have left a comment around related issue [#5082](https://github.com/medic/medic/issues/5082#issuecomment-462613787) @kennsippell . Will keep this open as reminder for now.
