### ISSUE TITLE
Message queue not loading when translations are missing

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5272]
When loading Admin's message queue, we try to load all languages in Angular before generating messages. We do that by iterating over all languages and issuing a call to Angular Translate, which effectively loads the language. 
If the key we are trying to translate doesn't exist, Angular Translate throws an error and, as a result, the message queue does not load. 

![image](https://user-images.githubusercontent.com/35681649/51597103-1f2e4600-1f03-11e9-9132-ceb530911e31.png)

Discovered after translations failed to be updated by an upgrade (https://github.com/medic/medic-webapp/issues/5271).

**Comment by ngaruko** [comment]
LGTM 
![image](https://user-images.githubusercontent.com/6979995/52603992-0d224080-2ece-11e9-8a61-2e8b25158592.png)
