### ISSUE TITLE
Lint the browser compatibility of our code

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5280]
We should use this: https://github.com/amilajack/eslint-plugin-compat

To set our browser version compatibility in web code.

**Comment by Jodge** [comment]
@SCdF good suggestion!
I have a question `eslint-plugin-compat` uses the `browserslist` configuration in `package.json` so what browserslist should we pick to be targeted by this plugin?

Example: currently for postcss autoprefixer we are targeting  `['last 2 Firefox versions', 'Chrome >= 54']`

**Comment by SCdF** [comment]
@Jodge our current browser compatibility is documented here: https://github.com/medic/medic-docs/blob/master/installation/supported-software.md

For firefox (which we just say "latest") you might want to make it the last ~4 versions (eg last 6 months) or something .

**Comment by Jodge** [comment]
@SCdF I guess this requires no AT, and can be closed?

**Comment by SCdF** [comment]
Correct, yep
