### ISSUE TITLE
Integration tests labeled as "passing" by travis even when not all E2E tests run

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5293]
Here is a build labeled as passing by Travis: https://travis-ci.org/medic/medic/builds/484489080?utm_source=github_status&utm_medium=notification

In the logs for the integration suite, I see:
```
Ran 147 of 199 specs
147 specs, 1 failure
Finished in 200.341 seconds
An error was thrown in an afterAll
AfterAll Expected $[0] = '_id,form,patient_id,reported_date,from,contact.name,contact.parent.name,contact.parent.parent.name,contact.parent.parent.parent.name,bar,baz,foo,smang.smong,wd_array,wd_emptyString,wd_false,wd_naughtyArray,wd_naughtyString,wd_null,wd_zero' to equal '_id,form,patient_id,reported_date,from,contact.name,contact.parent.name,contact.parent.parent.name,contact.parent.parent.parent.name,bar,baz,foo,smang.smong'.
Expected $[1] = '"export-data-2-test-doc-3","b","abc125",1517616000000,,,,,,,"bazVal",,,,,,,,,' to equal '"export-data-2-test-doc-3","b","abc125",1517616000000,,,,,,,"bazVal",,'.
>> 15:32:21.411 INFO [ActiveSessions$1.onStop] - Removing session e364978fac8e4d420bbf8e1456f82bc6 (org.openqa.selenium.chrome.ChromeDriverService)
[15:32:21] I/launcher - 0 instance(s) of WebDriver still running
[15:32:21] I/launcher - chrome #01 passed
Closing report
```

The suite took only 5 minutes to run and typically takes about 8 minutes.

**Comment by garethbowen** [comment]
Does it seems strange that we're running assertions in an `afterAll`? I wonder if that's unsupported behaviour.

I can't see the log any more - did you restart the build?

**Comment by kennsippell** [comment]
What about here? https://travis-ci.org/medic/medic-webapp/jobs/485043046

**Comment by garethbowen** [comment]
Yeah that's better! Not sure where I was looking...

**Comment by SCdF** [comment]
@kennsippell I have fixed where I think the problem is. However, in my branch everything is *passing*, where I'd expect now it would correctly error. However, the branch example you gave is from a few months ago, so it may be the error that was being masked has been fixed.

**Comment by kennsippell** [comment]
I don't think the core of the issue here is a single test which is failing, but rather that the build is passing in travis while tests are failing. I'm less concerned about fixing a specific test and more concerned about fixing the wire-up to travis to ensure that builds fail when tests fail.

**Comment by dianabarsan** [comment]
@kennsippell 
Looking at the branch that this build (https://travis-ci.org/medic/medic/jobs/485043046 - your example) ran on, it looks like you've disabled a number of tests on purpose (https://github.com/medic/medic/commit/910e1f3dbdc9c5727c491c1a26951d0699debf6b & https://github.com/medic/medic/commit/c67b8088d1cab081316cef5654bc62fe8766c562 & https://github.com/medic/medic/commit/79707b78230a65f6ba967c98d72e25e9afac6a67) which would account for the tests skipped? 
The first commit disables 29 tests and the second disables 22 tests and the 3rd commit disables 1 test (52 in total).

199 - 147 = 52.

![image](https://user-images.githubusercontent.com/35681649/55273382-2c84f980-52d3-11e9-8a5c-6a023b741239.png)

**Comment by kennsippell** [comment]
Well that's embarrassing. Thanks.  

But something is still off that there is `1 failure` and the travis build is failing. Or does our investigation explain that also?

**Comment by kennsippell** [comment]
Tried a few things and it just seems that exceptions or failures in `afterAll` can't easily cause a suite failure. I find this odd. Even more so, that failures in `beforeAll` don't cause failures and the tests in the test class still execute.

Seems the recommended solution in Jasmine is to use a "fail-fast" configuration. But those configurations aren't supported in protractor.   Not sure what action to take here if any. 

Please re-open if you feel there is a path toward excellence which we should consider taking.
