### ISSUE TITLE
Individual builds can no longer be restarted

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5297]
Since we moved to staged builds we are unable to restart individual builds.

For example, if you have a flaky build:
![image](https://user-images.githubusercontent.com/583851/51850362-7ecc8d00-2319-11e9-9691-9122816d5401.png)

And you try to individually restart a build, you'll get the following error:
```
********FATAL********
{ error: 'not_found',
  reason: 'deleted',
  status: 404,
  name: 'not_found',
  message: 'deleted',
  docId: 'medic%3Amedic%3Atest-15021' }
+app=medic-api
+echo '[/home/travis/.nvm/versions/node/v8.15.0/bin/horti-svc-stop] Stopping medic-api...'
```

**Comment by garethbowen** [comment]
I've been thinking about this and I think we need to leave the release on the testing server for some time. So maybe after each build we delete all docs that are older than a week?

**Comment by SCdF** [comment]
@garethbowen I think that makes sense.

Ideally we'd have that function as part of the build server itself (e.g. to also periodically prune branches pushed to the main build server), but that requires us hosting something more complicated than a CouchDB database unfortunately

**Comment by garethbowen** [comment]
No AT required.
