### ISSUE TITLE
Investigate and fix common feedback errors

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5298]
First reported on [this issue](https://github.com/medic/medic/issues/4898#issuecomment-458263351) (comment inlined below) our app is generating a lot of uncaught errors in the browser. Some of these may have already been resolved in a later version of the app.

- Spend some time investigating the most common errors.
- If you ask @michaelkohn nicely he may help you find full stacks for these errors.
- Use the linked spreadsheet to work out what version of the app is affected.
- Link to the fixes where they exist.
- Fix easy bugs.
- Raise issues for complex bugs.
- Note which errors are difficult to trace, and consider improving feedback doc creation to make it easier in future (eg: catch an error and throw another one with a better message).

### Feedback docs created since 1-Jan-2018

The spreadsheet [here](https://docs.google.com/spreadsheets/d/1OMvqi70JbulaMi17Dex2SVZwJpPM9E8TOp0u8OfOyyQ/edit#gid=1979929895) has the breakdown by partners.  

info/message | Count
-- | --
Uncaught   TypeError: Cannot read property 'handleAndroidBack' of undefined | 581,624
Uncaught   Error: Could not resolve 'undefined' from state 'home' | 50,836
Uncaught   TypeError: Cannot read property 'body' of undefined | 18,362
Uncaught   TypeError: Cannot call method 'handleAndroidBack' of undefined | 14,158
Uncaught   TypeError: Cannot read property 'length' of undefined | 13,596
  | 13,526
Uncaught   TypeError: Cannot read property 'scrollIntoView' of undefined | 7,572
Uncaught   Error: Could not resolve 'undefined' from state 'about' | 6,433
Uncaught   TypeError: document.querySelectorAll(...).forEach is not a function | 6,286
Uncaught InvalidStateError: Failed to execute 'index'   on 'IDBObjectStore': The transaction has finished. | 1,475
Uncaught   Error: Could not resolve 'undefined' from state 'tasks.detail' | 1,334
Uncaught TypeError: fieldset:disabled input,   fieldset:disabled select, fieldset:disabled textarea, input:disabled,   select:disabled, textarea:disabled is not a function | 988
Uncaught   TypeError: Cannot read property 'clone' of null | 238
Uncaught   Error: Could not resolve 'undefined' from state 'contacts.detail' | 213
Uncaught   Error: Could not resolve 'undefined' from state 'analytics.targets' | 114
Uncaught   TypeError: Cannot read property '_attachments' of undefined | 87
L’objet   ne gère pas la propriété ou la méthode « forEach » | 76
Uncaught   Error: Could not resolve 'undefined' from state 'contacts.addChild' | 61
Script   error. | 57
Uncaught   Error: Could not resolve 'undefined' from state 'reports.detail' | 33
Uncaught   Error: Could not resolve 'undefined' from state 'error' | 28
Uncaught   TypeError: Cannot read property '_id' of null | 26
Uncaught   Error: Could not resolve 'undefined' from state 'messages.detail' | 22
Uncaught   TypeError: Cannot read property 'outerHTML' of undefined | 20
Uncaught   TypeError: Cannot call method 'scrollIntoView' of undefined | 19
Uncaught TypeError:   angular.element(...).injector(...).get(...).v1.simprintsResponse is not a   function | 15
Uncaught FormLogicError: Could not evaluate:   selected(../dob_method,'calendar'), message: Cannot read property   'ownerDocument' of undefined | 15
Object   doesn't support property or method 'forEach' | 14
Uncaught FormLogicError: Could not evaluate:   selected(../vaccines, 'other'), message: Cannot read property 'ownerDocument'   of undefined | 13
Uncaught   Error: Could not resolve 'undefined' from state '' | 10
Uncaught   TypeError: Cannot read property 'toString' of undefined | 7
Uncaught   FormLogicError: Could not evaluate: concat(../../contact/name, ' Family'),   message: Failed to execute 'evaluate' on 'Document': The string   'concat('Ñ\!'è! \"è#9ìčè', " Family")' is not a valid XPath   expression. | 7
Uncaught   TypeError: Cannot read property 'seq' of null | 6
Uncaught   TypeError: Cannot read property 'createObjectStore' of undefined | 6
Uncaught   TypeError: Cannot read property 'balance' of null | 6
Uncaught   TypeError: Cannot read property '0' of undefined | 6
Unable   to get property 'top' of undefined or null reference | 5
Uncaught   Error: Could not resolve 'undefined' from state 'reports.add' | 3
NotFoundError: The operation failed because the   requested database object could not be found. For example, an object store   did not exist but was being opened. | 3
Uncaught   TypeError: Cannot read property 'error' of null | 2
Uncaught FormLogicError: Could not evaluate:   concat(../../contact/name, ' Family'), message: Failed to execute 'evaluate'   on 'Document': The string 'concat(redacted, "   Family")' is not a valid XPath expression. | 2
Uncaught DataCloneError: Failed to execute 'put' on   'IDBObjectStore': An object could not be cloned. | 2
Uncaught   TypeError: Cannot read property 'format' of undefined | 1
Uncaught   TypeError: Cannot call method 'clone' of null | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 4 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 4 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 4 | 1
Uncaught   SyntaxError: Unexpected token in JSON at position 3 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 3 | 1
Uncaught   SyntaxError: Unexpected token in JSON at position 22 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 15 | 1
Uncaught   SyntaxError: Unexpected token  in JSON at position 11 | 1
Uncaught   SyntaxError: Unexpected token in JSON at position 10 | 1
Uncaught   Error: unexpectedly reached end of input: � | 1
Uncaught   Error: unexpectedly reached end of input: @ | 1
Uncaught   Error: unexpectedly reached end of input: ¿ | 1
allocation   size overflow | 1
Grand   Total | 717,321

**Comment by michaelkohn** [comment]
> If you ask @michaelkohn nicely he may help you find full stacks for these errors.

Here are two examples of what I have access to... happy to help pull the data in a way that is easier for others to work with.

[5298_feedback_doc_example_01.txt](https://github.com/medic/medic/files/2808452/5298_feedback_doc_example_01.txt)
[5298_feedback_doc_example_02.txt](https://github.com/medic/medic/files/2808453/5298_feedback_doc_example_02.txt)

**Comment by wtekeu** [comment]
@garethbowen is there a reason behind the reliance on `window.onerror` vs AngularJS error handler `$exceptionHandler`: https://docs.angularjs.org/api/ng/service/$exceptionHandler ?

**Comment by garethbowen** [comment]
@wtekeu Ooh nice one. Originally the code was executed from other places (eg: kanso) so it couldn't use angular services which is why it's in `/webapp/src/js/modules/`. Now that we've finally gotten rid of kanso we can make it an angular service and use other services. Feel free to make that change, or raise a separate issue to make that change. Thanks!

This would possibly also fix an issue we have where all errors in the log appear to come from the feedback service...

**Comment by wtekeu** [comment]
Muso Errors since Jan. 19 2018 (post 3.x upgrade)

info/message | Count
-- | --
Uncaught InvalidStateError: Failed to execute 'index' on 'IDBObjectStore': The transaction has finished. | 319
Uncaught Error: Could not resolve 'undefined' from state 'about' | 84
Uncaught Error: Could not resolve 'undefined' from state 'home' | 56
Uncaught Error: Could not resolve 'undefined' from state 'error' | 14
Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined | 8
Uncaught Error: Could not resolve 'undefined' from state '' | 5
Uncaught Error: Could not resolve 'undefined' from state 'home' | 1

Was not able to debug them as the stack does not include the col number.

**Comment by derickl** [comment]
MUSO was on 2.8.x until April 2018 (2.16) then in Sep/Oct 2018 (2.18), then Jan/Feb 2019 (3.x)

**Comment by wtekeu** [comment]
Sorry, I meant Jan. 19 20**19**

**Comment by garethbowen** [comment]
We should be able to track down where these two are coming from:

- "Uncaught Error: Could not resolve 'undefined' from state 'xxx'"
- "Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined"

The IDB one looks like a PouchDB issue we get from time to time which will be very hard to track down.

**Comment by garethbowen** [comment]
@wtekeu I've merged that refactor - let me know if I can help track down those two errors.

**Comment by wtekeu** [comment]
@garethbowen Yes I need help with the two errors.

**Comment by garethbowen** [comment]
@wtekeu For the first one (* "Uncaught Error: Could not resolve 'undefined' from state 'xxx'") I think that means somewhere we're using `$state.go` or `ui-sref` with an undefined variable. There are only 3-4 places where we use those without passing a hardcoded string. My two top suspects are:

1. the android back button which tries to navigate back to the first visible tab.
2. the tour dialog which redirects you to a page to start a guided tour.

Unfortunately I haven't been able to cause these to error, but we could wrap them in some defensive code that ensures the route isn't undefined/null and maybe even logs a better error explaining what happened so we can fix it properly.

**Comment by wtekeu** [comment]
@garethbowen thanks for the help. I will review.

**Comment by garethbowen** [comment]
For the second one, there are 10 places in the browserified code where we call `scrollIntoView` - mostly in Enketo or the Tour library. I'm guessing it's caused by the Tour library when the element we want the tour step to focus on doesn't exist because they have no reports or whatever. There's only 8 of them so I'm not too worried about it.

For both of these, the feedback docs should have up to 20 lines of console output (info, warn, etc) which might help you work out what the user was doing.

**Comment by garethbowen** [comment]
Closing this for now with improved logging. I'll set up a recurring task to check for errors every month or so until we have proper monitoring set up.
