### ISSUE TITLE
Remove node domain from export data controller

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5300]
The [export data controller](https://github.com/medic/medic/blob/master/api/src/controllers/export-data.js#L126) uses node domains to catch all errors and handle them. This is deprecated and can cause memory leaks (although I don't think this particular code leaks).

Switch to managing the errors without using domains.

**Comment by ngaruko** [comment]
Does this need any AT on our part @Jodge ? Does it affect the `export` feature in the web app?

**Comment by Jodge** [comment]
@ngaruko No, This was just getting rid of deprecated code that could cause memory leak

**Comment by ngaruko** [comment]
Thanks @Jodge - Closing this.
