### ISSUE TITLE
Swahili "starting app" translation missing

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5307]
We missed a translation in the bootstrapper for "Starting app…" in the Swahili language.

**Comment by jillrshah** [comment]
It is "Programu yaanza..."

Thanks!

**Comment by garethbowen** [comment]
Thanks Jill!

**Comment by garethbowen** [comment]
Code review please @vimemo

**Comment by garethbowen** [comment]
Merged and backported to `3.4.x`

**Comment by newtewt** [comment]
Seeing the translation now.
