### ISSUE TITLE
Validate email address when creating or editing users

### ISSUE THREAD

**Issue by peter-ochieng** [medic/medic#5313]
Validate email address when creating and editing users in admin

**Steps to reproduce**:
 - Login with admin credentials
 - Go to AppSettings
 - Under AppSettings, go to Users and click Add user
 - On the Add user popup, enter any value into the E-mail address field and save

**What should happen**:
 - Only valid emails addresses should be accepted to be saved in this field

**What actually happens**:
 - Any value is saved as an email address

**Other**:
_The email validation should only apply if a value has been entered into the Email address field since this field is not a mandatory field when creating users

**Comment by garethbowen** [comment]
@peter-ochieng The associated PR was merged - can this be closed now?

**Comment by peter-ochieng** [comment]
@garethbowen Yes,this can be closed.
