### ISSUE TITLE
Bootstrap translation doesn't work on first load

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5326]
**Steps to reproduce**:
1. As an admin configure a user to have a language other than English
2. Clear all your cookies
3. Log in to the app as the non-English user

**What should happen**:
The bootstrap translations are in the user's language.

**What actually happens**:
The bootstrap translations are in English. If you refresh the translations are in the right language.

[Video](https://github.com/medic/medic/files/2814582/translation-startup.mov.zip) provided by @newtewt 

**Environment**:

- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: api, webapp
- Version: 3.5.0 (head of master)

First reported in #5224

**Comment by garethbowen** [comment]
Merged into `master`, and backported to `3.4.x` and `3.3.x`

**Comment by newtewt** [comment]
This doesn't seem to work. I've installed latest 3.3.x branch on gamma.dev. Is there something I can check to verify the cookie has been set?

I clear cache and cookies in Firefox. 
Log in as tom (user lang set to french)
The starting messages are all in english and after the app loads everything is in French.

**Comment by newtewt** [comment]
Ahh it was the known horti issue with upgrading not actually upgrading. Thanks @dianabarsan 

This is translating the messages as the app starts.
