### ISSUE TITLE
The login page is not translated

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5327]
**Steps to reproduce**:
1. As an admin configure a user with a language other than English or the default app language
2. Go to the login page - at this point the app doesn't know which user it is so will use the default app language
3. Log in as the user configured in 1
4. Log out

**What should happen**:
The login page should be translated into the language you configured in step 1.

**What actually happens**:
The login page is in the default app language.

![login page](https://user-images.githubusercontent.com/2064938/52091047-09620480-2618-11e9-8b99-3a47a9de6578.png)

![cookies](https://user-images.githubusercontent.com/2064938/52091056-11ba3f80-2618-11e9-979f-d2bb18bfaba5.png)

**Environment**:

- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: API
- Version: 3.5.0 (head of master)

**Comment by ngaruko** [comment]
Has this been back ported to 3.3 @garethbowen ? I see it works on a local install running the latest master but not on `gamma.dev` running the latest 3.3.x

**Comment by ngaruko** [comment]
Seems to work on `purge-upgrade-muso-mali.dev` running 3.3.X. I guess there was an error in `gamma.dev` update.
