### ISSUE TITLE
Error loading target details

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5330]
**Steps to reproduce**:
1. Log in as an admin
2. Go to Targets
3. Click on an existing target

**What should happen**:
The name of the target should be displayed. No errors in console.

**What actually happens**:
The name is not shown. There's an error in the console. The name field is also missing when adding a new Target. Also the name column is always blank on the Targets list.

```
Error fetching target TypeError: "$scope.target.name is undefined"
	require<[96]</</< http://localhost:5988/medic/_design/medic-admin/js/main.js:106750:11
	processQueue http://localhost:5988/medic/_design/medic-admin/js/main.js:37529:37
	scheduleProcessQueue http://localhost:5988/medic/_design/medic-admin/js/main.js:37577:27
	digest http://localhost:5988/medic/_design/medic-admin/js/main.js:38690:15
	apply http://localhost:5988/medic/_design/medic-admin/js/main.js:39078:13
	ngEventHandler http://localhost:5988/medic/_design/medic-admin/js/main.js:48434:13
	dispatch http://localhost:5988/medic/_design/medic-admin/js/main.js:69592:16
	handle http://localhost:5988/medic/_design/medic-admin/js/main.js:69401:6
```

![screenshot from 2019-02-01 15-20-18](https://user-images.githubusercontent.com/2064938/52098699-e85bdc80-2634-11e9-9ba5-a435cdf34560.png)

![screenshot from 2019-02-01 15-21-33](https://user-images.githubusercontent.com/2064938/52098746-23f6a680-2635-11e9-89cc-bc8e9ae0bd5e.png)

**Environment**:

- Instance: localhost
- Browser: Firefox
- Client platform: Linux
- App: admin
- Version: 3.5.0 (head of master)

**Comment by Jodge** [comment]
@garethbowen I am unable to reproduce this bug

**Environment:**

- Instance: localhost
- Browser: Chrome / Firefox
- Client platform: Linux - Ubuntu

Maybe @ngaruko could help us also from his side to see if he can reproduce it?

**Comment by garethbowen** [comment]
@Jodge I can reproduce this on gamma.dev (`3.3.x`) - same error in the console but slightly different look. Have a look at this page: https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite#/targets/edit/active-pregnancies

**Comment by Jodge** [comment]
Yeah sure

**Comment by ngaruko** [comment]
LGTM @Jodge 
![image](https://user-images.githubusercontent.com/6979995/55041496-28b66480-5092-11e9-9b30-50fb3774cb50.png)
