### ISSUE TITLE
Testing dev builds on mobile device after service worker change is awkward

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5340]
From #5219.
> This change will block testing on insecure origins except localhost. This is pretty awkward for testing dev builds on a phone – I ran a DNS server + nginx proxy + vpn on my phone to work around it. This is likely something we should address in this change or shortly after. Looking to discuss the best approach.

This issue tracks documenting a clear process to test dev builds on mobile devices.

**Comment by SCdF** [comment]
An alternative might be to use medic-os' docker image as a base, have it run code not form horti but from configured directories, and also have the docker image use SSL with a medic-self-signed certificate, the pub key of the root of which we could manually install on phones we want to test?

**Comment by kennsippell** [comment]
The port forwarding approach through Chrome Dev Tools (detailed in the link above) is super smooth. It works great on Android Chrome 53, but it crashes the Medic app when I try it within the container. I'd have to dig deeper into this SIGSEGV.

@garethbowen @SCdF -- If you gents agree this is the best approach, I'll dig in and try to get this working with the app.

```
02-05 23:11:08.646 14365 14365 I chromium: [INFO:CONSOLE(66)] "Uncaught (in promise) SecurityError: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", source: http://192.168.43.11:5988/login/script.js (66)
02-05 23:11:11.693 14365 14365 D ViewRootImpl@3ae2cab[Toast]: mHardwareRenderer.destroy()#4
02-05 23:11:11.708 14365 14365 D ViewRootImpl@3ae2cab[Toast]: dispatchDetachedFromWindow
02-05 23:11:11.714 14365 14365 D InputTransport: Input channel destroyed: fd=115
02-05 23:11:21.762 14365 14365 D ViewRootImpl@565f1ee[EmbeddedBrowserActivity]: Relayout returned: oldFrame=[0,0][1080,1920] newFrame=[0,0][1080,1920] result=0x1 surface={isValid=true -900403200} surfaceGenerationChanged=false
--------- beginning of crash
02-05 23:11:24.627 14365 14416 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 14416 (Thread-7)
02-05 23:11:24.628 14365 14365 W cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 14365
02-05 23:11:24.629 14365 14365 I MedicMobile: EmbeddedBrowserActivity.onReceivedLoadError() :: [-1] http://localhost:4988/ :: net::ERR_EMPTY_RESPONSE
02-05 23:11:24.629 14365 14365 I MedicMobile: EmbeddedBrowserActivity.onReceivedLoadError() :: ignoring for non-root URL
```

**Comment by SCdF** [comment]
gent... 😊 

For posterity in case it moves around, here is a permalink to the second answer: https://stackoverflow.com/a/43426714/1666

As long as the SIGSEGV isn't a giant pita to solve this seems like a good approach, though I worry it is going to be due to a deep bug in crosswalk or something. I think at some point in the future being able to deploy the whole stack locally based on your git workspace would be ideal (bc we'd be testing all of the layers), but this can happen later.

**Comment by kennsippell** [comment]
I'm beginning to doubt that trying to fix the SIGSEGV in crosswalk is a productive vector. I didn't realize the project was unmaintained. Quite ironically, they stopped supporting crosswalk [because of PWAs](https://crosswalk-project.org/blog/crosswalk-final-release.html) -- the same technology which is causing this problem for us.  

I'm not fully familiar with the responsibilities of the android wrapper -- but would it be possible to have v3.5 become a full-fledge PWA and use that to replace our wrapper? It may be a very round-about fix for this issue.

**Comment by SCdF** [comment]
>  I didn't realize the project was unmaintained

Yeah, the only reason we're still on it these days is partially a small number of old phones that can't get a newer version of the web view, but 95% because you can't override quotas usefully in raw Chrome, and we are worried about hitting size limits and having Chrome silently delete everything

**Comment by garethbowen** [comment]
> Did you have a specific featureset in xwalk in mind to bring your suggestion to life? Any pointers appreciated.

We can add code in our android wrapper for intercepting requests and (hopefully) messing with them, similar to [this issue](https://github.com/medic/medic-android/issues/26). I haven't had a chance at this yet.

> 95% because you can't override quotas usefully in raw Chrome, and we are worried about hitting size limits and having Chrome silently delete everything

We're also baking in more and more features that require an android wrapper, eg: simprints integration, sms sending.

**Comment by SCdF** [comment]
> We're also baking in more and more features that require an android wrapper, eg: simprints integration, sms sending.

Totally, I didn't mean android wrapper vs. Chrome (I shouldn't have used "raw Chrome" sorry), I meant android wrapper + crosswalk vs. android wrapper + webview

**Comment by garethbowen** [comment]
@kennsippell Any update on this? Looks like it may be related to #5611 ?

**Comment by kennsippell** [comment]
@garethbowen - I have a working version on Ubuntu but it doesn't work on Mac due to the same root cause as #5611 (networking limitations on docker+mac). Expect it to work on Windows but remains untested.

To support Mac, it's pretty hard for me without a Mac machine... I could emulate one (just thought of that)? Or rent? Or try to find a friend with one? But I'm not totally familiar with the technical limits of docker here. It was nice working with Nick in Nairobi with his Mac, but now I'm a bit stuck.

Second issue is just that I need to sync with @Hareet and understand what he's doing for the docker image on Mac.

**Comment by newtewt** [comment]
Since we've decided to use ngrok for now I am closing this. The instructions for setup have been merged.
