### ISSUE TITLE
Registration transition invalidates unique ids when creating people

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5345]
When using `registration` transition to create people and also using `patient_id_field` configuration to set the `patient_id` manually, validating the uniqueness of `patient_id` is incorrect: non-unique ids are reported as unique and vice-versa, resulting in correct reports being marked as errored and creating patients with duplicate `patient_id` fields.

**Comment by dianabarsan** [comment]
I ran a quick search in `medic-projects` for `patient_id_field` and it appears that nobody is currently using this feature. I don't think that we need to backport this.

**Comment by garethbowen** [comment]
AT passed. When I provide a unique ID there are no errors. When I provide a non-unique ID there are errors.
