### ISSUE TITLE
The update_scheduled_reports transition runs indefinitely

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5347]
**Steps to reproduce**:
 - Enable `update_scheduled_reports` transition. It requires no additional configuration.
 - make sure Sentinel is running, and it's seq is up to date (empty queue)
 - create this document
```
{
  "_id": "scheduled_form_1",
  "type": "data_record",
  "form": "some_form",
  "fields": {
    "year": 2018,
    "month": 6
  },
  "reported_date": 1549372882579
}
```
 - check the doc after a few seconds (10-20), making sure Sentinel has processed it (you can check `medic-setinel/scheduled_form_1-info` to see that the transition executed)

**What should happen**:
 - `_rev` field should be `2-something` - the doc should have been processed once by Sentinel
 - after the fix, clinic-less docs should not be processed by the transition. 

**What actually happens**:
 - the `_rev` field is much higher
 - if checking Sentinel logs, it keeps processing the same doc over and over (you can stop it by deleting the doc or changing it's `type` field to something else)

The given example treats the case when the doc is not attached to a clinic. 
The issue also happens when the report is attached to a clinic.
```
{
  "_id": "scheduled_form_2",
  "type": "data_record",
  "form": "some_form",
  "fields": {
    "year": 2018,
    "month": 6
  },
  "year": 2018,
  "contact": <insert clinic contact lineage here>,
  "reported_date": 1549374018405
}
```

**Comment by wtekeu** [comment]
@dianabarsan This is what I obtained when testing using branch `3.4.x`

<img width="1263" alt="Screen Shot 2019-05-13 at 4 03 39 PM" src="https://user-images.githubusercontent.com/1445164/57650599-2bfda500-7599-11e9-9987-81679fe4ec0a.png">

<img width="1370" alt="Screen Shot 2019-05-13 at 4 05 08 PM" src="https://user-images.githubusercontent.com/1445164/57650614-31f38600-7599-11e9-96d9-f9c5f8bf8b95.png">

Not exactly what you described I should get. Am I doing something wrong?

**Comment by dianabarsan** [comment]
@wtekeu Does your document have an attached clinic?

**Comment by wtekeu** [comment]
@dianabarsan no I initially tried without attaching a clinic to the document

**Comment by dianabarsan** [comment]
@wtekeu 
AH! Doc errors... 
https://github.com/medic/medic/blob/master/shared-libs/transitions/src/transitions/update_scheduled_reports.js#L13 <- the transition tests for doc errors, and your registration transition adds the `invalid_contact_id` error so, so update_scheduled_reports only runs once, when the doc doesn't have errors.

**Comment by wtekeu** [comment]
ok will try with one

**Comment by wtekeu** [comment]
@dianabarsan I was able to reproduce it with a document without errors. Will continue AT.

**Comment by wtekeu** [comment]
AT complete! Was able to reproduce the issue using the branch `3.4.x`. Changed to `master` and created the same doc and tested. Looking good!
