### ISSUE TITLE
Date formatting in exports is not human readable

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5352]
First raised in [this medic-projects issue](https://github.com/medic/medic-projects/issues/5790) the export files are formatting the date as millis since the epoch which isn't easy for end users to read. These files should be able to be read without having to apply further calculations.

Unfortunately changing the output format would break API compatibility for anyone scripting against the export endpoints.

Add a new parameter to the export endpoints for `human-readable` (or come up with a better name) which defaults to `false` for backwards compatibility. Then update the webapp to add the new parameter everywhere it's being called. Remember to update the API documentation as well.

**Comment by garethbowen** [comment]
Ready for AT in `export-date`.

AT instructions: export all types from the app and ensure the dates are in ISO format, curl the export APIs directly and make sure the dates are in millis, then curl again with `options.humanReadable=true` to make sure the dates are in ISO.

**Comment by ngaruko** [comment]
LGTM,
**Before**
![image](https://user-images.githubusercontent.com/6979995/55767996-2e1ea080-5acf-11e9-952a-afcc92458ee2.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/55767984-24953880-5acf-11e9-982d-a82de312161a.png)

 **However**, `curling`  the export APIs directly without `options.humanReadable=true` does not return the dates are in millis but in ISO. Is that the default @garethbowen ?
![image](https://user-images.githubusercontent.com/6979995/55768655-da618680-5ad1-11e9-9e8e-743628e1299a.png)

**Comment by garethbowen** [comment]
No, the default should be millis. I'll have a look.

**Comment by garethbowen** [comment]
Ok, so I think it was a problem with the documentation. Feedback docs aren't really supported by this option either because their dates are already human readable in the db. I've updated the docs to make this clear. Please have a look at this and make sure it makes sense to you: https://github.com/medic/medic/blob/9e823e5feaef45db6986681c392684ad67aa32a9/api/README.md#export

**Comment by garethbowen** [comment]
@ngaruko Back to you!

**Comment by ngaruko** [comment]
Thanks @garethbowen 
Looks good with other exports. Ready to merge

**Comment by garethbowen** [comment]
Merged. Thanks @eljhkrr !
