### ISSUE TITLE
Serve app from root

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5361]
The `/medic/_design/medic/_rewrite` bit is unnecessary, complicated, confusing, ugly, etc, etc. Serve the webapp app from `/` and the admin app from `/admin`.

- add redirects or proxies so old URLs will still work
- make sure people upgrading with old service workers or appcaches survive the change
- make sure people upgrading with phones which have the old url configured survive the change
- don't assume the database is called `/medic` - take the last bit of the COUCH_URL environment variable that api is given and use that

**Comment by garethbowen** [comment]
This is ready for AT in the `app-root-redirect` branch.

**Comment by garethbowen** [comment]
For AT be particularly careful about upgrading making sure that we don't have to download the changes feed since 0 again, or download the documents into a new database. Make sure that all the old URLs redirect correctly to the new URL. Also check that the service worker is caching everything it should.

**Comment by kennsippell** [comment]
I ATed this as part of 5557. Given today's decision to have devs do AT before moving on to 3.6, I am merging this (one conflict resolved).
