### ISSUE TITLE
Unregistered phone number or person getting an autoreply with correct textform format

### ISSUE THREAD

**Issue by ashish-medic** [medic/medic#5365]
If a valid SMS (correct texform) is sent from an unregistered phone number (not in the hierarchy) is getting autoreply.  `public_form` is set to false in forms is not working. Issue was noticed for textform that were set in patient_reports (Patient Reports) of config.

Issue was posted here 
https://github.com/medic/medic-projects/issues/5411

**Comment by dianabarsan** [comment]
Ready for AT on `5365-phone-verification`.
Post AT, please do not merge. A shared library needs to be published and dependencies updated on the branch. Thanks!

**Comment by ngaruko** [comment]
LGTM.
Have pinged @ashish-medic to do a quick double check and close related issue [medic/medic-projects#5411](https://github.com/medic/medic-projects/issues/5411)

**Comment by ngaruko** [comment]
Back to you @dianabarsan for merge

**Comment by ashish-medic** [comment]
@ngaruko yes working as expected cc @dianabarsan

**Comment by dianabarsan** [comment]
Merged.
