### ISSUE TITLE
Check is missing in checkboxes

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5380]
Using 3.4 locally I'm seeing only a highlighting on selected checkboxes and no check in the box. This is using chrome. Using the android app against my local env it works fine.  Screenshot below shows the highlight box with no check
---

_Brief description of bug encountered_.

**Steps to reproduce**:
Log in
Navigate to a form that has check boxes. (Immunization Visit)
Check some of the immunizations. 

**What should happen**:
A check is displayed in the box. 

**What actually happens**:
The box is highlighted but no check.

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance: running locally to test 3.4
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.4

_And any other environment-specific information you can think of._

![image](https://user-images.githubusercontent.com/10531066/52671280-a0686f80-2ee8-11e9-9f1f-bb20241e65e4.png)

**Comment by garethbowen** [comment]
@newtewt It's working for me..

Firefox:

![screenshot from 2019-02-13 16-44-49](https://user-images.githubusercontent.com/2064938/52685534-ee47ab00-2fae-11e9-9067-e50234ef978c.png)

Chrome:

![screenshot from 2019-02-13 16-46-17](https://user-images.githubusercontent.com/2064938/52685535-ee47ab00-2fae-11e9-89d4-1e5d2ebcdb13.png)

Can you reproduce this issue on a server I can access?

Are there any errors in the console?

**Comment by newtewt** [comment]
Nothing in console. I'll confirm once we get this onto a test instance and close or update.

**Comment by dianabarsan** [comment]
I'm seeing this as well in Chrome 72 on latest master. 
Not seeing it in Chromium 71 or Firefox.

Apparently Chrome 72 doesn't render this (coming from Enketo css):
`background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' stroke='#{$color-stroke}' fill='#{$color-fill}' width='32' height='32' viewBox='0 0 32 32'%3E%3Cpath d='M25.1 12.5l-3.4-3.3-8 8-2.9-3-3.4 3.4 6.3 6.3z'/%3E%3C/svg%3E");`

I only way I got it to render if I converted it to base64.

**Comment by garethbowen** [comment]
I can reproduce this now that my Chromium has updated to 72. Fun...

**Comment by garethbowen** [comment]
This may be the issue: https://stackoverflow.com/questions/54453987/did-chrome-72-break-dataimage-svgxmlutf8-for-css-background-svgs

**Comment by garethbowen** [comment]
If I encode the `#` as `%23` it works as expected. I'll raise an Enketo issue and overwrite this in our css.

**Comment by garethbowen** [comment]
Issue raised with enketo-core: https://github.com/enketo/enketo-core/issues/601

**Comment by ngaruko** [comment]
This is also happening in 3.3.0 - Shall we back ported it @garethbowen ?

**Comment by garethbowen** [comment]
@ngaruko As this only affects Chrome 72 it won't affect any of our users using the android app, which is the vast majority of users who submit Enketo forms. I'm happy leaving it in 3.4.0 at this point so we don't risk slowing down the 3.3.0 release.

**Comment by ngaruko** [comment]
LGTM
Tested on `gamma.dev` 3.4
![image](https://user-images.githubusercontent.com/6979995/53307810-12857f00-3901-11e9-8252-f92281a989de.png)
