### ISSUE TITLE
The accept_patient_reports transition clears sent tasks

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5390]
If `accept_patient_reports` has a form configuration with `silence_for`, when matching which tasks to be cleared, statuses are not taken into consideration. 
This can lead to tasks that are in not in a pending type state to be set to `cleared`.

**Comment by dianabarsan** [comment]
This [commit](https://github.com/medic/medic/commit/08cf7af8f5d76e18e4d318e7ad61af73901cb0d3) has pushed the changes of this issue to `3.4.x` , so moving this to `3.4.x` to be AT-ed.

**Comment by ngaruko** [comment]
Any clue on how to AT this on our end @dianabarsan ?

**Comment by dianabarsan** [comment]
For AT, you can use Standard config and you will just need to manipulate some dates.
- submit a new pregnancy
- this will create a schedule for this pregnancy - we're interested in a group that has multiple tasks of the same type (for example Group 2 or 3 from https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite#/reports/8fdd077d-3a6f-4efe-9d5c-da2c83f0a9ba - each of these groups has a followup message + a reminder, with due dates one week apart)
- change the dates on the 2 messages so the followup due date is yesterday and the reminder is a week from yesterday, and change the status of the followup so it's "sent" or "delivered" - we're simulating that the CHW has received the followup message
- submit a pregnancy visit report for the same patient

After `accept_patient_reports` transition has ran, open the delivery report and check that the reminder message had it's status changed to "cleared" while the followup message should still have the status you gave it.
