### ISSUE TITLE
Can't edit translation terms for new keys

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5405]
**Steps to reproduce**:
1. Log in to the admin console
2. Go to Languages > Application Text
3. Click Add Translation
4. Fill in the key but no terms
5. Submit
6. Edit the translation
7. Provide an English translation
8. Submit

**What should happen**:
The translation is updated.

**What actually happens**:
The translation is unchanged, no errors.

**Environment**:

- Instance: local
- Browser: Firefox
- Client platform: Linux
- App: admin
- Version: 3.5.0 (head of master)

**Comment by Jodge** [comment]
@garethbowen what exactly does "terms" mean here?

> 4. Fill in the key but no terms

**Comment by garethbowen** [comment]
The "key" is the unique identifier and it's what we use in the code to get the translation. The "terms" are the actual translations into each language, ie: the string that's actually shown in the UI.

**Comment by ngaruko** [comment]
LGTM @Jodge -

**Comment by garethbowen** [comment]
Already merged. Closing.
