### ISSUE TITLE
Errors when navigating away from edited forms

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5409]
We have a feature that shows a popup when navigating away from an edited form: https://github.com/medic/medic/issues/4013 . This is part of 3.3. This is not working as expected in latest code. 

**Steps to reproduce**:
- Open the app (user type is not relevant as long as you can open some sort of Enketo form). I will continue to describe steps as if logged in as admin and submitting contact creation forms, but the same happens when submitting reports. 
- Open a form to create a new contact (type is irrelevant)
- Edit one of the fields, so the app marks the form as `edited`
- Open browser console

**Bug 1:**
- Click on any of the tabs

**What should happen**:
- You should get a popup saying `This form is not finished....` and not navigate away from the form. Clicking on "YES" should perform the navigation, "NO" should keep you on the same page.

**What actually happens**:
 - Chrome and Firefox: Errors in the console 
```
Transition Rejection($id: 13 type: 6, message: The transition errored, detail: TypeError: Cannot read property 'preventDefault' of undefined)
TypeError: Cannot read property 'preventDefault' of undefined
```

This is most likely connected to a recent upgrade of ui-router in webapp, and a switch from `$stateChangeStart` broadcast to `$transitions.onStart`.

**Bug 2:**
- Click on a contact in the LHS list

**What should happen**:
- You should get a popup saying `This form is not finished....` and not navigate away from the form. Clicking on "YES" should perform the navigation, "NO" should keep you on the same page.

**What actually happens**:
- Chrome: You get the popup, but the page underneath also navigates to the contact you clicked, without interacting with the popup.
- Firefox: Same console errors as in Bug 1

**Environment**
 Instance: _localhost_
 Browser: _Firefox 65, Chrome 72, Chromium 71_
 Client platform: _Ubuntu 18_
 App: _webapp_
 Version: _3.4.x, 3.5.x_

**Comment by dianabarsan** [comment]
This also affects 3.4.

**Comment by dianabarsan** [comment]
Merged in to `master` and backported to `3.4.x`

**Comment by ngaruko** [comment]
looks to be working, functionally, but there is an error showing in the console. Is this anything to worry about @dianabarsan ?
![image](https://user-images.githubusercontent.com/6979995/53316882-5f337f00-392e-11e9-8bdd-123e376a586b.png)

**Comment by dianabarsan** [comment]
@bede That's just what our Modal without a Catch does, I wouldn't worry about it. 
Most of our modals don't Catch because we usually don't need to do things when the user says "no", only when they say "yes". For curiosity, you can check the console if you try to logout and then change your mind.
