### ISSUE TITLE
All reports are highlighted

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5417]
**Steps to reproduce**:
 - Login to a 3.3 instance
 - Navigate to reports page

**What should happen**:
 - Reports should appear in the LHS, with white background

**What actually happens**:
 - All reports on the LHS appear highlighted (orange background)

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/

- Instance: _gamma.dev.medicmobile.org, any 3.3.x install_
- Browser: _FF, Chrome, Chromium_
- Client platform: _Linux_
- App: _webapp_
- Version: _3.3.x_

**Comment by dianabarsan** [comment]
In addition to this, switching back to non-select mode does not clear the selection:

![image](https://user-images.githubusercontent.com/35681649/52945016-72b47800-3379-11e9-8c54-fe9f656a7bb6.png)

**Comment by dianabarsan** [comment]
Caused by changes made as part of https://github.com/medic/medic/issues/4013. 

The report highlighting only affects `3.3.x`, as `3.4.x` uses grandchild scopes for LiveList. 
Selection list not being cleared when switching `selectMode` affects `3.3.x`, `3.4.x` and `master`.

**Comment by garethbowen** [comment]
@dianabarsan I've merged this in to `3.3.x` but I'll leave it with you to forward port as necessary.

**Comment by newtewt** [comment]
Looks to be fixed. Nice!

**Comment by dianabarsan** [comment]
Forward ported to `3.4.x` and opened a PR to merge into `master`.

**Comment by garethbowen** [comment]
Merged into `master`.
