### ISSUE TITLE
Confirming navigation away from form doesn't work

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5423]
**Steps to reproduce**

1. login as admin 
2. go to Contacts
3. open a form to add a new contact and edit something 
4. open the Hamburger menu and click on About
5. when the navigation warning dialog pops up, click on "Yes" (You want to navigate to the about page).

**What should happen**
- You should be redirected to the About page

**What actually happens**
- You stay in the same "Contacts" zone, but your form closes. Depending on what type of form you opened, you're either redirected to the parent contact or to no contact (if you selected to add a new district). 

Same thing happens with reports, also clicking on tabs different than current "scope" (Contacts -> click on Reports etc) yields the same result. 

Version: 3.3 & 3.4.

3.5 has worse issues (https://github.com/medic/medic/issues/5409)

**Comment by dianabarsan** [comment]
I was wrong about the versions here. `3.4.x` includes the ui-router upgrade and has the same behavior as https://github.com/medic/medic/issues/5409 .

I think we can close one of them.

**Comment by garethbowen** [comment]
Ok great. Closing this one.
