### ISSUE TITLE
Selecting no language and submitting is showing translation keys instead of default app language

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5432]
A new user is prompted to select which language they want to use on log in. If the user selects nothing and presses submit they are dropped into the app and the translation keys are shown. Watching the caught exceptions  there is one for `./locale/undefined` and looking at the cookie it is set to undefined. 

**Steps to reproduce**:
Create a new user
Log in with that user
When prompted to select a language. Do not select a language and press submit. 

**What should happen**:
The user has the default app language selected or English if that is not selected. 

**What actually happens**:
The translation key are showing and there are errors in console. 

**Environment**:

- Instance: gamma.dev
- Browser:  Chrome
- Client platform: Linux
- App: webapp
- Version: 3.3.0

**Comment by garethbowen** [comment]
@peter-ochieng Have you had a chance to look at those requested changes? I'd like to get this in to AT as soon as possible. Thanks!

**Comment by peter-ochieng** [comment]
@garethbowen I've seen and made the changes and have also resubmitted for re-review.
Thanks

**Comment by garethbowen** [comment]
@peter-ochieng I think I've tracked the bug down in the API login controller. Can you please code review the above PR and let me know if it makes sense to you?

**Comment by garethbowen** [comment]
This is now ready for AT in the `5432-dont-set-locale-undefined` branch (off `master`). Let me know if it passes and I'll merge and backport.

**Comment by ngaruko** [comment]
LGTM on the branch

**Comment by garethbowen** [comment]
Merged into `master` and backported to `3.4.x`.

**Comment by newtewt** [comment]
Reopening this as it is showing it's head in master again.

**Comment by Jodge** [comment]
@garethbowen wanna follow up on this? seems like a regression as per our conversation with @newtewt 3.4 is fine

**Comment by garethbowen** [comment]
Yes I'm planning to get to this today, thanks!

**Comment by garethbowen** [comment]
It looks like this got reverted in this commit: https://github.com/medic/medic/commit/eeac7411c829ef96b99483a121e6f383f9fb4c17

Trying again...

**Comment by garethbowen** [comment]
@newtewt Ready for AT again.

**Comment by newtewt** [comment]
This is now working again.

**Comment by garethbowen** [comment]
Removing from 3.5.0 - the 3.5.0 work was just fixing a bad merge...
