### ISSUE TITLE
Images page not working in the admin console 

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5436]
_Brief description of bug encountered_.

**Steps to reproduce**:
 - _Log on as admin_
 - _Go to `/medic/_design/medic-admin/_rewrite#/images/icons`_
 - _or click on Images_

**What should happen**:
 - _the Images page should show_
![image](https://user-images.githubusercontent.com/6979995/53049312-a7e8d380-34fb-11e9-9853-56f34a3c3d7a.png)

**What actually happens**:
 - _Nothing happens in the UI_
 - _Observed errors in the console_
![image](https://user-images.githubusercontent.com/6979995/53049381-d070cd80-34fb-11e9-8de6-02af8eddb97b.png)

 - _Also observed errors in the console the `Images` element is not a hyperlink , ie no `href`_
Looks like this:
![image](https://user-images.githubusercontent.com/6979995/53049462-07df7a00-34fc-11e9-8e44-26c89f9bf16e.png)

Instead of this maybe:
![image](https://user-images.githubusercontent.com/6979995/53049531-35c4be80-34fc-11e9-8e45-112d92d2bae9.png)

**Environment**:

- Instance: _(gamma.dev.medicmobile.org, v3.3.x)_
- Browser: _(Firefox, Chrome)_
- Client platform: _(MacOS)_
- App: _(admin)_
- Version: _(3.3.x)_

Works well on `master` (3.5)

**Comment by garethbowen** [comment]
This was caused by a [bad backport](https://github.com/medic/medic/commit/1c03cf813abb0817d50ad1af7ed83425f3e2fd97) which changed the state name to one that doesn't exist in 3.3.0.

**Comment by garethbowen** [comment]
Merged to `3.3.x`. Not a problem in `3.4.x` or `master.

**Comment by ngaruko** [comment]
LGTM
