### ISSUE TITLE
Validate target ID uniqueness

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5439]
When creating Targets in the admin app you have to provide a unique ID but we don't have any validation to ensure the ID isn't a duplicate. This causes bugs [like this one](https://github.com/medic/medic/issues/5438).

Add validation when creating or updating Targets which stops users submitting duplicate IDs.

**Comment by garethbowen** [comment]
Ready for AT. The branch for testing is: `5439-target-uniqueness`

**Comment by ngaruko** [comment]
LGTM . Back to you @garethbowen 
![image](https://user-images.githubusercontent.com/6979995/55919530-6d253100-5c4a-11e9-9e6b-e6c69a50e369.png)

**Comment by garethbowen** [comment]
Merged.
