### ISSUE TITLE
Report page is blank after cancelling navigation confirm dialog

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5445]
Creating a new report. Editing something to mark it as changed. Then navigating away shows the are you sure dialog. The report behind is blanked out. Pressing no dismisses the dialog but the page is blank. 

**Steps to reproduce**:
Navigate to a person.
Click new action
New Pregnancy or any other report
Make some change to defaults to mark the report as dirty
Click away to trigger the are you sure you want to leave dialog
Click No on the dialog

**What should happen**:
The diag is dismissed and the report is shown where the user was. 

**What actually happens**:
The diag is dimissed and the RHS is blank. 

**Environment**:

- Instance: gamma.dev
- Browser: Chrome 
- Client platform: Linux
- App: webapp
- Version: 3.3.x

**Comment by garethbowen** [comment]
Merged into `3.3.x` to keep the release train running. @dianabarsan I'll leave it with you to forward port as necessary.

**Comment by dianabarsan** [comment]
For 3.4 (and 3.5) I've already written up a fix that covers this and others - can be seen here https://github.com/medic/medic/pull/5444 . I just wanna check it one more time before requesting a review. 
So no forward port necessary.

**Comment by newtewt** [comment]
Looks good!
