### ISSUE TITLE
Remove unused permissions

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5447]
We have dropped certain features like `export audit` and `export server logs` but we still have permissions hanging on the[ admin portal](https://gamma.dev.medicmobile.org/medic/_design/medic-admin/_rewrite#/authorization/permissions).

![image](https://user-images.githubusercontent.com/6979995/53143082-62133480-35fb-11e9-8ce8-5623eb7b8c76.png)

![image](https://user-images.githubusercontent.com/6979995/53143137-95ee5a00-35fb-11e9-9d1c-c8ef5a7b5fd4.png)

- Instance: _(gamma.dev.medicmobile.org)_
- Browser: _(Firefox, Chrome)_
- Client platform: _(Windows, MacOS, Linux)_
- App: _(webapp, admin)_
- Version: _(3.3)_

**Comment by Jodge** [comment]
`export server logs` 
Last seen: https://github.com/medic/medic/commit/a4238509b67dac5e3b38038fab7427788d3aa29f#diff-c096f29b328c61492abfe6a6f404fd35

`export audit`
Last seen:
https://github.com/medic/medic/commit/9ca61d4f6b325a51a237a77a442f98825add1548#diff-c096f29b328c61492abfe6a6f404fd35

@garethbowen `can_export_audit` and `can_export_server_logs` still reside in `config/standard/app_settings.json` do they go away or remain for posterity?

**Comment by garethbowen** [comment]
@Jodge Definitely remove them from standard too - good spotting!

**Comment by Jodge** [comment]
Ready for AT, the branch for testing is: `5447-unused-permissions`

**Comment by ngaruko** [comment]
LGTM _ U can go ahead and merge @Jodge
