### ISSUE TITLE
Sentinel due_tasks updates only one task/doc/run

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5453]
Sentinel's `due_tasks` script should update all `pending` tasks with a due date the current window.
Due to how the view results are "compacted" so a doc is not requested/hydrated twice and a check that validates if the scheduled_task should be `pending`, only one matching task/document is updated.

**Comment by garethbowen** [comment]
@dianabarsan I think this is a duplicate of #4498 - do you agree?

If so, can you close whichever one you think is less helpful?

**Comment by dianabarsan** [comment]
Oh yea, definitely a duplicate. Thanks!
