### ISSUE TITLE
Place select2 dropdown results are badly styled in the admin app

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5459]
**Steps to reproduce**:
 - Log in as admin
 - Navigate to the Admin App > Users > Add User
 - Search for a "Associated contact"

**What should happen**:
- The results should be easy to read.

**What actually happens**:
- The results are ugly and hard to read.

![screenshot from 2019-02-27 16-42-30](https://user-images.githubusercontent.com/2064938/53464337-b95b4e00-3aae-11e9-8832-8ff18abf1a6c.png)

**Environment**:

- Instance: localhost
- Browser: Firefox
- Client platform: Ubuntu
- App: admin
- Version: 3.5.0

**Comment by garethbowen** [comment]
This is how it looks now:

![screenshot from 2019-02-27 16-41-45](https://user-images.githubusercontent.com/2064938/53464503-5ae29f80-3aaf-11e9-9a33-6d6a9c64b10d.png)

**Comment by garethbowen** [comment]
Ready for AT in the `5459-fix-admin-contact-styling` branch.

**Comment by ngaruko** [comment]
LGTM. 
_**before**_
![image](https://user-images.githubusercontent.com/6979995/56658977-ad51ce00-66a4-11e9-803d-bc83346cfa11.png)

_**after**_
![image](https://user-images.githubusercontent.com/6979995/56659645-5b11ac80-66a6-11e9-93ae-2ff3706d314c.png)
