### ISSUE TITLE
Investigate Play Store replacements

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5479]
It looks as though Google's Play Store isn't going to allow medic-collect or medic-gateway to be listed any more, and if we start sending SMS from medic-android it will get blocked too. We are investigating various workarounds but in the medium-term it's likely we'll have to use a different app store so that projects can update the android app easily.

Investigate alternatives to the Play Store that could provision our apps.

**Comment by garethbowen** [comment]
@abbyad Should we bump this from 3.5.0?

**Comment by garethbowen** [comment]
Moving to 3.6.0.

**Comment by abbyad** [comment]
Sorry, I had text in this box but hadn't hit Comment...

Short term plans for Gateway and Collect are to host in GH Releases.
We should update build process to sign builds with the proper certificate, and uploaded to GH releases. We should aim to do this as soon as feasible, but not specifically tied to 3.5/6.

We don't have an immediate need for another store for medic-android.

**Comment by kennsippell** [comment]
@abbyad What is remaining for this issue to be tackled in 3.7?

**Comment by abbyad** [comment]
Yup, nice job with those. We can create a new issue in the future if new requirements force us to look for a replacement again. We can close this one now.
