### ISSUE TITLE
Countdown timer sound is not playing

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5482]
_Brief description of bug encountered_.

Launching the timer to on a form is showing the following error in console. 

```
Refused to load media from 'https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/static/audio/alert.mp3' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.
```
**Steps to reproduce**:
Using form in this [bug](https://github.com/medic/medic/issues/4279#issue-303660216)
Have Console open
Open in the web app

**What should happen**:
The alert mp3 shouldn't  be causing an error and should play I believe when timer completes. 

**What actually happens**:
Alert isn't played and error is shown

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/contacts/b9d543cf-1c35-468a-9ab7-f183bfae2e44/report/issue_4279_a 

**Environment**:

_Fill in as many of these as apply. It's especially useful if some environments work and some don't (ie works in Chrome but not in FF)._

- Instance: gamma.dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.4.x

**Comment by garethbowen** [comment]
Code review please @kennsippell

**Comment by garethbowen** [comment]
This has been merged into `master` so I've backported it to `3.4.x` ready for AT.

**Comment by newtewt** [comment]
@garethbowen  the error version of the message isn't showing for me anymnore. However, console is still showing an entry `urity Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.` The wording is definitely cut off in chrome.  Also, I believe the alert moved and is updated in master but not the 3.4.x branch not sure if we should correct that here or not.

**Comment by newtewt** [comment]
![image](https://user-images.githubusercontent.com/10531066/54130166-43c47b80-43e6-11e9-82b7-128318ea8c90.png)

**Comment by garethbowen** [comment]
As discussed on the call, it may be because of the previous service worker cache. Try wiping your cache completely and refreshing to see if that fixes it.

**Comment by newtewt** [comment]
After clearing cache the error about content security is gone. 

The path being moved is still around though. 
`GET https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/static/audio/alert.mp3 404`

**Comment by garethbowen** [comment]
Ok - that appears to be a completely separate issue with the URL of the beep being wrong. It only affects `3.4.x` as it was fixed on `master` when [the service worker was introduced](https://github.com/medic/medic/commit/99c99dec8f87cf07fa720ccc643cdc2885b06121#diff-7619459d34fbf7cfafa63a0bbaa4cb8a).

Should be fixed now!

**Comment by newtewt** [comment]
Awesomeeee, everything back to working.
