### ISSUE TITLE
Setting relevant="false()" is a hard error to troubleshoot in console

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5484]
When using the form below. The `relevant="false()" is causing an error in console that isn't very clear. It would be helpful if we could make this more clear. As a side it would also be nice if medic-conf could catch uploading forms with this property set and show an error. 

Error:
```
inbox.js:3 Error loading form Error: ["TypeError: Cannot read property 'scrollIntoView' of undefined"]
    at inbox.js:3
    at inbox.js:3
    at inbox.js:3
    at c.$digest (inbox.js:3)
    at inbox.js:3
    at Object.completeTask (inbox.js:3)
    at inbox.js:3

```
FORM: 
```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Test Issue 4279 A: timer with relevant</h:title>
    <model>
      <instance>
        <issue_4279_a delimiter="#" id="issue_4279_a" prefix="J1!issue_4279_a!" version="2018-03-08 17-42">
          <group>
            <timer/>
          </group>
          <meta>
            <instanceID/>
          </meta>
        </issue_4279_a>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/issue_4279_a/group/timer" readonly="true()" relevant="false()" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/issue_4279_a/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <group appearance="field-list" ref="/issue_4279_a/group">
      <label>Testing Timer</label>
      <input appearance="countdown-timer" ref="/issue_4279_a/group/timer">
        <label>Text for timer</label>
      </input>
    </group>
  </h:body>
</h:html> 
```

**Comment by garethbowen** [comment]
This may be the reason for some errors found in the wild: https://github.com/medic/medic/issues/5298#issuecomment-465213494

This may be something we have to fix in enketo-core.

**Comment by garethbowen** [comment]
I don't think we should make the error more clear because I don't think this should cause an error at all. I assume it's trying to scroll to a field but the field it's there because it's not relevant. I think the correct behaviour would be for enketo to not scroll if the field is `undefined` and potentially to scroll to the next field in the form (if there is one).

**Comment by wtekeu** [comment]
@newtewt you get the error message because enketo initializes the pages and try to scroll to the first question that is relevant .. in your case there is one page with only one question that is not relevant. If you still want to test whether enketo moves to the next question as suggested by @garethbowen create a second relevant question in your page. It seems to me it will.

**Comment by newtewt** [comment]
@wtekeu  this issue then only occurs if you have 1 question on the page and it is set relevant to false. It causes the form not to load at all. I am not sure whether that would ever be a valid use case. Seems like an edge case.  Adding a second question the form loads with no error.

**Comment by wtekeu** [comment]
@newtewt Should we close this?

**Comment by wtekeu** [comment]
As confirmed by @newtewt this is not an issue that should warrant further investigation.

**Comment by garethbowen** [comment]
I'm going to have a look at seeing if we can squelch the error and/or log something nicer as it's something we've seen in the wild and it's creating unnecessary feedback docs.

**Comment by garethbowen** [comment]
Here's the unminified stacktrace:

```
TypeError: Cannot read property 'scrollIntoView' of undefined
    at Object.focusOnFirstQuestion (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:100434)
    at Object.flipTo (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:100392)
    at Object.flipToFirst (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:100404)
    at Object.init (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:100201)
    at Form.init (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:97811)
    at :5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:198169
    at processQueue (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:55345)
    at :5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:55393
    at Scope.$digest (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:56512)
    at Scope.$apply (:5988/js/inbox.js?_sw-precache=d0c3a17592bd31a14110956d4b7cf5c0:56900)
```

And screenshot

![Screenshot from 2019-09-10 11-17-50](https://user-images.githubusercontent.com/2064938/64572729-ac53db80-d3bc-11e9-9149-dbd2e089381e.png)

**Comment by garethbowen** [comment]
I've raised an issue to improve this in enketo-core: https://github.com/enketo/enketo-core/issues/662

**Comment by garethbowen** [comment]
After the PR this is how it looks:

![Screenshot from 2019-09-10 13-21-40](https://user-images.githubusercontent.com/2064938/64576827-64d64b00-d3ce-11e9-8b09-4baac882d959.png)
![Screenshot from 2019-09-10 13-21-46](https://user-images.githubusercontent.com/2064938/64576828-64d64b00-d3ce-11e9-9015-9a7e22223a34.png)

**Comment by garethbowen** [comment]
Ready for AT in `5484-patch-enketo-to-show-useful-warning`

**Comment by newtewt** [comment]
Looks good to me. I can submit the form now and the warning is displayed in console.
