### ISSUE TITLE
Muso supervisors can't review mRDT reports while having a replication depth of 1

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5485]
## Some Background
Muso supervisors with a replication depth of 2 are forced to replication all families (clinics) and forms associated with those families. Many CHVs per supervisor * many familes per CHV yields an estimated 4000 home-visit forms per week for these supervisors. This causes performance problems. Performance of the app can be improved with purging, but replication for some users takes more than three days. To fix https://github.com/medic/medic-projects/issues/5781, Muso is reducing the replication depth of supervisors to 1.

Muso is conducting an mRDT Trial starting April 1st in which supervisors need to review patient forms. These forms would require a replication depth of 3 (impossible), so Muso leverages the `needs_signoff` flag on reports. 

## Requirement
The needs_signoff flag only works for reports which are one level deeper than the user's replication depth. With a replication depth of 1, Muso supervisors cannot review a report at depth 3. 

For the April 1st trial, Muso is setting a replication depth of 2 for the mRDT supervisor (one user only) and configuring purging with aggressively supervisor-specific rules. However, this won't scale well for the mRDT scaleup in August as all supervisors would be hindered by multi-day replication times with the replication depth of 2. 

Muso needs a solution which would allow a replication depth of 1 for a user which can also review reports at depth 3.

**Comment by SCdF** [comment]
@garethbowen any reason why we wouldn't want to change the meaning of `needs_signoff` to be a string not a boolean, that string being the identifier of the person who is supposed to view it?

**Comment by kennsippell** [comment]
@SCdF How would the form logic derive the value of the supervisor's contact id? If we're going to use the parent chain, I believe the best we could do would be to set it to the `district_hospital` -- the parent of the supervisor.

**Comment by garethbowen** [comment]
Right. We could set needs_signoff to a place UUID from the contact's hierarchy, then emit that ID from the view, and anyone who has access at that place or higher would be able to see the report. I think that'd work...

**Comment by SCdF** [comment]
@kennsippell yeah I presumed that we can use a UUID from the hierarchy of the CHW who writes the doc (as Gareth says, the contact). If you don't think that is going to work if you could draw a diagram of hierarchies that would be very helpful in visualising the situation.

Side note: we could actually, if we were feeling adventurous, allow for `needs_signoff` to be an array. This would potentially (though how would you know about the ids) allow us to expose docs over various different hierarchies.

**Comment by kennsippell** [comment]
Hierarchy Level | Use in the Muso Project
-- | --
District Hospital | Muso uses this to represent a Supervisor's catchment region
Persons that have District Hospital as parent | The supervisor
Health Clinic | Muso uses this to represent a CHV's catchment region
Persons that have Health Clinic as parent | The CHV
Clinic | This represent's a family of patients
Persons that have Clinic as parent | Patients

@SCdF Not sure if that is helpful?  I think it can work, I'm just saying whoever builds it may need to be mindful of this.

**Comment by SCdF** [comment]
@kennsippell right so to solve your problem if we change `needs_signoff` to a string or an array of strings you could set needs_signoff to `report.contact.parent.parent._id` to mean the supervisor, yeah?

The concern would be if the (hydrated) report couldn't come up with an identifier that fits into the current replication scheme, in which case we'd need to go back to the drawing board and work out what we really needed here.

**Comment by dianabarsan** [comment]
Ready for AT on `5485-expand-needs-signoff`.

**Comment by kennsippell** [comment]
I ATed this today. On Muso's configuration for an mRDT supervisor with replication depth of `1`, I'm seeing mRDT reports appear on `5485-expand-needs-signoff` but not on `master. Tried a few other scenarios and this looks good! Found one bug in 3.5 not related to this issue.
