### ISSUE TITLE
Minify all JavaScript files

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5489]
We use uglify to make our JS smaller but we don't apply it to all files. Make sure this is applied to all JS files we serve to improve download speed and reduce parsing time.

**Comment by garethbowen** [comment]
Results:

`build/ddocs/medic/_attachments/js/service-worker.js`: 11753kb to 4649kb
`api/src/public/login/script.js`: 1889kb to 1395kb

**Comment by garethbowen** [comment]
Unfortunately it looks like we weren't minifying anything... from the build:

```

Running "uglify:build" (uglify) task
>> Destination build/ddocs/medic/_attachments/js/service-worker.js not written because src files were empty.
>> Destination build/ddocs/medic-admin/_attachments/js/main.js not written because src files were empty.
>> Destination build/ddocs/medic-admin/_attachments/js/templates.js not written because src files were empty.
>> Destination api/build/public/login/script.js not written because src files were empty.
>> 2 files created 20.09 MB â†’ 2.97 MB
```

The files are being copied _after_ we attempt to minify them.

**Comment by garethbowen** [comment]
The log now:

```
Running "uglify:build" (uglify) task
>> 6 files created 32.41 MB â†’ 4.93 MB
```

Much better. I'm not sure how we can fail if the uglify isn't working in future.

**Comment by garethbowen** [comment]
Ready for AT in `5489-uglify-all-the-things`

AT: clear all caches, open the network tab of the dev tools, load the login page and log in to the app and make sure the `login/script.js`, `service-worker.js`, `login/styles.css`, and `inbox.js` are all uglified (eg: all code on one line).

**Comment by ngaruko** [comment]
LGTM..
![image](https://user-images.githubusercontent.com/6979995/55315867-c0201b00-54c9-11e9-89aa-b840685e50d1.png)

**Comment by garethbowen** [comment]
Merged into `master`.
