### ISSUE TITLE
Compress TTF font files

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5490]
Currently TTF font files aren't gzipped which makes them much larger than they need to be. Modify the api gzip solution to compress TTF files too.

**Comment by garethbowen** [comment]
Results for `fonts/NotoSans-Regular.ttf`: 406kb -> 217kb

**Comment by garethbowen** [comment]
Ready for AT in `5490-gzip-ttf`.

AT: Clear your cache, appcache, service-worker cache, etc. Bring up the network tab. Log in. Make sure the request for all ttf fonts has a `content-encoding: "gzip"` header and the size is roughly 2KB.

**Comment by ngaruko** [comment]
Hi @garethbowen . Are we expecting `2KB` or about `216KB`?

![image](https://user-images.githubusercontent.com/6979995/56717852-3e2cb600-6746-11e9-8d76-dd0bcb7513d4.png)

![image](https://user-images.githubusercontent.com/6979995/56719279-1a1ea400-6749-11e9-8851-ccf5b69693fe.png)


after
![image](https://user-images.githubusercontent.com/6979995/56720383-666ae380-674b-11e9-969a-477476d73315.png)

![image](https://user-images.githubusercontent.com/6979995/56723736-36730e80-6752-11e9-9ff7-71ee1c1bb05b.png)

**Comment by garethbowen** [comment]
Definitely the latter - merged!
