### ISSUE TITLE
The DDoc Version on the About page isn't working

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5498]
**Steps to reproduce**:
1. Log in as a restricted user
2. Make sure you're still online
3. Go to Hamburger > About

**What should happen**:
 - The "DDoc version" field should show the first part of the rev of the server ddoc

**What actually happens**:
 - It says "offline"

![Screenshot from 2019-03-13 16-37-51](https://user-images.githubusercontent.com/2064938/54252093-61444180-45ae-11e9-8acc-f77ed2784f88.png)

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/about

The network request to get the version returns an error:

```json
{ "rows": [ {"id":"\"_design/medic\"","error":"forbidden"} ] }
```

**Environment**:

- Instance: gamma.dev
- Browser: Chrome
- Client platform: Ubuntu
- App: webapp
- Version: 3.4.x

**Comment by ngaruko** [comment]
LGTM ... Ready to merge @garethbowen 
**Before**
![image](https://user-images.githubusercontent.com/6979995/55040800-f9522880-508e-11e9-837f-b11d15780b1d.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/55040931-85fce680-508f-11e9-98f9-63e0c0af7cf8.png)

**Comment by garethbowen** [comment]
Merged.
