### ISSUE TITLE
Reloading the app while offline shows sync status "required"

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5501]
**Steps to reproduce**:
1. Load the app
1. Fully sync so the hotdog menu says "all reports synced"
1. Go offline
1. Refresh the app
1. Open the hotdog menu

**What should happen**:
- No translation warnings in the console
- The sync status is "unknown"

**What actually happens**:
- A console warning is shown
- The sync status is "reports to sync"

Console log:

```
Translation for sync.status.undefined doesn't exist
```

![Screenshot from 2019-03-14 16-46-23](https://user-images.githubusercontent.com/2064938/54329933-bba9d480-4678-11e9-83e0-f6bb0298e59b.png)

**Environment**:

- Instance: localhost
- Browser: Chrome
- Client platform: Ubuntu
- App: webapp
- Version: 3.5.0 (head of master)

**Comment by garethbowen** [comment]
AT: Testing this depends on #5481 or #4898 being fixed, because currently there's basically always a feedback doc to submit, so instead of seeing "unknown" you'll see "error".

**Comment by garethbowen** [comment]
Ready for AT in `5501-rationalise-sync-events`

**Comment by ngaruko** [comment]
Can you look at the [conflicts](https://github.com/medic/medic/pull/5503/conflicts) on this branch @garethbowen ?https://github.com/medic/medic/pull/5503/conflicts

**Comment by garethbowen** [comment]
@ngaruko I've fixed the conflicts - once the build passes you should be good to go again.

**Comment by newtewt** [comment]
I'm seeing this work on the web currently but waiting on the fixes for working in the android-app so we can verify on phone .

**Comment by ngaruko** [comment]
LGTM -
![image](https://user-images.githubusercontent.com/6979995/57588888-98fc4500-756f-11e9-8dab-735008329718.png)
