### ISSUE TITLE
Creating / syncing meta db-s fails when db name is not "medic"

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5507]
When you deploy medic app and use a db name that is not `medic`, creation and replication of user meta dbs doesn't work, having all sorts of effects on the app.

For online users, which query the DB directly, loading reports fails and the console is riddled with replication failures. 
For offline users, loading reports works as the queryied DB exists locally, but replicating upstream will fail. 

The reason is that webapp builds the meta db name based on the main db name and adds a suffix: `<main-db-name>-user-<username>-meta`, while API hardcodes the meta db names to `medic-user-<username>-meta` both in `routing` and in the `user-db` service. 

Since we're intending to use meta db-s for more than storing read docs (telemetry, feedback, etc) we should make sure this data is uploaded correctly.

![image](https://user-images.githubusercontent.com/35681649/54440080-b1eca380-4742-11e9-946c-19cf716890b8.png)

**Comment by dianabarsan** [comment]
Ready for AT on `5507-db-name-is-not-medic`.

**Comment by ngaruko** [comment]
LGTM - There might be other areas where `medic` is hard coded in our products, but I guess we will be fixing those as we come across those.
