### ISSUE TITLE
Images on reports are being blocked. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5514]
Processing a MRDT form with image attached is not showing when viewing the report. Looking at the console the following error is shown. 

```
/medic/_design/medic/_rewrite/#/reports/a9cd35cd-3b25-4f3c-833f-48a33a5b8d15:1 Refused to load the image 'blob:https://gamma.dev.medicmobile.org/25a306b7-0592-458c-a6e8-ff1d23a00b50' because it violates the following Content Security Policy directive: "img-src 'self' data:".
```
**Steps to reproduce**:
Log in to gamma.dev
Navigate to reports.
Click Add report
Process an MRDT form

**What should happen**:
The report is displayed with the image of the mrdt test

**What actually happens**:
The form displays however the broken image icon displays and the above error is shown in console.

https://gamma.dev.medicmobile.org/medic/_design/medic/_rewrite/#/reports/a9cd35cd-3b25-4f3c-833f-48a33a5b8d15 

**Environment**:

- Instance: gamma.dev
- Browser: Chrome, mobile app
- Client platform: Linux
- App: webapp
- Version: 3.4.0-beta.1

**Comment by garethbowen** [comment]
Ready for AT in `5514-img-blob`. Instructions: Remember to clear service worker cache as it caches the old CSP headers.

**Comment by garethbowen** [comment]
Backported to `3.4.x` here: https://github.com/medic/medic/commit/9d0045cfdb4d3fea874c2eb33bf462d1faf93572

**Comment by newtewt** [comment]
All good on 3.4.x

**Comment by garethbowen** [comment]
Merged to `master`
