### ISSUE TITLE
Feedback modal doesn't close after successful submission

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5522]
**Steps to reproduce**:
1. Go to hamburger menu > Report Bug
2. Fill in any description
3. Submit

**What should happen**:
- The bug is submitted, the modal is closed, and a Snackbar is shown confirming the submission.

**What actually happens**:
- The modal stays open.

Nothing in the logs.
No indication of an error in the UI.

**Environment**:

- Instance: localhost
- Browser: Firefox
- Client platform: Ubuntu
- App: webapp
- Version: 3.5.0ish (master)

**Comment by garethbowen** [comment]
This was a regression caused by this line being removed in this commit: https://github.com/medic/medic/commit/f91bdea49bcabb988c3d1329cbf2792f897f42b0#diff-d43ea71e027c59879beb3bb530f132eaL54

**Comment by Jodge** [comment]
@garethbowen this a regression and a quick fix, do we need AT here?

**Comment by garethbowen** [comment]
Yeah I think so. It's a quick fix but I may have broken something else along the way...

The only issues that skip AT are technical ones that don't affect the product in any way, eg: testing, build tools, documentation, etc

**Comment by garethbowen** [comment]
Ready for AT in `5522-remember-to-close-the-modal`

**Comment by ngaruko** [comment]
Feedback is submitted but ...
a) still shows error in console
![image](https://user-images.githubusercontent.com/6979995/54915471-10dcc480-4f5c-11e9-9515-8f19e807120c.png)

b) add an empty json in the `export feedback` list
[image](https://user-images.githubusercontent.com/6979995/54915499-27831b80-4f5c-11e9-9242-c304fd900c0b.png)

**Comment by garethbowen** [comment]
@ngaruko The only way I managed to reproduce this was by deleting the "feedback.submitted" translation, in which case I also got this in the log: "Translation for feedback.submitted doesn't exist". Can you confirm you see this in your log too?

The workaround is to provide the translation but I'll also patch the code so it doesn't fail if there's no translation.

**Comment by garethbowen** [comment]
I've merged a fix and the build has passed. Can you have another look please?

**Comment by ngaruko** [comment]
LGTM @garethbowen (Fresh install)
**_Before_**
![image](https://user-images.githubusercontent.com/6979995/55529218-af0b2000-56fc-11e9-8993-f10f8349469e.png)
**_After_**

![image](https://user-images.githubusercontent.com/6979995/55529266-014c4100-56fd-11e9-89ff-32d2935d4bbf.png)

**Comment by garethbowen** [comment]
Merged into `master`.
