### ISSUE TITLE
Tooltip showing as `logo`

### ISSUE THREAD

**Issue by abbyad** [medic/medic#5531]
The logo for branding has a tooltip with just `logo`. Perhaps there is a way to set this that was missed. If so, we should document it.

![image](https://user-images.githubusercontent.com/789512/54859450-b20d1600-4ce3-11e9-8985-cc8eadaa4778.png)

**Steps to reproduce**:
- Hover over the logo in the top left corner of the app

**What should happen**:
- Should have some useful information (or nothing?), previously this used to be the version number. @amandacilek should would show the version number again, or something else?

**What actually happens**:
 - The tooltip is `logo`

**Environment**:

- Instance: gamma.dev
- Browser: Chrome 72
- Client platform: Windows
- App: webapp
- Version: 3.4.0-beta.2

**Comment by Jodge** [comment]
This is a `regression` by white labelling feature, we should revert it back to display the version number on tooltip hover

**Comment by Jodge** [comment]
Ready for AT on branch `5531-logo`

**Comment by amandacilek** [comment]
I'm not sure how common of a UI pattern it is, but I'm fine showing the version number again on hover.

The previous tooltip of "logo" sounds more like information that should be in the code as alt text for accessibility purposes. In the case of alt text, "logo" would be fine, or we could further customize it to say whatever partner it is e.g. "Living Goods logo".

**Comment by Jodge** [comment]
Actually previous it was `Title | version` e.g. `Medic Mobile | 3.5.0` so the change I have made has restored it back to that

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/55121615-30dcd580-5160-11e9-9c0b-67a3756e8b89.png)


Back to you @Jodge to merge!

**Comment by abbyad** [comment]
Nice! @ngaruko does it also work when the title is changed with the custom branding feature?

**Comment by Jodge** [comment]
@ngaruko could you also pull the latest code on this branch, I just realized when testing this change, the admin side specifically **Images - Branding** got broken, Ideally the test should confirm that you are able to change the title and the logo from the admin side as before

**Comment by garethbowen** [comment]
@ngaruko This is now ready for AT again.

**Comment by ngaruko** [comment]
It also works when the title and/or logo is changed with the custom branding feature @abbyad .
I guess that was the last fix @Jodge ?
![image](https://user-images.githubusercontent.com/6979995/55551339-0e862180-5737-11e9-8456-6bc430f495ed.png)

**Comment by Jodge** [comment]
@ngaruko yes that's right, Thanks!
