### ISSUE TITLE
Countdown timer does not respect custom timer value

### ISSUE THREAD

**Issue by abbyad** [medic/medic#5536]
The countdown timer is always using the default time of 60, even when set as shown in https://github.com/medic/medic/issues/1531#issuecomment-155388612

Here is a sample XLSForm and corresponding XForm: [timer.zip](https://github.com/medic/medic/files/3006010/timer.zip)

**Steps to reproduce**:
 - Create a form with a non-default timer (eg set to `9` seconds)
 - Open form and tap on timer

**What should happen**:
 - Timer should have a 9 countdown before completion

**What actually happens**:
 - Timer shows a 60s countdown, which is [the default](https://github.com/medic/medic/blob/e59da173289d8041798ef9310a99be8b73faef1f/webapp/src/js/enketo/widgets/countdown-widget.js#L31).

**Environment**:

- Instance: standard.dev, gamma.dev
- Browser: Chrome 72
- Client platform: Windows
- App: webapp
- Version: 2.18.0-beta.1 on standard.dev, and 3.2.1 on gamma.dev

**Comment by abbyad** [comment]
The countdown-timer works for some projects, and it turns out that the difference is in using a `note` field vs a `string` as the XLSForm type. 

The difference in the resulting XForm is that a `note` is readonly:
### `string`
```xml
      <bind nodeset="/timer/timer" type="string"/>
```
### `note`
```xml
      <bind nodeset="/timer/timer" readonly="true()" type="string"/>
```

Given that it is reasonable for a form builder to set this field as readonly manually in the XForm, or via XLSForm `note` field, we should be more tolerant here. That said, since there is a workaround I am lowering the priority to low and will document accordingly.

**Comment by abbyad** [comment]
Here are the forms working for posterity: [timer_as_string.zip](https://github.com/medic/medic/files/3008506/timer_as_string.zip)

### XLSForm

type | name | label | appearance | default
-- | -- | -- | -- | --
string | timer | Press timer to start | countdown-timer | 9

### XForm
```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>Timer Test</h:title>
    <model>
      <instance>
        <timer delimiter="#" id="timer" prefix="J1!timer!" version="2019-03-26 10-09">
          <timer>9</timer>
          <meta tag="hidden">
            <instanceID/>
          </meta>
        </timer>
      </instance>
      <instance id="contact-summary"/>
      <bind nodeset="/timer/timer" type="string"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/timer/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body class="pages">
    <input appearance="countdown-timer" ref="/timer/timer">
      <label>**Press timer to start**</label>
    </input>
  </h:body>
</h:html>
```

**Comment by garethbowen** [comment]
Ready for AT in `5536-countdown-timer-does-not-respect-custom-timer-value`

**Comment by garethbowen** [comment]
Using the xform above I tested the following values:

| Value | Timer duration |
|----|----|
| `<timer></timer>` | 60 seconds |
| `<timer/>` | 60 seconds |
| `<timer>a</timer>` | 60 seconds |
| `<timer>18</timer>` | 18 seconds |
| `<timer> 18 </timer>` | 18 seconds |
| `<timer>18a</timer>` | 18 seconds |
| `<timer>-18</timer>` | Beep sounded immediately |

60 seconds is the default timer duration. The only test that could be considered a fail is the last one where I think it'd be better to fall back to the default, however it's a stupid thing to do so I'm calling this a pass!

**Comment by garethbowen** [comment]
Merged and ready for release.
