### ISSUE TITLE
UHC metrics are incongruous between contacts and analytics tab due to month_start_date

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5544]
Muso has several UHC-specific targets which report metrics which overlap with the data on the UHC-enabled contacts tab. For example, they track "total number of home visits this month" and "% of families which have received >= 2 home visits this month" in the analytics tab.

The UHC data on the contacts tab reports on a monthly period from the 26th to the 25th (eg. Feb 26th to March 25th). This is controlled via a configurable "month_start_date" in app_settings.  At the same time, the same data is reported on the targets tab from the 1st to the last of the month (eg. Feb 1st to March 1st). This is not configurable.

The two metrics aren't aggregating the same information and appear broken.
* On March 1st, the contacts tab reports "10 home visits for Bob's family" and the analytics tab reports "0 home visits this month". 
* On March 26th, the contact's tab tab reports "0 home visits" for everybody and the analytics tab reports "350 home visits this month".

This is two tabs for the same user at the same time:
![Screenshot from 2019-03-27 09-20-59](https://user-images.githubusercontent.com/9014751/55093478-b0d84200-5071-11e9-899f-fa4e9f1a08c4.png)

**Comment by garethbowen** [comment]
@kennsippell Would this be solved by using `month_start_date` in all target calculations, or does it need to be different for different targets?

**Comment by kennsippell** [comment]
I would expect that they should always be the same periods. 
I'd expect a fairly straightforward change [here](https://github.com/medic/medic/blob/master/webapp/src/js/services/target-generator.js#L30).

**Comment by garethbowen** [comment]
Agreed. I might even call this a bug...

**Comment by kennsippell** [comment]
Dare you to change the label.

**Comment by dianabarsan** [comment]
Ready for AT on `5544-configurable-targets-intervals`

**Comment by wtekeu** [comment]
AT complete! 
LGTM.

Submitted a home visit and validated the count after changing my calendar (May 1, May 8, May 15, May 22 and May 29).

Merged and ready for release.
