### ISSUE TITLE
Documentation tooling

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5548]
It would be cool if we could add an automatic documentation generation tool into our development flow. This would help newcomers as well as (hopefully!) help us to write good code-local documentation.

It should understand some kind of JS-friendly comment-based documentation (like [JSDoc](http://usejsdoc.org/about-getting-started.html)), and use that to generate some readable documentation (e.g. html or markdown) that we can store somewhere and refer to.

Whether or not that storage is part of the each commit (e.g. it gets run as part of Grunt and updates a git-commitable location) or whether we run it manually occasionally (e.g. on every release) to be stored elsewhere is up for debate.

It would also be useful if it understood Angular's conventions, so it could intelligently link controllers to services and so on.

**Comment by garethbowen** [comment]
The above PR gets the framework going. Next steps:

- [ ] Improve the documentation to be more useful - currently it doesn't include much and it's all listed as "global".
- [ ] Consider using angular-jsdoc for angular documentation.
- [ ] Generate documentation for api, sentinel, and all the shared libs too.
- [ ] Consider splitting the documentation so there's one index for each of webapp, admin, api, sentinel, and all the shared-libs.
- [ ] Publish the documentation somewhere (maybe readthedocs.io or github ?).

**Comment by smbuthia** [comment]
Would it make sense to rename the modules in a way that makes it easy to identify where they are used? 
For example `admin.controllers` or `webapp.inboxControllers` as per the naming conventions described [here](https://github.com/mgechev/angularjs-style-guide#modules). This way, we can have one index with very distinct categories.

**Comment by garethbowen** [comment]
Yeah that makes sense. We're currently in the progress of working towards angular 8+ after which we should rework the naming system. Until then I think we should leave it as is so we don't end up renaming everything twice.

**Comment by garethbowen** [comment]
I think this is enough for now. We need to fill out the JSDocs, particularly on services, but the framework is in place.

**Comment by garethbowen** [comment]
Merged improvements. Closing this as the framework is done.
