### ISSUE TITLE
Allow users to specify date for UHC last visited

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5579]
Currently we always use a visit doc's `reported_date` field as the basis for the UHC last visited date. Sometimes the form allows the user to enter the date the visit occurred, in which case we should use that field instead.

Update the implementation to look for a specific field in the form to use as the last visited date, falling back to the `reported_date`.

Make sure the date format that the enketo date picker outputs is compatible with our last visited date implementation.

Original issue: https://github.com/medic/medic-projects/issues/6065

**Comment by garethbowen** [comment]
Ready for AT in `5579-allow-users-to-specify-date-for—uhclast-visited`. Make sure if a report has a `visited_date` field then that field is used for the "last visited date" in the contacts UI. If the report doesn't have a `visited_date` field then the `reported_date` should be used instead.

**Comment by dianabarsan** [comment]
This change looks good to me. This is the form I used to test: https://gist.github.com/dianabarsan/05cb7a0c0d19dda88117088d97a8040b
Maybe it can be some use to you @ngaruko .

**Comment by ngaruko** [comment]
Not sure if I am missing something @dianabarsan @wtekeu but when one selects `no` for `specify a home visit date`, the `last_visit` is empty in the db and in the UI.
Form
![image](https://user-images.githubusercontent.com/6979995/58388493-e9959700-8073-11e9-924f-d5812101d2fb.png)

db
![image](https://user-images.githubusercontent.com/6979995/58388503-fca86700-8073-11e9-8994-e5c0aa1693f3.png)

UI
![image](https://user-images.githubusercontent.com/6979995/58388510-0fbb3700-8074-11e9-86ef-6b01850a1d6b.png)

**Comment by dianabarsan** [comment]
@ngaruko The issue was just about being able to specify `visited_date` for a home visit. The form (I adapted) is just a means for AT. 
This change should be reflected on the LHS families list - if you specify a `visited_date`, that is the date that the LHS list should use, instead of the `reported_date` of the report.

**Comment by ngaruko** [comment]
LGTM
Before
![image](https://user-images.githubusercontent.com/6979995/58450123-af0a2800-8161-11e9-877e-52d1118efa46.png)


after
![image](https://user-images.githubusercontent.com/6979995/58450132-bd584400-8161-11e9-8dbd-560d2f9b5451.png)

**Comment by garethbowen** [comment]
Merged
