### ISSUE TITLE
Record the date when verifying a report

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5580]
Record when a report is marked as verified so it can be compared to the reported date for analytics purposes.

Requested in https://github.com/medic/medic-projects/issues/6066

**Comment by kennsippell** [comment]
When supervisors are reviewing an mRDT result, they click "Has Errors" or "Verify" - currently, the app allows them to change from one state to the other whenever they want. This is proving problematic for some of Muso's data analytics.

Muso has requested "We don't want the Supervisor to be able to change her verification answer ("error" or "correct") after she submits it. Instead, we would like to have a prompted message that states whether the Supervisor is sure or not about submitting the answer after submitting the answer. "

https://medic.slack.com/archives/C09292U2U/p1555659362002500

**Comment by kennsippell** [comment]
We have promised this to muso in 3.5 and it should not be punted.

**Comment by garethbowen** [comment]
Ready for AT in `6066-verfied-date`

**Comment by ngaruko** [comment]
The PR for this has [merging issue](https://github.com/medic/medic/pull/5575) @garethbowen for changes requested by @dianabarsan .

**Comment by garethbowen** [comment]
@ngaruko Good point - I've dismissed that old review so now it's good to go.

**Comment by ngaruko** [comment]
This branch has conflicts @kennsippell . Did you want to have a look and resolve those?

**Comment by dianabarsan** [comment]
Ready for AT on `6066-verfied-date`.

**Comment by ngaruko** [comment]
Looks like report can be `verified` even if the `can_verify_reports` permission is disabled. Did you want to have a second look at the code @kennsippell ?

**Comment by ngaruko** [comment]
LGTM - Closing this!
