### ISSUE TITLE
Allow external report contributions without a phone number

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5589]
Currently, if you want to POST new reports to Medic via the `/api/v2/records` API, you need to provide a phone number in the `from` field. This is used to link the report to contact later, and this functionality is important.

However, we should allow this linking without having to provide a phone number. Other things we could provide would be a contact_id in UUID form, or a contact's shortcode.

**Comment by SCdF** [comment]
This expanded a little bit more to generally be a cleanup of this area of code.

Documentation is here: https://github.com/medic/medic-docs/pull/106
Code PR is here: https://github.com/medic/medic/pull/5687

(for when it's ready for) AT:
 - You don't need to provide a phone number in the `from` field when submitting JSON forms via the records endpoint
 - Sending in SMS via this endpoint shouldn't be affected and should work as documented (ie I didn't break anything)

**Comment by garethbowen** [comment]
@newtewt This is "Done" - can the issue be closed now?

**Comment by newtewt** [comment]
Yeah that's my bad. I assumed that moving to done would close.
