### ISSUE TITLE
Update the CheckDate service to store the delta in telemetry

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5590]
When the app starts we run the CheckDate service to query the server date and compare with the date on the phone. This is useful because quite often phone dates are incorrect which means all the reports generated from that phone are inaccurate.

As well as showing a notice to the user when the date is bad it would be useful if project administrators could see which users are out of date.

Modify the CheckDate service to store the date diff in the Telemetry service.

**Comment by garethbowen** [comment]
Ready for AT in `5590-record-date-offset`

**Comment by garethbowen** [comment]
Because this is ready before 3.7.0 is in RT I going to move it to 3.7.0 to get it out the door.

**Comment by ngaruko** [comment]
LGTM
Tested by changing the date on the local server and logging in on a mobile device.
![image](https://user-images.githubusercontent.com/6979995/63761027-89cdb700-c914-11e9-8b3d-6e700229b8ed.png)

**Comment by garethbowen** [comment]
@ngaruko That's the existing functionality. Please check that the telemetry also contains the delta between the device date and the actual date.

**Comment by ngaruko** [comment]
Thanks @garethbowen . 
![image](https://user-images.githubusercontent.com/6979995/63815123-80c9fd80-c987-11e9-8039-eb7c4b5bf832.png)

**Comment by garethbowen** [comment]
@ngaruko I think that's ~1 day in millis. Is that how much you changed your local time?

**Comment by ngaruko** [comment]
@garethbowen  Yes, that was with the client 1 day behind server time. Setting clients time ahead of server time yields a negative delta...like so:
![image](https://user-images.githubusercontent.com/6979995/63821189-24270c80-c9a0-11e9-98bf-1684755cadf8.png)
