### ISSUE TITLE
Fix UHC styling when using both UHC and muting at the same time

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5595]
There is a bug/oversight in our UI styling when using both UHC and muting features at the same time. 

**What it currently looks like:** 
When a contact is muted and is displaying a grey icon in the main contacts list, the UHC date last visited and visits per month text is still styled red. This is confusing as it sends conflicting signals to the user. The red says “look at me, I’m important”, while the grey icon and muted status is meant to say “don’t worry about me, I’m not as important”.

**What it should look like:**
- If a contact is muted, the date last visited text should always be colored black, even if over 30 days.
- If a contact is muted, the number of visits per month (right side) is always grey, no matter if the visit count is 0, 1, 2, or 2+.
- If a contact is muted, the number of visits per month (right side) does not have a warning sign icon associated with it, no matter if the visit count is 0, 1, 2, or 2+.

**Mockups**
On the left is the current problematic styling. On the right is the desired styling.

![Screen Shot 2019-04-19 at 9 12 45 AM](https://user-images.githubusercontent.com/26235957/56432724-55b9f980-6283-11e9-9761-e359d5816417.png)

IMPORTANT: Another option could be to remove all UHC information from muted contacts entirely (don't display the date last visited or visits this month at all for those who are muted). But this should only be done if we are also able to accomplish #5596. If the muted contacts remain intermingled amongst active contacts then I think it makes sense to keep the UHC information, as it explains the sorting method.

**Comment by dianabarsan** [comment]
Ready for AT on `5595-muted-visits`

**Comment by wtekeu** [comment]
AT complete!
LGTM

Before:
<img width="648" alt="Screen Shot 2019-05-16 at 12 07 48 PM" src="https://user-images.githubusercontent.com/1445164/57869619-6a7ea400-77d3-11e9-97c6-701fb641fe85.png">

After:
<img width="595" alt="Screen Shot 2019-05-16 at 12 06 58 PM" src="https://user-images.githubusercontent.com/1445164/57869626-710d1b80-77d3-11e9-8799-dc27b8e8f4da.png">

Merged and ready for release.
