### ISSUE TITLE
Sort muted contacts to the bottom of the contacts list

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5596]
Right now muted contacts remain on the main contacts list, intermingled amongst active contacts, the only difference being that their icons are styled grey.

Our initial proposal for muting was that we would like to collect all of the muted contacts in a separate folder that lives at the bottom of the list. However this posed some technical challenges and we dropped it from the muting MVP.

@dianabarsan  said theoretically we could re-sort the contacts, but this would require updating the form that lists the people, and all phones would have to re-index their data.

An alternative could be sorting muted contacts to the bottom of the list ONLY when the list is sorted by “date last visited”. In UHC mode the default sorting is configurable by project, and any UHC user can go in at any time and toggle the sorting back and forth between “by date last visited” and “alphabetically”. But if _most_ UHC projects set their default sort to date last visited (Muso does), and if _most_ users typically leave it on the default sort, this solution could help most users in most cases.

Would be nice if devs could explore the potential solution described above (which would only help UHC projects) and/or any other ways to sort the muted contacts to the bottom of the list, which might potentially work across all projects.

**Comment by dianabarsan** [comment]
Ready for AT on `5596-muted-to-the-bottom`.
Post AT, please do not merge. A shared library needs to be published and dependencies bumped on the branch.

**Comment by newtewt** [comment]
@amandacilek should this include the people view on the right hand side?

**Comment by amandacilek** [comment]
> @amandacilek should this include the people view on the right hand side?

Hm, I thought we had another ticket to get rid of the contact list on the right hand side because it was redundant information... #5092. Are we talking about the same thing?

If there _is_ still a full contacts list on the RHS, yeah ideally that would match the rules on the LHS, and muted contacts there would sort to the bottom too I guess.

**Comment by garethbowen** [comment]
@newtewt I think this is ready for AT again.

**Comment by newtewt** [comment]
Tested this and merged the PR yesterday. Contacts are being sorted to the bottom on the LHS and RHS
