### ISSUE TITLE
Logging in as admin on mobile app you're unable to leave the admin console

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5599]
Since we've changed that admins are directed to the admin console when they log in. If they want to view the application they have to click the button across the top. If they log in on the android app the button isn't shown and they are stuck in the admin console.

**Steps to reproduce**:
Launch the android app
Point to an instance you have an admin account for
Log in as admin

**What should happen**:
The button to return to the application should be available to the user

**What actually happens**:
The button is hidden and you cannot leave the admin console

**Environment**:
- Instance: any instance running 3.5
- Browser: android app
- Client platform: Android
- App: webapp
- Version: 3.5

I've attached a video to see the issue.

[video.zip](https://github.com/medic/medic/files/3106816/video.zip)

**Comment by Jodge** [comment]
Ready for `AT` on branch `5599-admin-nav`

**Comment by newtewt** [comment]
Seeing the hamburger menu and the options to select application now.
