### ISSUE TITLE
Support Node 12

### ISSUE THREAD

**Issue by srsudar** [medic/medic#5607]
(Originally posted on #4826)

When following the README, I was unable to execute several of the `npm` commands. They were failing with various errors. One was related to v8, and something lacking the method `IsNearDeath`. (I didn't save the stack traces, sorry.)

Failing state:
```
$ node --version
v12.0.0
$ npm --version
6.9.0
```

I was able to work around this with `nvm use 11`.

```
$ nvm use 11
Now using node v11.14.0 (npm v6.7.0)
```

The commands now succeed.

**Environment**:

Ubuntu bionic.

**Comment by garethbowen** [comment]
A snippet from my log...

```
In file included from ../src/binding.cpp:1:0:
../../nan/nan.h: In instantiation of ‘void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]’:
../../nan/nan.h:2394:20:   required from ‘void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]’
../src/binding.cpp:351:42:   required from here
../../nan/nan.h:2378:3: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^~~~
In file included from /home/gareth/.node-gyp/12.3.1/include/node/v8-internal.h:14:0,
                 from /home/gareth/.node-gyp/12.3.1/include/node/v8.h:25,
                 from /home/gareth/.node-gyp/12.3.1/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/gareth/.node-gyp/12.3.1/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/gareth/.node-gyp/12.3.1/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
binding.target.mk:127: recipe for target 'Release/obj.target/binding/src/binding.o' failed

```

**Comment by garethbowen** [comment]
This is blocked on a PouchDB release: https://github.com/pouchdb/pouchdb/pull/7747

**Comment by garethbowen** [comment]
This first two issues I hit were fixed by upgrading:

- bundlesize@0.17.2
- node-sass@4.12.0

**Comment by garethbowen** [comment]
The pouchdb blocker might be resolved by this PR: https://github.com/medic/medic/pull/5684

**Comment by garethbowen** [comment]
Ready for AT in `5607-node-12-and-bump-dependencies`

This is difficult to fully AT because bugs could be hiding anywhere in the product. Do a simple smoke test of webapp, api, and sentinel to make sure there aren't any obvious issues. Anything missed should be picked up in release testing.

**Comment by ngaruko** [comment]
LGTM at the moment. Master fails with errors similar to the above: ```/Users/bede/.node-gyp/12.7.0/include/node/v8config.h:326:29: note: expanded from
      macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))```
but branch passes.
Will monitor unusual behaviors during release testing !

**Comment by ngaruko** [comment]
@garethbowen  - Reopening to get conflicts resolved on the [branch](https://github.com/medic/medic/pull/5751) before we are able to merge...

**Comment by garethbowen** [comment]
Merged.
