### ISSUE TITLE
Add python 2.7 to list of required software for developer environment

### ISSUE THREAD

**Issue by srsudar** [medic/medic#5608]
(Originally posted on #4826)

When following the README, `npm install` and `npm ci` failed when trying to build `gyp` or `leveldb`. My apologies but I don't remember exactly which.... And again I didn't capture a stack trace.

It turns out this was because my `python` command was python 3. It was a syntax error, and after some googling eventually an issue on the `gyp` or related project said I needed python 2.7. I was able to work around this by:

```
$ conda create --name py2 python=2.7
$ conda activate py2
$ python --version
Python 2.7.16 :: Anaconda, Inc.
```

At that point `npm install` and `npm ci` succeed.

**Environment**:

Ubuntu bionic.

**Comment by garethbowen** [comment]
Merged.
