### ISSUE TITLE
Does docker-compose work on Mac?

### ISSUE THREAD

**Issue by srsudar** [medic/medic#5611]
(Originally posted on #4826)

After installing `docker` and [following the instructions here](https://github.com/medic/medic-docs/blob/master/installation/public-docker-image-setup.md#use-docker-compose), I tried to run `docker-compose` with my yml file. It appeared to succeed, but there was nothing listening on `:5988` or `:5989`.

Should `docker-compose` work on Mac? Is there anything else I need to do beyond running the command? I was able to follow those steps on Ubuntu and GCP successfully.

**Environment**:

MacOS 10.14.4.

```
$ docker --version
Docker version 18.09.2, build 6247962
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad01
```

**Comment by Hareet** [comment]
Workarounds were provided in Slack, closing issue with a link to the latest docs.

This provides the clearest instructions to setting up the latest versions of the entire stack on OSX:
[Docker-Compose CHT Setup OSX](https://github.com/medic/medic-docs/blob/cht-docker-updates/installation/public-docker-image-setup.md)

Please let me know if there are any issues regarding the above documentation.
