### ISSUE TITLE
Changing user profile language prevents user from changing back to original language

### ISSUE THREAD

**Issue by smbuthia** [medic/medic#5616]
**Steps to reproduce**:
1. Log in as national or district admin
1. Go to user settings > Edit user profile > Language
1. Select a different language from what has already been set i.e. change from English to Swahili
1. Navigate away from user settings
1. Go to user settings > Edit user profile > Language
1. Select the language that had originally been set and apply i.e. change from Swahili to English

**What should happen**:
 - The language should change back to English from Swahili

**What actually happens**:
 - The language doesn't change back to English but can change to other languages other than the original language.

**Environment**:

- Instance: villagehealthworks-burundi.app.medicmobile.org
- Browser: Chrome
- App: webapp
- Version: 3.4.0

**Comment by kitsao** [comment]
I have also noted that the default language set by the in-built admin will always be the selected default (`<option label="English" value="en" selected="selected">English</option>`) by other users even if they switch to a different language. See sreenshot.
![image](https://user-images.githubusercontent.com/3928714/56895274-4f9cf780-6a91-11e9-92e3-1e42c824f00f.png)

I bootstrapped a clean 3.4.0 and saw an additional option on the select list

```
<option label="TODO: please ask admin to set this in settings UI" value="ny">TODO: please ask admin to set this in settings UI</option>
```

 when logged in as `restricted to their place` user. Not sure whether or not that means the language setting is to be done by the admin only and apply across the app?

**Comment by derickl** [comment]
Are there any errors on the browser console? @smbuthia @kitsao

**Comment by smbuthia** [comment]
I couldn't find any related errors on the browser console @derickl

**Comment by kitsao** [comment]
None @derickl

**Comment by garethbowen** [comment]
Ready for AT in `5616-changing-user-profile-language`.

**Comment by newtewt** [comment]
@wtekeu  I see the language is changing now when you select a new one. However, when you return to the edit page to select a new profile it shows the previous language.  

Go to user settings > Edit user profile > Language
Select a different language from what has already been set i.e. change from English to Swahili
Navigate away from user settings
Go to user settings > Edit user profile > Language
The previous selected language is displayed however it is not the current language selected.

**Comment by wtekeu** [comment]
@newtewt I was not able to reproduce it: https://testuyter.s3.amazonaws.com/Edit+user+profile+Recording.mov

Can you test it one more time?

**Comment by newtewt** [comment]
@wtekeu testing again and I see it working as expected.
