### ISSUE TITLE
JavaScript errors and crash stacks not logged to the console

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5622]
**Describe the bug**
Not all JavaScript errors and crash stacks are reported to the console.

**To Reproduce**
1. Open `webapp/webapp/src/js/controllers/inbox.js` in an editor and delete `Auth` from the ngInjection list (line 24).
1. Rebuild app
1. Login to the webapp

**Observed behavior**
The console has no errors.

**Expected behavior**
This is a basic scripting error in which we are using an undefined variable. The app fails to load (expected) but there should be an error in the console explaining why.

I think this bug is important and labelled it Priority 1 because these console errors are often our only way to investigate/understand live-site issues on the client.

**Comment by garethbowen** [comment]
This is something to do with the `$exceptionHandler` service - if I comment out the `require('./exception-handler');` line from `webapp/src/js/services/index.js` then the errors show up as per usual.

**Comment by garethbowen** [comment]
As far as I can tell this bug only affects errors that are thrown before angular starts up which makes it hard to AT without hacking the code a little.

When I hack the code it behaves as expected with both errors of configuration and errors in code being logged exactly once.

AT passed.
