### ISSUE TITLE
Uncaught Error in production v3.4 - Could not resolve 'undefined' from state '..'

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5627]
Based on the feedback documents for `moh_kenya_siaya` (running stable v3.4).

In the week of Apr 22 - Apr 28, there were 204 occurrences of this error pattern. These states seem to be `ui-sref`s from our header.

Top of stack  | Occurrences
-- | --
Uncaught Error: Could not resolve 'undefined' from state 'home' | 84
Uncaught Error: Could not resolve 'undefined' from state 'error' | 75
Uncaught Error: Could not resolve 'undefined' from state 'about' | 45

We should understand this error and either a) fix it if something is broken or b) silence it if it isn't a problem. If it is not actionable, then we need to talk about how we can make this data more actionable.

**Comment by garethbowen** [comment]
This has been improved (and hopefully fixed) in #5298
