### ISSUE TITLE
Uncaught Error in production v3.4 - Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5628]
Muso had 70 instances of this feedback document for April 29 - May 2.
`Cannot read property 'body' of undefined`

We should understand this error and either a) fix it if something is broken or b) silence it if it isn't a problem.  If it is not actionable, then we need to talk about how we can make this data more actionable.

**Comment by SCdF** [comment]
It's not clear how this is happening. The only reference to a body property in web code (any js in the webapp or shared-lib directory) that I could find is against `document`, i.e., `document.body`.  I'm not aware of any reason `document` wouldn't exist.

**Comment by garethbowen** [comment]
It's possible it's a bug in their configuration.

I think the next step here is to get a reference to a feedback doc that's failing with this - it _should_ have more information (like an uglified stack) to help us work out what's going on.

**Comment by kennsippell** [comment]
There were no occurrences of this bug in the muso-mali.app.medicmobile.org `medic-users-meta` database which contains all feedback docs from Muso's time running 3.5 and 3.6.
