### ISSUE TITLE
following README: misleading medic-conf command?

### ISSUE THREAD

**Issue by srsudar** [medic/medic#5630]
A line in the README about a `medic-conf` suggests:

```
Import the config: medic-conf --url http://username:password@localhost:5984
```

That fails for me, asking if I have the correct port. When running the API, a log statement suggests it is listening instead on `:5988`. Changing the port allowed the `medic-conf` command to succeed. Should that be the suggested port instead?

**Comment by kennsippell** [comment]
Hey @srsudar. Quick heads up that we just published medic-conf version 2.0.x which has some breaking changes affecting standard. I've got a PR out (#5508) to update standard in `master` but you might consider using the latest medic-conf@1.x build until I get that merged.
