### ISSUE TITLE
Move more scope properties to store and controller

### ISSUE THREAD

**Issue by rmhowe** [medic/medic#5635]
As part of the ongoing changes to get ready to [move to Angular 7](https://github.com/medic/medic/issues/4750), this issue is for moving various scope properties into the redux store and onto relevant controllers.

**AT:** Nearly every part of the app has been touched in at least some small way (excluding the admin app), sorry ☹️ This is effectively a refactor with no new features added. Specific big things that have been touched and may have broken:
- The action bar (LHS and RHS)
- Filters when listing contacts/reports/analytics, including the list of facilities
- The page title
- Unread count indicator in the top bar for new messages/reports/contacts
- App details on the About page

**PR:** https://github.com/medic/medic/pull/5792

**Comment by garethbowen** [comment]
Moving this to 3.6.0 as it's not required for 3.5.0

**Comment by ngaruko** [comment]
Hi @rmhowe . I am looking at this and seeing a few areas where the app behaves differently from `master` :

1 . `Report submitted` message not going away after `submit` button:
![image](https://user-images.githubusercontent.com/6979995/64290301-fe11f580-cfb9-11e9-9f71-f04bae7d1e89.png)

2. Slow loading
![image](https://user-images.githubusercontent.com/6979995/64290606-81334b80-cfba-11e9-9c14-db1ea0c8491f.png)

3. `None of the buttons work on `Update Password Modal` - no error in console
![image](https://user-images.githubusercontent.com/6979995/64290808-ebe48700-cfba-11e9-9bb2-bf3c9b5cd27a.png)

4. `Add new person`  combo box not working (not able to select):
![image](https://user-images.githubusercontent.com/6979995/64292665-fc96fc00-cfbe-11e9-9b7f-a06e7dafa47a.png)
With following console errors (in Firefox)
![image](https://user-images.githubusercontent.com/6979995/64292769-3962f300-cfbf-11e9-8034-90925090ba63.png)

**Comment by rmhowe** [comment]
@ngaruko thanks for finding those!

1. This is part of the admin app (which this code doesn't touch) and appears to also happen on `master` so I don't believe is a problem with this PR.
2. This is interesting, I've made some small changes which may help but I can't see much of a difference on my local. Are you able to do some rough benchmarking to quantify the difference on yours?
3. Fixed.
4. Fixed.

**Comment by ngaruko** [comment]
Thanks @rmhowe . I will re-AT 3 and 4, raise a separate issue on 1 if it still shows on `master` and leave 2 for performance testing during RT.

**Comment by ngaruko** [comment]
AT on `5635-reduxify-more-properties`. 
Just one more thing: All errors (no on that `edit user` are represented by one error message under `password` (second textfield). See screenshots
Master: ![image](https://user-images.githubusercontent.com/6979995/65084866-b4d19500-da00-11e9-932d-cf14e00ba38d.png) || 
![image](https://user-images.githubusercontent.com/6979995/65085413-25c57c80-da02-11e9-8847-bb841e4e0bd9.png)

Branch: 
![image](https://user-images.githubusercontent.com/6979995/65085065-49d48e00-da01-11e9-821c-0c3c0f711a89.png) || 
![image](https://user-images.githubusercontent.com/6979995/65085124-6244a880-da01-11e9-9970-c56f1304982a.png)
 
![image](https://user-images.githubusercontent.com/6979995/65085174-81dbd100-da01-11e9-9376-afe11416cc8d.png)

Also, there are still conflicts on the branch.... Back to you @rmhowe

**Comment by rmhowe** [comment]
@ngaruko thanks again for finding those, fixed the update password modal and all merge conflicts. A couple of e2e test are failing on travis only on a specific version of node so I'm not sure what's going on there but will look into it, I suspect they're just flaky tests though.

**Comment by ngaruko** [comment]
Hi @rmhowe > seems like the `update password` modal still does not handle errors properly. 
![image](https://user-images.githubusercontent.com/6979995/65191957-b0bd7a00-dac9-11e9-9ed9-f10a7a1bfd93.png)

Plus the `guided tour ` is also broken. No control buttons (`previous`, `next`, `end tour`).

**Comment by rmhowe** [comment]
@ngaruko that guided tour bug is also happening on `master` for me, not sure if that was a regression introduced previously? I've had a look into it but really not sure what's causing it. Also this is what the update password modal looks like for me on the PR branch
<img width="609" alt="updatepassword" src="https://user-images.githubusercontent.com/9385231/65257554-4d4b4080-daf9-11e9-9be5-b81d25574514.png">

**Comment by ngaruko** [comment]
Thanks @rmhowe 
True.The guide tour seems to be broken on `master`. Will raise a separate issue for this. Closing this one and will keep an eye in it during our RT, just in case I missed something here @newtewt
