### ISSUE TITLE
Update eslint to use ecmaVersion: 2017 to allow async/await pattern

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5647]
Should be able to do this for tests, api, scripts, and sentinel code.

**Comment by SCdF** [comment]
According to https://node.green and our minimum version as 8.6.x, we should also block the use of `SharedArrayBuffer` and 
`Atomics`

**Comment by garethbowen** [comment]
I think there's a way to have eslint use the `engines` property in `package.json` which would be ideal as it would keep updating as we bump our minimum node version.

**Comment by kennsippell** [comment]
[Api](https://github.com/medic/medic/blob/master/api/package.json#L11) and [Sentinel](https://github.com/medic/medic/blob/master/sentinel/package.json#L7) both support node 8.11.  Node 8.10 fully supports ES2017. You can see support for [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#Browser_compatibility) and [Atomics](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics#Browser_compatibility). So it should just be safe to run on ES2017 in eslint without further complications.

**Comment by kennsippell** [comment]
This is an eslint-only config change, so nothing to AT here.
