### ISSUE TITLE
Timer widget beeps even after cancelling the form

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5654]
**Describe the bug**
Timer widget beeps even after cancelling the form

**To Reproduce**
1. Start a new form with a countdown timer widget
2. Start the countdown
3. Click cancel and accept that you'll lose any changes
4. Wait for a minute (default timer duration)
5. You'll hear a beep!

**Expected behavior**
There should be no beep if the form is cancelled.

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Ubuntu
- App: webapp
- Version: 3.5.0 (master)

**Comment by garethbowen** [comment]
AT instructions: Also check submitting the form before the beep, or navigating on to another page, or any other way that you would expect the beep not to play any more.

**Comment by wtekeu** [comment]
AT passed. Tested the following cases:
1) cancel form
2) moved to a different page
3) submit page

Merged and ready for release.
