### ISSUE TITLE
The conditional_alerts transition doesn't include the current report in the list of relevant reports

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5668]
**Describe the bug**
The conditional_alerts transition can be used to send an alert when other reports have been received with the same form and clinic, however it doesn't always include the report that triggered the transition as one of the reports.

**To Reproduce**
1. Configure the transition (example config below)
2. Go to the Admin app > Message Test
3. Submit a message `P <patient_id> 5` from a valid phone number
4. View the report in the app and verify that the alert message is generated as expected
5. Submit a message `P <patient_id> 7`
6. View the new report and see that the message is still generated.

**Expected behavior**
The message should not be generated because the LMP is not 5.

**Screenshots**
![conditional-alerts](https://user-images.githubusercontent.com/2064938/57765619-ef2cdc00-7759-11e9-8b1f-a58afae82faa.png)

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Ubuntu
- App: sentinel
- Version: 3.5.0 (master)

**Configuration**
```json
    "alerts": [
      {
        "form": "P",
        "condition": "P(0).fields.last_menstrual_period == 5",
        "message": "ALERT",
        "recipient": "clinic"
      }
    ],
    "transitions": {
      "conditional_alerts": true,
    },
    "forms": {
      "P": {
        "meta": {
          "code": "P",
          "icon": "pregnancy-1",
          "translation_key": "form.p.title"
        },
        "fields": {
          "patient_id": {
            "labels": {
              "short": {
                "translation_key": "patient_id"
              },
              "tiny": {
                "en": "ID"
              }
            },
            "position": 0,
            "type": "string",
            "length": [
              5,
              13
            ],
            "required": true
          },
          "last_menstrual_period": {
            "labels": {
              "tiny": {
                "en": "LMP"
              },
              "short": {
                "translation_key": "report.p.last_menstrual_period"
              }
            },
            "position": 1,
            "type": "string",
            "length": [
              1,
              2
            ],
            "range": [
              2,
              42
            ],
            "required": false,
            "validations": {}
          }
        },
        "public_form": true,
        "use_sentinel": true
      },
    }
```

**Comment by dianabarsan** [comment]
Ready for AT on `5668-conditional-alerts-include-current-report`.
Post AT, please do not merge. A shared library needs to be published and dependencies bumped.

**Comment by newtewt** [comment]
This looks good. I'm seeing the alert added when the condition is met and not as shown in the bug. I'll leave it to @garethbowen  to merge as the deps need changed.

**Comment by garethbowen** [comment]
Merged!
