### ISSUE TITLE
Ability to configure forms access based on hierarchy

### ISSUE THREAD

**Issue by KenitoInc** [medic/medic#5670]
_*User story*_
As LG scales up and work on many experiment projects, it’s becoming increasing critical to have a way to `dynamically configure which CHVs access certain workflows` and who don’t have access. Sometimes CHVs participating in experiments are not segregated in a clear way like per branch. We can have sample CHVs from multiple branches.

We also need an intuitive way for non technical staff to assign and de-assign workflows/forms to CHVs unlike the current method where we put CHV uuids on the contact summary to indicate CHVs eligible for a certain experiment

_*Suggested solution*_
Adding an array of forms on the place object. These forms should be visible to everyone below the hierarchy. If you don’t want a form visible to everyone, you configure it down the hierarchy on the relevant place object. Check the example below
```
{
    "name":"…..",
    "uuid":"………",
    "forms": ["assessment.xml", "pregnancy.xml", ….],
    …
}
```
We can have a web tool (maybe on the admin panel) where a non-technical user can assign forms to branches or individual CHVs

**Comment by garethbowen** [comment]
In 2.16 we introduced a feature to [allow for more user roles to be configured](#4525). This means you can have different sets of users with different permissions. We could solve this by adding the ability to create new permissions, then a configurer could add a permission for `can_register_pregnancies`. Then the pregnancy registration form could be restricted to only users with that permission. Then non-technical users could change the users' roles to move them in and out of various experiments.

@KenitoInc Would this suit you?

**Comment by KenitoInc** [comment]
@garethbowen Two questions
1. Where will the configurer add the permission?
2. When restricting users, is there a way I can restrict the entire branch or I will have to do that one by one?

**Comment by garethbowen** [comment]
@KenitoInc 

> Where will the configurer add the permission?

I was envisioning a button to the admin app page for managing permissions. It could also be done with medic-conf by changing the `permissions` property in `app_settings.json`. I haven't tested this but adding the permission to the `app_settings.json` will _probably_ work in the app without any changes.

> When restricting users, is there a way I can restrict the entire branch or I will have to do that one by one?

Currently this would require modifying the role of a user one by one. It wouldn't be hard to script this to modify all users under a given branch. We could also consider adding a feature for adding permissions to branches to make this easier to configure.

**Comment by garethbowen** [comment]
Closing as I believe this can be achieved with configurable roles documented above. Please reopen if there's anything more to do here.
