### ISSUE TITLE
Webapp messages conversations don't scroll correctly when loading new unread records

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5672]
**Describe the bug**
On Messages tab, if you load a longer conversation and send a new message, the conversation reloads and you don't get scrolled down to the bottom. 

**To Reproduce**
1. Deploy 3.5 master
2. Login as either offline user or online user.
3. Go to Messages and select a long conversation (enough to have a scrollbar). 
4. Send a new message.
5. Observe the conversation reloading and landing in a random spot in history. If you scroll manually to the bottom, you can see your new message.

**Expected behavior**
The container should be scrolled to the bottom and you should immediately see your new message.

**Video**
https://drive.google.com/file/d/1j3O52vzBj1Xo5Cc6jzVTGbbQqyXTqNA_/view?usp=sharing

**Environment**
- Instance: local
- Browser: Chrome, Chromium, Firefox
- Client platform: Linux
- App: Webapp
- Version: 3.5

**Comment by dianabarsan** [comment]
Ready for AT on `5672-scroll-to-unread`.

**Comment by newtewt** [comment]
I'm seeing the scroll happen on both web and android versions.
