### ISSUE TITLE
API does not block offline users from editing docs when dbname is not medic

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5692]
1. Create a clean build using database name which is not medic. `COUCH_URL=http://admin:pass@localhost:5984/not_medic grunt build-dev deploy`
1. Run API using `COUCH_URL=http://admin:pass@localhost:5984/not_medic node server.js`
1. Create an offline user with a facility_id of a new `health_center`. Let this user be `user_id`. Find the id of the facility_id's parent, and let this be known as `district_id` with a `_rev` of `district_rev`. Note that the offline user's session does not have permission to edit this document.
1. `curl 'http://localhost:5988/medic/district_id' -H 'Cookie: AuthSession=session_cookie_for_offline_user;' -X PUT -H 'Content-Type: application/json' -d '{ "_rev":"district_rev" }'`

Expected: `{"code":403,"error":"forbidden","details":"Offline users are not allowed access to this endpoint"}`
Observed: The district's document is edited using a session cookie which does not have permission to edit it (or view it).

A regression from #5448 ?

**Comment by garethbowen** [comment]
@kennsippell Why do you expect that error? I think the observed one is fine - you're trying to put into a db that doesn't exist.

In point 3 is the port supposed to be `5988`?

**Comment by kennsippell** [comment]
I've updated the repro steps to be more clear. Does this answer your questions?

**Comment by garethbowen** [comment]
Ahh that makes sense to me now. Thanks for the update!

**Comment by dianabarsan** [comment]
It does appear to be a regression from #5448, indeed. 
Offline users are restricted from updating docs outside their replication depth in 3.4, even when using alternative db names. 
It appears that, in 3.5, when the used DB is not `medic` all requests (except login requests) are straight forwarded to the DB without any checks done. 
https://github.com/medic/medic/blob/master/api/src/routing.js#L199

**Comment by garethbowen** [comment]
Scheduled as a blocker for 3.5.0 due to being a regression.

**Comment by dianabarsan** [comment]
This issue will also cover restricting offline users from accessing the admin app, which has also regressed.

**Comment by dianabarsan** [comment]
For AT, please consider the following:

Deploy the app using a db that is not called `medic` (examples below will use `cidem` as the alternative db name).

Make sure that offline users:
- can login and replicate data up and down 
- their replication is restricted to their set of data (this is part of the regression, all requests were proxyed to couchdb, including _changes requests, so offline users were actually downloading everything)
- they can't update/create/delete docs that they can't see 
- they can't access admin app (details about which URLs point to the admin app below)
- they can't create new databases

All of the above should work identically if you use `medic` or `cidem` prefix:
for example, if you `curl http://localhost:5988/medic/district_id` and `curl http://localhost:5988/cidem/district_id` you should get the same response. 
Same goes for any online user request!

Make sure that online and offline users:
- can access legacy `settings` endpoints via GET. this endpoint is still used by `medic-conf` when doing settings backups!
`curl http://localhost:5988/medic/_design/medic/_rewrite/app_settings/medic`
`curl http://localhost:5988/cidem/_design/medic/_rewrite/app_settings/medic`
- users that have `can_configure` permission should be able to update settings on legacy endpoints via PUT
`curl -X PUT http://localhost:5988/medic/_design/medic/_rewrite/update_settings/medic -H 'Content-Type: application/json'`
`curl -X PUT http://localhost:5988/cidem/_design/medic/_rewrite/update_settings/medic -H 'Content-Type: application/json'`

The admin app is now available on 3 urls (with & without trailing slash)
- `http://localhost:5988/medic/_design/medic-admin/_rewrite`  
- `http://localhost:5988/cidem/_design/medic-admin/_rewrite`
- `http://localhost:5988/admin`

Goes without saying that you should expect the same behavior when db name is `medic`.

**Comment by garethbowen** [comment]
Ready for AT in `5692-fix-offline-security`

**Comment by newtewt** [comment]
I've tested these situations and some exploratory around and is working as expected. PR is merged.
