### ISSUE TITLE
Avail adding people to child places only

### ISSUE THREAD

**Issue by kitsao** [medic/medic#5693]
**Is your feature request related to a problem? Please describe.**
It is quite common for CHWs to add people outside a family/household. This has been noted for both LG and PIH, and D-Tree have expressed similar concerns after UAT that they would like to either deactivate the button or display an alert that the CHW is adding a person outside a household. Such persons go into the database as CHWs given the parent is a CHW area.

**Describe the solution you'd like**
The proposed solution is to allow adding persons to child places only. Alternatively, granular `can_create_people` permission is a possible solution.

**Describe alternatives you've considered**
No possible workaround

**Additional context**
![image](https://user-images.githubusercontent.com/3928714/58406775-08475e00-8073-11e9-9f4a-299eb44f9e95.png)

**Comment by garethbowen** [comment]
I believe this will be possible in 3.7.0 when [configurable hierarchy](https://github.com/medic/medic/issues/3639) ships. One of the features of a configurable hierarchy is the ability to have different kinds of people (eg: CHWs, patients, etc), and to be able to dictate what other contact types are valid parents for those people types. For example, you could enforce that patients can only have families as parents, and CHWs can only have CHW areas for parents.

@kitsao Would this solve your issue?

**Comment by kitsao** [comment]
Yes @garethbowen. Besides emphasizing to CHWs that they ensure they are within a household when adding a person during training, what else can we do as a stopgap?

**Comment by garethbowen** [comment]
What if you added a check in the form for the `parent.type === "clinic"`? I _think_ you have that information available...

**Comment by kitsao** [comment]
I don't think so, because the contact wouldn't be existing in order to check for the parent.

**Comment by garethbowen** [comment]
I think it's available somewhere on the context even with a new contact.

**Comment by kitsao** [comment]
I see, let me try that.

**Comment by garethbowen** [comment]
Closing as I believe configurable hierarchy can be used to solve this. Please reopen if there's something more to do here.
