### ISSUE TITLE
Update apps to use local shared-libs

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5694]
We use `npm pack` to zip `api` and `sentinel` and attach them to our build ddoc as part of build process. We also use a collection of scoped (`@medic/<library>`) [shared libraries](https://github.com/medic/medic/tree/master/shared-libs)  across our apps. 
Due to a [bug in npm](https://github.com/npm/npm/issues/17708), we were [forced](https://github.com/medic/medic/issues/5068) to `npm publish` these libraries in order for them to be packed as bundledDependencies . 

Due to the large overhead required to manage and update these published shared libraries and the fact that the [bug in npm was fixed](https://github.com/npm/npm-packlist/pull/20), our shared libraries can be local once more.

**Comment by garethbowen** [comment]
Ready for AT in `fix-error-logging`. Most of the changes only affect development, but there are some changes to how we bundle shared-libs for release. AT this in a full stack not in a development setup. Install using Horti. Then make sure the shared-libs (transitions, messages, lineage, etc) are bundled correctly into api and sentinel.
