### ISSUE TITLE
Reports with mRDT photo should also include timestamp metadata from the mRDT app

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5695]
As part of https://github.com/medic/medic-projects/issues/6195, the [mRDT app now includes a timestamp representing how long it takes the CHV to capture a photo](https://github.com/medic/rdt-capture/blob/mali/app/src/main/java/edu/washington/cs/ubicomplab/rdt_reader/ImageQualityActivity.java#L451) of the mRDT test. For data analytics reasons the research team is requesting the data be included in the medic report.

Our WebApp should receive this data from the mRDT app and bundle it into the report along with the image.

Original request from research team @ https://github.com/medic/medic-projects/issues/6222

**Comment by wtekeu** [comment]
Ready for AT using branch `5695-include-mrdt-timetaken` and attached apk.

Make sure that combinations of (`5695-include-mrdt-timetaken`, master) and (attached apk, current medic-wrapper) work to ensure backward compatibility. Also when `5695-include-mrdt-timetaken` and attached apk are tested, the resulting capture doc should include the field `timeTaken`.

apk: https://testuyter.s3.amazonaws.com/apk.zip

**Comment by kennsippell** [comment]
@wtekeu Running vNext `rdt-capture`, vNext `android`, and vNext `webapp` version. 

I am seeing

```angular.js:15536 Error loading form Error: ["TypeError: Cannot read property 'outerHTML' of undefined"](…)``` 

The user experience is that I see the "Error loading form. Please try again or check with an administrator." Is it expected that this change is not backward compatible with the mRDT xforms?

**Comment by wtekeu** [comment]
@kennsippell I tested with the mrdt demo form (which I have updated) https://github.com/medic/medic/pull/5728/files#diff-7d82c76043223e0e7ac50f1a5b4f9dfe .. I have discussed updating the form with Bara, and he mentioned that it was not an issue .. and the update is very minimal

**Comment by wtekeu** [comment]
Ok I will update the code ..

**Comment by kennsippell** [comment]
Thanks for revisiting. This is back in AT.

**Comment by newtewt** [comment]
Hey, couple questions. 

What format is this time in? "mrdt_time_taken": "43267". Full report is below. 

Should the old MRDT form work with the new apps and webapp and the new MRDT example form work in the old apps and old webapp?

I keep seeing this error in console `VM350:1 Uncaught SyntaxError: Identifier 'api' has already been declared`

Just before was 
```
PositionError {code: 3, message: "Timeout expired"}
code:3
message:"Timeout expired"
__proto__:PositionError
```

The new images have a number stamped into the corner. That wasn't there before is this an expected change? 43.185 is shown in the screenshot.

![number_stamp](https://user-images.githubusercontent.com/10531066/60339829-e2fe8600-9977-11e9-9734-64b28d875c68.png)





```
{
  "_id": "8941b94d-0391-403e-8364-6003362f1dfa",
  "_rev": "2-3a012b526b0a568a4c663e7556d3d452",
  "form": "new_mrdt_demo",
  "type": "data_record",
  "content_type": "xml",
  "reported_date": 1561721440375,
  "contact": {
    "_id": "65c52076-84c5-53a2-baca-88e6ec6e0875",
    "parent": {
      "_id": "8606a91a-f454-56e3-a089-0b686af3c6b7",
      "parent": { "_id": "fc9928ae-9f48-5d2d-8a0f-222b2389f77f" }
    }
  },
  "from": "+16143291527",
  "hidden_fields": ["mrdt_time_taken"],
  "fields": {
    "name": "T",
    "mrdt_image_data": "",
    "mrdt_time_taken": "43267",
    "meta": {
      "instanceID": "uuid:d1375b08-c6d9-4678-b86b-eaa5c1f8fac4",
      "deprecatedID": ""
    }
  },
  "_attachments": {
    "content": {
      "content_type": "application/xml",
      "revpos": 1,
      "digest": "md5-k4/HZBIj3KxlNXcwRsNLqg==",
      "length": 207396,
      "stub": true
    },
    "user-file/new_mrdt_demo/mrdt_image_data": {
      "content_type": "image/png",
      "revpos": 1,
      "digest": "md5-IwtqybkP+6Fs2aClSRmTQg==",
      "length": 155236,
      "stub": true
    }
  }
}

```

**Comment by wtekeu** [comment]
@newtewt I think the `mrdt_time_taken` is in milliseconds
The new timestamp in the image is expected. Please confirm with @Fatoufall 
Yes, the old MRDT form should work with the new app and new webapp
Yes, the new MRDT form should work with the old app and old webapp (the timestamp won't be populated)

At which stage do you see the error? Do you get with both the old app and the new app?

**Comment by wtekeu** [comment]
@newtewt try this build https://testuyter.s3.amazonaws.com/medic-android-SNAPSHOT-unbranded-debug.apk .. should take care of the console error

**Comment by wtekeu** [comment]
As for the `PositionError` I think it is related to a geolocation timeout which is unrelated to the rdt timetaken capture.

**Comment by newtewt** [comment]
@wtekeu  the time stamp `43267` is in milliseconds?  I'm going to guess then something is wrong unless it's not a standard calculation. Don't we normally calculate from the date in 1970?  Converting that to human readable would be `GMT: Thursday, January 1, 1970 12:01:07 PM`

**Comment by wtekeu** [comment]
@newtewt  We don't compute the timestamp, it is passed to use by the `rdt-capture` app. `43267 milliseconds` means it took you roughly `43 seconds` to capture the image

**Comment by newtewt** [comment]
Sorry that's my confusion. I didn't realize it was taking the time it took to take an image and not a timestamp of when the image was taken. 

I've processed through all the same combos that Kenn had done. Using the new APK for both MRDT and our android app. This is working as expected.  

There are a few PRs it looks associated. I'm not sure which ones to go after. Can you squash and merge @wtekeu
