### ISSUE TITLE
Schedules are not cleared with Unicode form codes

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5698]
**Describe the bug**
Reported in `medic-projects`: https://github.com/medic/medic-projects/issues/6366

**To Reproduce**
1. Load standard config on an instance.
1. Replace "N" form with "क" (do this in the form definition and `registrations` config, alternatively you can duplicate the form and schedule from another form)
3. Submit your new "क" form, wait until your report is processed and patient created. The report should have one scheduled task. 
4. For the new patient, submit a "P" form.

**Expected behavior**
After your "P" report is processed, the previous "क" report scheduled task should be cleared.

**What actually happens**
The scheduled task from your "क" report is still scheduled. 

**Environment**
- Instance: any 3.4, 3.5 instance
- App: api, sentinel
- Version: 3.4, 3.5

**Additional context**
When validating whether a report is a valid registration, we extract the form code from the document `form` property with `/^[^\w-]*([\w-]+)[^\w-]*$/` [here](https://github.com/medic/medic/blob/master/shared-libs/registration-utils/src/index.js#L3).
In javascript, `\w` does not match non-ASCII unicode even when using the `u` flag. 
Using the `\p` metacharacter along with the `u` flag instead works, like:
`/^[^\p{L}\p{N}_-]*([\p{L}\p{N}_-]+)[^\p{L}\p{N}_-]*$/u`

**Comment by garethbowen** [comment]
There is also a bug with the SMS parsing when you submit the "क" in step 3. Using Admin > Message Test to submit the SMS "क ralph 12347" the report comes out with a patient name of "क" and an ID of "ralph 12347".

![Screenshot from 2019-05-30 14-11-47](https://user-images.githubusercontent.com/2064938/58603447-e523e500-82e4-11e9-9af7-eb45427309c1.png)

**Comment by garethbowen** [comment]
The other bug was a misconfiguration on my part - now the code works as expected.

**Comment by garethbowen** [comment]
Ready for AT in `5698-support-unicode-form-codes`.

Don't merge when it passes because I'll need to publish libraries and backport changes to 3.4.0.

**Comment by ngaruko** [comment]
LGTM ... Back to you @garethbowen !
