### ISSUE TITLE
Cannot make multiple changes to branding without refresh

### ISSUE THREAD

**Issue by abbyad** [medic/medic#5699]
Editing each branding field in the admin console can be done once, but followup changes without a page refresh cause 409 conflict errors.

**To Reproduce**
1. Go to `/admin/#/images/branding`
1. Edit the _Title_
1. Click _Submit_
1. See that change went through (refresh app in a different tab)
1. Edit the _Title_ again
1. Click _Submit_
1. You'll see `There was an error saving your settings, please try again.` in the app, and `PUT https://gamma.dev.medicmobile.org/medic/branding 409` conflict message in console.

**Expected behavior**
Should be able to edit and submit the Title (or images) multiple times without errors and without refreshing the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/58564734-7e76cc80-81fb-11e9-972a-2b05e55f2a5c.png)

**Environment**
- Instance: gamma.dev.medicmobile.org
- App: webapp
- Version: 3.5ish (instance was running branch `5519-sw-use-tmp`)

**Comment by garethbowen** [comment]
Ready for AT in `5699-improve-branding-admin-page`. This is in the same branch as #5725 and #5727 .

**Comment by ngaruko** [comment]
LGTM
