### ISSUE TITLE
Webapp doesn't support languages that are not pluralized by `make-plural`

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5705]
**Describe the bug**
Reports fail to load when the user language isn't pluralized by `make-plural`. 

**To Reproduce**
1. Install 3.5 (or 3.4)
2. Create a new language with a code that is not-existent or is not pluralized by `make-plural`. For example "rn". 
I prefer to copy whole contents of a translation file that already exists and just change the `code` and `_id` fields to match.
3. Login as an online user to the instance and change your language to "rn". Go to reports. **Refresh**
4. Observe that no reports load on the LHS and translations are missing from some of the filters.

**Expected behavior**
Reports LHS should load. 

**Logs**
There are no errors logged in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/58900966-dbe1b080-8708-11e9-9318-cf1a82afb049.png)

**Environment**
- Instance: local, [live instance](https://github.com/medic/medic-projects/issues/6310)
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.4, 3.5 (possibly earlier)

**Additional context**
There are no errors visible in the console because `angular-translate` [deliberately ignores all translation loading errors](https://github.com/angular-translate/angular-translate/blob/master/src/service/translate.js#L1950):
```
langPromises[key]['finally'](function () {
    clearNextLangAndPromise(key);
})['catch'](angular.noop); // we don't care about errors (clearing)
``` 
If I change the source to actually log the error, replacing `angular.noop` with `console.error`:
```
Error: Localisation function not found for locale "rn"
    at Object.get (plurals.js:31)
    at new MessageFormat (messageformat.js:37)
    at Object.setLocale (angular-translate-interpolation-messageformat:121)
    at eachInterpolator (angular-translate.js:1633)
    at Object.forEach (angular.js:401)
    at useLanguage (angular-translate.js:1638)
    at angular-translate.js:2324
    at processQueue (angular.js:17914)
    at angular.js:17962
    at Scope.$digest (angular.js:19075)
```
We plug in the `message-format` interpolation to handle plurals, which in turn uses `make-plural` library.
We wait for the `$translate` to be `ready` [before we load forms](https://github.com/medic/medic/blob/master/webapp/src/js/controllers/inbox.js#L421), 
and we wait for forms to be loaded [before we load reports in the LHS](https://github.com/medic/medic/blob/master/webapp/src/js/controllers/reports.js#L471).
We also wait for `$translate` to be `ready` to load report filters.

`$translate` throws the error before broadcasting the "ready" event, so forms never load, so reports never load.

`make-plural` covers lots of languages, but not all. "rn" is a valid language code for Kirundi.
[Link to the source of `make-plural` covered languages](https://github.com/eemeli/make-plural/blob/master/packages/plurals/umd/plurals.js)

**Comment by garethbowen** [comment]
We need to find a way to handle locales that aren't supported by `make-plural` otherwise this will hit us again. This can be patched in for the 3.5.0 release but we should also contribute it back to `make-plural` in some form.

We should also contribute back an implementation for `rn` so this can be solved properly and upstream.

**Comment by derickl** [comment]
From @SMurithi the project has been facing this issue for a couple of weeks. Is it possible to path 3.4? @garethbowen

**Comment by garethbowen** [comment]
The medic-projects issue is marked as "medium" priority. Is that no longer correct?

**Comment by derickl** [comment]
I'll let @SMurithi give appropriate context in medic-projects so that we are all on the same page.

**Comment by dianabarsan** [comment]
Ready for AT on `5705-support-custom-locales`.

**Comment by ngaruko** [comment]
Are we back porting this to 3.4 @dianabarsan ?

**Comment by dianabarsan** [comment]
@ngaruko  I don't this so.

**Comment by ngaruko** [comment]
LGTM
*Before*
![image](https://user-images.githubusercontent.com/6979995/59312640-f536be00-8d01-11e9-8383-78c33e1d7662.png)

*After*
![image](https://user-images.githubusercontent.com/6979995/59313265-59f31800-8d04-11e9-909e-f1dff001fa9f.png)

Will close this and merge
