### ISSUE TITLE
Remove unused less variables

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5711]
@amandacilek has found a bunch of variables in our `variables.less` file which aren't referenced anywhere. Remove them to reduce confusion.

**Comment by garethbowen** [comment]
Ready for AT in `5711-remove-unused-css`

**Comment by ngaruko** [comment]
Unused css have been removed. I guess there is no much to AT @amandacilek except to check that pages still render properly (ie, no useful css removed as well).

**Comment by garethbowen** [comment]
Yeah there's not much here. It can probably be left for regression testing. Merged.
