### ISSUE TITLE
Primary contact created through "new place form" doesn't have hierarchy

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5715]
**Describe the bug**
The `contact` attribute for places should be a hierarchy of parents, but this isn't properly set when creating contacts through the default form for creating a new place.

I haven't checked if this is an issue with the form or the app. I'm also unsure of any negative user-outcomes of this. May increase severity of this bug once these factors are known.

**To Reproduce**
1. From a clean database running latest master.
1. Create a new district as administrator. When prompted, set the primary contact as "create contact".
1. Create a new health_center as administrator. When prompted, set the primary contact as "create contact".
1. Inspect the document created as the primary contact of the health_center.

**Expected behavior**
This document's `contact` attribute should have a `parent` attribute but it does not.

**Logs**
If applicable, include the server or browser logs.

**Screenshots**

**Environment**
Latest `master`

**Comment by SCdF** [comment]
@garethbowen where are we in the whole "replace our weird defaults by shipping standard config" landscape? Would it be sensible to get that done instead of this?

**Comment by garethbowen** [comment]
That's #3779 . I think it's currently blocked waiting for the CHT reference app so we get smartphone features out of the box.

This issue may be "fixed" by configurable hierarchy ( #3639 ) which removes a lot of this code and requires custom place creation forms.

**Comment by newtewt** [comment]
@kennsippell  this issue only applies to master right? Seems 3.6.1 is working on and I'm using @garethbowen 's branch for config hierarchy and works as well.  I'm thinking this should be closed as apart of the config hierarchy ticket.

**Comment by kennsippell** [comment]
Sounds like @garethbowen launched a preemptive strike. Happy to close as fixed - maybe when those changes merge?

**Comment by kennsippell** [comment]
I have confirmed this as fixed in latest master + latest master standard.
