### ISSUE TITLE
New households registered do not show on the contact list until after page reload

### ISSUE THREAD

**Issue by kitsao** [medic/medic#5718]
**Describe the bug**
A new household created does not appear immediately on the contact list, until the page is reloaded.

**To Reproduce**
1. Login as a normal user (health_center level)
2. Submit a new household/place (clinic)
3. The household does not show up on the contact list
4. Reload the page to display the new household on the contact list

**Expected behavior**
A newly added household shows on the contact list.

**Logs**
None.

**Environment**
- Instance: any on version 3.4.0
- Browser: Chrome
- Client platform: Linux 18.04, Windows 10
- App: webapp
- Version: 3.4.0

**Comment by garethbowen** [comment]
I can reproduce this on `master` 3.5.0. Scheduling...

**Comment by garethbowen** [comment]
This is easiest to reproduce with a small database, for example, when adding your first clinic. When a new clinic comes in we do the search again limited by the number of clinics on the left hand side. If the clinic is sorted to the bottom then it's below the limit and doesn't get returned by the search. If it's sorted in the middle of the list it works as expected.

**Comment by garethbowen** [comment]
Ready for AT in `5718-minimum-query-limit`

**Comment by ngaruko** [comment]
LGTM
**Before**
![image](https://user-images.githubusercontent.com/6979995/59570362-ff363380-90ea-11e9-8bbc-43b965173ca0.png)


**After** 
![image](https://user-images.githubusercontent.com/6979995/59570868-820ebc80-90f2-11e9-9c70-33fe189e32b0.png)
