### ISSUE TITLE
UI/UX updates on admin app Branding page

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5725]
Relates to #5391 (text updates to this page)

- [ ] Content in the “Branding” tab is too close to the navigation on the left. There should be a consistent 30px gap, just like on all the other pages.
- [ ] Add more white space between sections. Also too many horizontal grey lines, suggest removing the grey lines directly underneath the “Upload header logo” “Logo” and “Upload favicon” texts.

Split off from #5435

**Comment by garethbowen** [comment]
Ready for AT in `5699-improve-branding-admin-page`. This is in the same branch as #5699 and #5727 .

**Comment by newtewt** [comment]
This looks good but as there are conflicts in the branch I'll recheck the 3 issues once updated.
