### ISSUE TITLE
Updating branding images doesn't delete the obsolete attachments

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5727]
**To Reproduce**
1. Go to `App Settings > Images > Branding`
2. Upload a new logo
3. Hit Submit
4. Inspect the doc in the database and notice there are now three attachments

**Expected behavior**
There should only be two attachments - the favicon and the _new_ logo. Additional files have to be replicated down to clients even though the image will never be shown.

**Comment by garethbowen** [comment]
Ready for AT in `5699-improve-branding-admin-page`. This is in the same branch as #5699 and #5725 .

**Comment by ngaruko** [comment]
LGTM
**Before**
![image](https://user-images.githubusercontent.com/6979995/61502500-500db480-aa28-11e9-981d-c6bd6dd4c3a0.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/61502840-99123880-aa29-11e9-9435-a5d8874828fa.png)

**Comment by ngaruko** [comment]
Closing this - will remember to merge once the other 2 issues on same branch have  passed AT.
