### ISSUE TITLE
Cannot add more than one household member

### ISSUE THREAD

**Issue by chelule** [medic/medic#5729]
**Describe the bug**
While creating a clinic and adding persons using a repeat group, the plus sign shows up only once and remains hidden after that thus one cannot be able to add more people. 
**To Reproduce**
1. Add family
2. (Based on LG configuration avaliable on medic/config-lg ) Proceed , Do you have other family members? Answer yes
3. Hit the plus first time, provide details of 1st person, 
4. Observe bottom of the page for the plus  - Only the Minus button appears.

**Expected behavior**
Plus button in the page to add more persons 

**Logs**
N/A
**Screenshots**
<img width="369" alt="Screen Shot 2019-06-18 at 18 49 40" src="https://user-images.githubusercontent.com/1633299/59701125-8d9ada00-91fd-11e9-8825-86e2edadf4d9.png">
<img width="371" alt="Screen Shot 2019-06-18 at 18 49 51" src="https://user-images.githubusercontent.com/1633299/59701131-9095ca80-91fd-11e9-841c-59e1383ecbe7.png">
<img width="365" alt="Screen Shot 2019-06-18 at 18 50 04" src="https://user-images.githubusercontent.com/1633299/59701142-97244200-91fd-11e9-97b4-51c560455b36.png">
<img width="375" alt="Screen Shot 2019-06-18 at 18 47 28" src="https://user-images.githubusercontent.com/1633299/59701211-bde27880-91fd-11e9-850a-79f5b64c9322.png">

**Environment**
- Instance: localhost test instance with docker medic-os
- Browser: Chrome
- Client platform: MacOS
- App: Medic webapp
- Version: 3.4, 3.3

**Comment by derickl** [comment]
@chelule could you attach the XLSForm used?

**Comment by KenitoInc** [comment]
[clinic-create.xlsx](https://github.com/medic/medic/files/3371556/clinic-create.xlsx)
@derickl Kindly see attached

**Comment by derickl** [comment]
@chelule @KenitoInc could you remove the `field-list` appearance set on the `repeat` group and re-upload and test again?

**Comment by KenitoInc** [comment]
@derick Removing `field-list` fixes the issue.

**Comment by ngaruko** [comment]
LGTM
**Before**

![image](https://user-images.githubusercontent.com/6979995/61427638-02834000-a973-11e9-86b8-81ba28d70dc6.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/61430799-47ad6f00-a97f-11e9-98c8-27d8f59ebf50.png)

**Comment by ngaruko** [comment]
@peter-ochieng Merging is blocked for this PR . Can you please have a look have a look at the PR and  address requested changes ?

**Comment by dianabarsan** [comment]
Ready for AT on `5729-add-button-on-repeats`.

**Comment by newtewt** [comment]
@peter-ochieng can you tell me what changed for this ticket? I'm kind of confused as it seems the issue was form related and we made a change to the app. Can you clarify?

**Comment by peter-ochieng** [comment]
@newtewt Yes, this issue could be resolved by removing the `field-list` appearance set on the repeat group but I also applied a css fix which fixed the issue regardless of whether the `field-list` is set.

**Comment by newtewt** [comment]
@peter-ochieng  thanks for clarifying. I'm seeing the add button with or without the field-list option.
