### ISSUE TITLE
Build deletion script fails to execute

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5736]
Found while investigating https://github.com/medic/medic-projects/issues/6478

The `scripts/travis/cleanup.js` is run after each testing build and is meant to delete old builds, but it's failing because the `validate_doc_update` function doesn't like us uploading minimal deletion docs.

This is high priority because it's causing most builds to fail.

**Comment by SCdF** [comment]
Merged, as it's a technical issue no AT is required
