### ISSUE TITLE
Mobile "back" button not working as expected when creating reports

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5741]
**Describe the bug**
When creating or updating reports, instead of displaying the cancel "X" button, the mobile navigation shows the back "<" button which does not actually cancel creating the form. 

**To Reproduce**
1. Login to a 3.5 instance, use a user with an associated contact that can create reports
2. Switch your browser to mobile view
3. From the reports page, add a new report (does not matter which)
4. Notice that the header doesn't show an "X", rather a "<"
5. Edit a field and click on the "<"

**Expected behavior**
You should get a popup saying "this form is not finished....are you sure you want to leave". Clicking on "No" should keep you on the same page, filling the form. Clicking on "Yes" should take you to the reports list.

**What actually happens**
The popup doesn't show and you go to the reports list directly. If you click on an existent report from the list or try to add another form or try to navigate to another tab, you will get the aforementioned popup. 

**Logs**
No errors in the logs.

**Environment**
- Instance: gamma.dev.medicmobile.org, any 3.5 instance
- Browser: any
- App: webapp
- Version: 3.5

**Additional context**
Appears to have been introduced in 3.5, when  moving scope properties to Redux store. 
3.4 works as expected.
****

**Comment by garethbowen** [comment]
Ready for AT in `5741-correct-scope`

**Comment by ngaruko** [comment]
LGTM

**Before**
![image](https://user-images.githubusercontent.com/6979995/60056777-341f3780-9736-11e9-82b6-4914a7e2bc0b.png)

**After**
 
![image](https://user-images.githubusercontent.com/6979995/60058108-389a1f00-973b-11e9-8520-85de963d3b1b.png)

and warning popup restored
![image](https://user-images.githubusercontent.com/6979995/60058132-51a2d000-973b-11e9-97bf-229ab2eb112b.png)

Good to go @dianabarsan .

**Comment by garethbowen** [comment]
Merged and backported to `3.5.x`.
