### ISSUE TITLE
The translation "contact.no.children" is missing in the default configuration

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5742]
**Describe the bug**
contact.no.children is missing a translations. There isn't an English or any other language as far as I can tell so the key is displayed. 

**To Reproduce**
1. Setup a new instance of the app
2. Log in as admin
3. Navigate to contact with no children.

**Expected behavior**
A label is displayed that describes what no children is.

**Screenshots**
![Screen Shot 2019-06-21 at 12 25 38 PM](https://user-images.githubusercontent.com/2064938/59982228-09b07a00-9663-11e9-91b9-44e75d92905d.png)

**Environment**
- Instance: gamma.dev
- Browser: chrome
- Client platform: Linux
- App: webapp
- Version: 3.5

**Additional context**
Workaround:

1. App Settings > Languages > Application Text
2. Click "Add Translation"
3. Use "contact.no.children" as the translation key
4. Provide one or more translations
5. Press "Submit"

**Comment by garethbowen** [comment]
This needs a review, but we can AT in parallel. Branch: `5742-missing-translation`

**Comment by ngaruko** [comment]
LGTM
**Before**
![image](https://user-images.githubusercontent.com/6979995/59983052-e12e7d00-966e-11e9-9418-4277736af454.png)

**after**
![image](https://user-images.githubusercontent.com/6979995/59983097-7f224780-966f-11e9-9c8c-6c932df84b83.png)
Leaving it open, pending the code review. Feel free to merge and close after the review @peter-ochieng ...

**Comment by garethbowen** [comment]
This will need to be backported to `3.5.x` also. Feel free to leave that to me if you prefer.

**Comment by garethbowen** [comment]
Merged and backported to `3.5.x`
