### ISSUE TITLE
User cannot login when database name is not medic

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5743]
**Describe the bug**
User cannot login when database name is not medic.

**To Reproduce**
1. Start api with `COUCH_URL` specifying a database which is not `medic`
2. Navigate to `http://localhost:5988`
3. Login

**Expected behavior**: Login
**Observed behavior**: Error

**Comment by garethbowen** [comment]
Ready for AT in `5743-dbname-login`

**Comment by ngaruko** [comment]
Does this needs  to be backported to 3.5.x @garethbowen ?

**Comment by garethbowen** [comment]
Yes.

**Comment by ngaruko** [comment]
Thanks. LTGM. Feel free to merge and  backport @kennsippell .

**Comment by kennsippell** [comment]
Backported!
