### ISSUE TITLE
Ability to hide a field within a section on the Reports tab detail

### ISSUE THREAD

**Issue by amandacilek** [medic/medic#5747]
Currently for the Muso mRDT project, we are hiding most of the fields on the Reports detail page so that supervisors can more quickly and easily find the information that they need (mainly, the Results field).

Right now Muso supervisors are seeing two result fields, instead of one, which is confusing:

**Resultat:** 
pos

**Resultat du TDR de l’ASC est:** 
Positive (+)

![Screen Shot 2019-06-24 at 9 10 42 AM](https://user-images.githubusercontent.com/26235957/60040849-c1975480-966e-11e9-895b-1a39d4348030.png)

As I understand it, both of these fields have to be shown because they are part of the same section/group and right now we can’t hide a single field within a section. This request is to allow us to hide a field within a section (or to experiment with other solutions that only show one result field to the supervisor).

**Comment by garethbowen** [comment]
That's not great. It should be reasonably easy to fix - the code needs to be updated to recurse into the groups.

**Comment by garethbowen** [comment]
Ready for AT on `5747-recurse-to-generate-hidden-fields`

**Comment by garethbowen** [comment]
@newtewt Ready for AT again. Sorry about that!

**Comment by newtewt** [comment]
I'm able to hide single fields or groups using the tag="hidden"
