### ISSUE TITLE
Admin upgrade page doesn't update 

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5750]
**Describe the bug**
If `horticulturalist` deletes the deployment document before the the admin upgrade page receives the latest update, the admin page will not update to inform the user that the upgrade has finished. 

**To Reproduce**
This is a race condition, so not guaranteed to happen every time. 
1. Install 3.5 with Horticulturalist.
2. Upgrade to another version and keep the admin upgrade page open.
3. The page remains stuck on "Deploying new installation" even after the app was successfully updated. 

**Expected behavior**
The page should show "Deployment complete." and a "Reload application" button after upgrade. 

**Environment**
- Instance: local
- App: admin
- Version: 3.5, 3.6

**Comment by dianabarsan** [comment]
Ready for AT on `5750-update-on-delete`. 
To AT, install the branch and then upgrade to something else, checking on the admin upgrade page.

**Comment by newtewt** [comment]
Cool, I've upgraded to a few different branches from ` 5750-update-on-delete` and was presented the reload application button each time.
