### ISSUE TITLE
CSP error in Console rendering forms with attached images

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5753]
Images injected using the `media` attribute in XForms result in an error in the console:

> /#/contacts/cb547802-75f6-48ef-bce0-0a28539789d0/report/patient_assessment_over_5:1 Refused to load the image 'jr://images/positive.png' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".

The media is displayed.

**To Reproduce**

1. Deploy an XForm which includes 'media"
1. Load the form
1. Inspect the console

**Expected behavior**
This console error should not be unnecessary noisy and unnecessary feedback documents.

@garethbowen:
> It shouldn't be noisy - the src should be swapped out before it's rendered in the browser
```elem.attr('src', '#' + src);```
> Thinking about it, that may not be sufficient to stop the browser trying to load it
> Maybe we need to drop the src altogether

https://github.com/medic/medic-projects/issues/6505

**Comment by garethbowen** [comment]
@kennsippell Do you think this should block 3.5.0 or be in 3.6.0? I think the images work, albeit with a spurious error, but other media types are blocked completely. I'm not aware of anyone using any other media types so we might get away with it until 3.6.0, and I don't want to delay 3.5.0 unnecessarily.

**Comment by kennsippell** [comment]
From Muso/mRDT perspective, I wasn't considering this urgent. Definitely not 3.5. 
Would you clarify which media times are blocked completely?

**Comment by garethbowen** [comment]
The CSP "mediaSrc" was insufficient, whereas "imgSrc" was fine. So images load and "media" don't. The only "media" I tested was video.

**Comment by kennsippell** [comment]
Just saw your PR ... 3.6 seems appropriate

**Comment by garethbowen** [comment]
Ready for AT in `5753-loading-media-in-forms`. I used `demo-forms/multimedia.xml` to test it out.

**Comment by newtewt** [comment]
I'm able to see images and videos run on the provided form. Closing this out. 

Side question: Do we have a supported list of "medias"?

**Comment by garethbowen** [comment]
> Do we have a supported list of "medias"?

The old code looked for video, audio, or images. The new code is more flexible and tries to load anything with an attribute of `src="jr:..."`
