### ISSUE TITLE
Investigate performance degradation when loading the app on 3.5.0.beta.2

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5756]
**Describe the bug**
Performance timings (stopwatch) are slower now when logging in to the app on all devices (chrome desktop, tecno wx3, and J5 in the mobile app)

**To Reproduce**
1. Install 3.5.0.beta.2 
2. Seed with data
3. Log in as restricted user from seed data. Start timer when pressing log in. 

**Expected behavior**
When the loading finishes and the app is loaded(no replicating/ loading rules displayed and tabs are clickable) stop the timer. 
Time has gone 1:45 up from 0:55

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome, Mobile App
- Client platform: Linux, Android
- App: webapp
- Version: 3.5.0.beta.2

Details on times here. 
https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw/edit#gid=0

**Comment by garethbowen** [comment]
The tests are being rerun so I've blocked this awaiting confirmation of the issue.

**Comment by newtewt** [comment]
This is due to a change in the dataset. Testing the same data on 3.4.1 is similar but lower performing on that version. Closing.
