### ISSUE TITLE
Makes replication _all_docs requests quicker

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5759]
When replicating down, after receiving a batch of changes, PouchDB will iterate them to comprise a list of docs that are on their 1st revision. If any are found, it would try to get them with an `_all_docs?include_docs=true` request, presumably as a performance shortcut.
Once it receives the results, all of the docs that are not retrieved (for any reason) or have attachments or have since been edited or have conflicts, will be retrieved with the next `_bulk_get` request. 

The `_all_docs` calls are particularly expensive, as the implementation composes the list of all allowed doc ids that the user is allowed to see and compose a response based on that.
While this implementation is correct for generalized `_all_docs` requests (requesting `_all_docs` without parameters is expected to return the full list of existent docs stubs), we could improve it for the specific case of replication requests (that use `keys` and `include_docs=true`) parameters to actually request the docs and run the view map queries over the results to filter the ones the user is allowed to see - similar to how we filter `_bulk_get` requests.

**Comment by garethbowen** [comment]
Ready for AT in `5759-faster-replication-all-docs`

**Comment by newtewt** [comment]
Looks good. Checked replicating from nothing, checked replicating new docs after the fact, creating, editing, deleting, and couldn't access/edit docs not owned by the user.
