### ISSUE TITLE
The `initial_replication_date` in info docs is always `unknown`

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5760]

**Comment by SCdF** [comment]
Here is how this was initially implemented: https://github.com/medic/medic/commit/bb6c07118be6cd4dda01a474f41d6cf3dbbc3d40

This pulled the initial replication date from the audit log DB, or used `unknown` if that failed.

However, subsequent refactorings, presumably when we switched how we audit, has lost this functionality and so it's always set to `unknown`.

**Comment by garethbowen** [comment]
@SCdF I think we should get this in to 3.6.0. What do you think?

**Comment by SCdF** [comment]
@garethbowen I put it in 3.7 to not be controversial, but I agree. We may even wish to backport it to 3.5.1?

There are two solutions here, we could do the easy non-controversial one for 3.5.1 / 3.6.0 and then ship a more correct one (if the performance holds up) in 3.7.0?
 - Easy: if you request an info doc and it doesn't exist, set the `initial_replication_date` to `Date.now()` instead of `unknown`. In this implementation the date will be close enough if sentinel is keeping up, except where it's incredibly wrong (because you edit a historical document that hasn't had an info doc generated yet)
 - Harder: maintain the infodoc dates in api as we PUT/POST/bulkdocs, and use `unknown` in cases where you need to generate an infodoc from sentinel's perspective. This is as correct as it can be, but will slow writes down (and I don't think we can safely write out of request flow for conflict reasons) by some amount we'd need to test

Here is the easy PR: https://github.com/medic/medic/pull/5766

I'm looking into the harder one now.

**Comment by garethbowen** [comment]
Let's get the easy one in 3.6.0 for now - we can backport it if something holds up 3.6.0.

**Comment by garethbowen** [comment]
Ready for AT in `5760_quick_fix`

**Comment by ngaruko** [comment]
Testing this with `http://admin:pass@localhost:5988/medic-sentinel/settings-info`. Still getting `unknown` for `initial_replication_date`:
![image](https://user-images.githubusercontent.com/6979995/60583036-11e48400-9dde-11e9-9905-a3837dae7f43.png)

Can you add a some notes on the ticket @SCdF ?
Thanks

**Comment by SCdF** [comment]
Whoops, sorry about having no AT notes. Here we go:
 - `initial_replication_date` will be set on an info doc as a date (as opposed to 'unknown') if *either* the doc comes in from SMS, *or* if the doc is on its first `_rev` when Sentinel sees it.
 - This means that if you create a new report as an offline user who then goes online, the initial_replication_date should be when it syncs (and when sentinel catches up).
 - It is expected that if an offline user creates and then edits a document before syncing the initial replication date will be set to unknown. This is an unfortunately limitation of this particular approach we've taken, and will be hopefully fixed in a later release.

So your above example is working correctly: we *don't* know the initial replication date of this document. In fact, it was almost certainly initially created much before this code, so it would be literally impossible to know.
