### ISSUE TITLE
The POE export script incorrectly detects invalid placeholders

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5763]
**Describe the bug**
We recently introduced a script to export our translations from POE into the repo for inclusion in the release. One of the parts of this tries to detect when someone has accidentally translated or typoed a placeholder (eg: `{{contact.nme}}`). This works well mostly but is showing a lot of false negatives.

**To Reproduce**
1. Install the POE script following the instructions in [the README](https://github.com/medic/medic/tree/master/scripts/poe)
2. Go to `/ddocs/medic/_attachments/translations`
3. Run `poe export .`
4. See a bunch of errors, eg:

```
FAILURE: messages-loz.properties: Translation key messages.v.report_accepted on line 752 has placeholders that do not match those of messages-en.properties
FAILURE: messages-ne.properties: Translation key contact.primary_contact_name on line 426 has placeholders that do not match those of messages-en.properties
FAILURE: messages-es.properties: Translation key contact.primary_contact_name on line 426 has placeholders that do not match those of messages-en.properties
```

**Expected behavior**
It should only error when the placeholder is actually invalid. 

**Environment**
- Instance: localhost
- Client platform: Ubuntu
- App: webapp script
- Version: master

**Additional context**
The workaround is to ignore the errors - the script still does the export and the files can be committed regardless.

**Fix**

Examples of false negatives:

- Not using a placeholder that the reference language (English) uses - it may make sense in some languages to omit a placeholder altogether and this is valid.
- Using a placeholder multiple times or in a different order than the reference language does.
- Using a placeholder that does work but isn't used in the reference language.

We need to build a list of valid placeholders. Currently that list is only what is provided in the English translation, but that's incomplete. I think we need to include some sort of allow list of placeholders which are valid even if they're not included in the English translation.

**Comment by garethbowen** [comment]
Ready for AT in `5763-poe-invalid-placeholder`

**Comment by newtewt** [comment]
@garethbowen  for the .env file do we have details on what needs to be provided here? Do we have an account for this?
```
DEBUG = false
POE_API_URL = https://api.poeditor.com/v2
POE_API_TOKEN =
POE_PROJECT_ID = 
SLACK_WEBHOOK_URL =
```

**Comment by garethbowen** [comment]
@newtewt The API token is in 1password. The project id is "33025" I think. The webhook can be left blank.

**Comment by newtewt** [comment]
@wtekeu  I'm seeing a `messages-ex` file now. What is that file used for?

**Comment by wtekeu** [comment]
@newtewt This file lists additional valid placeholders for each key. It is to be updated manually if the validation starts failing after the developer has checked that it is in fact valid.

**Comment by newtewt** [comment]
Thanks, looks good to me.
