### ISSUE TITLE
Node environment error after upgrading to 3.5.0 release

### ISSUE THREAD

**Issue by kitsao** [medic/medic#5767]
**Describe the bug**
Getting a NODE_ENV error on the browser console after a successful upgrade to 3.5.0:
`
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to ensure you have the correct code for your production build.
`

**To Reproduce**
Upgrade an instance to release 3.5.0

**Screenshots**
![image](https://user-images.githubusercontent.com/3928714/60340699-f845d580-99b4-11e9-859a-c45c413c184f.png)

**Environment**
- Instance: Any running 3.5.0
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.5.0

**Comment by dianabarsan** [comment]
Ready for AT on `5767-put-redux-in-prod-mode`.

**Comment by newtewt** [comment]
This is working as expected now. Although, I'm kinda confused because we set  `export NODE_ENV='production'` all over the place in medic-os. Is this becasue couchdb is serving that file and looking at the scripts it's one of the few places that's not set?

**Comment by dianabarsan** [comment]
@newtewt 
This is in webapp (which runs in your browser), not in API or Sentinel which run serverside with node.
The code that runs in your browser isn't processed serverside at all, only served, it's generated at build time in Travis, and this is what has changed.
