### ISSUE TITLE
View Report on outgoing messages tab brings up blank page

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5780]
**Describe the bug**
Clicking view report on the outgoing message tabs brings up a new tab with url shown as `about:blank#blocked`

**To Reproduce**
1. Admin app
2. click on outgoing messages tab
3. Click view report

**Expected behavior**
A new tab is displayed and nothing is loaded. The url shows as `about:blank#blocked`. In firefox it's slightly different and displays  `unsafe://#/reports/0e7d8339-4912-4ba3-ae59-9238decc2023` in the url and  the error below in the body.
```
The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (unsafe) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.
```

**Screenshots**
Firefox screenshot

![image](https://user-images.githubusercontent.com/10531066/60530484-d3a87100-9cc6-11e9-83c7-20c052424d3c.png)

**Environment**
- Instance: gamma.dev or localhost
- Browser: chrome, firefox
- Client platform: linux
- App: admin
- Version: 3.6.0

**Comment by dianabarsan** [comment]
Ready for AT on `5780-failing-view-report-outgoing-messages`

**Comment by ngaruko** [comment]
LGTM.
