### ISSUE TITLE
Offline users that `can_configure` are redirected to `admin` app

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5785]
**Describe the bug**
In 3.4, we introduced a feature to [automatically redirect admins to the admin app - 5035](https://github.com/medic/medic/issues/5035). This redirect is, unfortunately, done for offline users as well.

**To Reproduce**
1. On a 3.4 or 3.5 instance, create an offline role that `can_configure` and create a user with this role
2. Login to the instance with this user
3. You are redirect to `<your instance url>/admin` (or `<your instance url>/medic/_design/medic-admin/_rewrite` for 3.4) and all you see is: `{"error":"forbidden","reason":"Insufficient privileges"}`

**Expected behavior**
You should be bootstrapping webapp.

**Environment**
- Instance: any 3.4, 3.5 instance

**Additional context**
Tagging this as low priority, as an offline role that `can_configure` could be considered misconfigured.

**Comment by garethbowen** [comment]
Ready for AT in `5785-offline-users-redirect`

**Comment by newtewt** [comment]
The redirect is working as expected when logging in. However, there is now the option to access the configuration wizard. Which in the previous version after getting to the app even with that permission it wasn't showing. 

![image](https://user-images.githubusercontent.com/10531066/62489397-a737b700-b794-11e9-9464-b12edeae07c6.png)

**Comment by dianabarsan** [comment]
@newtewt are you certain it was hidden in the previous version? 
Last time I think this was referenced was here: https://github.com/medic/medic/issues/4786#issuecomment-430179442 
From the code, that link is always visible when the user `can_configure`.

**Comment by newtewt** [comment]
You're right, I double checked against a offline user with can_configure on an older version and it shows. I'll close this.
