### ISSUE TITLE
Muso's mRDT supervisor tasks cannot resolve

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5789]
For Muso's mRDT supervisor workflows:
* A CHW creates a report with `needs_signoff: true` for patient C.
* Supervisor A logs in with replication depth 1. The report replicates to their phone only because of `needs_signoff`. They can review/approve the report.
* A task triggers action from Supervisor A. Clicking the task makes a second report indicating the supervisor has followed up.

**Expected Behaviour**
The action of the task should be able to resolve the task.

**Observed Behaviour**
The logic controlling tasks is scoped to only access data for one contact at a time. Therefore the report which is created must be assigned with a `patient_id` which is equal to the owner of the original report (patient C). 

Because of the replication depth, patient C is not present on the device and the app crashes when building a ContactSummary. The user sees no error (only an infinite spinner), but does this appears in the console:

```
Error: Document not found: cb547802-75f6-48ef-bce0-0a28539789d0
    at lineage-model-generator.js:26
```

**Second Problem**
If the follow-up report were to be properly associated with Patient C, the task would still be impossible to resolve. This is because reports associated with contacts which are not on the device are not grouped under the same contact (even though the associated contact id is the same) - each report is given a new unique anonymous contact, so they are never in scope at the same time for the task logic.

More details about these scenarios and other issues contained in: https://github.com/medic/medic-projects/issues/6519 and https://github.com/medic/medic-conf/issues/205

**Comment by kennsippell** [comment]
Muso configuration code for this task at https://github.com/medic/medic-projects/pull/6531

**Comment by kennsippell** [comment]
Since 3.7 is quite a ways out, and 3.6 is the build planned for Muso's mRDT scale-up : we should consider releasing this in 3.6 or creating a 3.6.1 for it.

**Comment by garethbowen** [comment]
Ready for AT in `5789-mrdt-resolve`

**Comment by ngaruko** [comment]
LGTM
