### ISSUE TITLE
Make replication _bulk_docs requests quicker

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5797]
Similarly to https://github.com/medic/medic/issues/5759, the current implementation of `_bulk_docs` filtering for offline users makes use of getting all the allowed doc ids in order to determine whether the user is allowed to edit an existent doc. 
For large users, getting the allowed doc ids can be quite time consuming. 
Instead of getting all allowed ids, we can do an `_all_docs` to get all existent docs that the user is trying to update and run the view map functions over the results in order to filter the allowed ones.

**Comment by garethbowen** [comment]
Ready for AT in `5797-faster-bulk-docs`

**Comment by newtewt** [comment]
@dianabarsan  other than it should be faster, can you share what else you think would be good to focus on for this?

**Comment by dianabarsan** [comment]
@newtewt the change alters the way we determine whether an offline user is allowed to edit an existent doc. 
Besides being faster than before, it should continue to work the same: offline users should only be allowed to edit an existent doc if they are allowed to see the current version and they would be allowed to see the edited version.

**Comment by newtewt** [comment]
Thanks,  I've ran through a few scenarios testing creating, editing, and deleting docs. Also tried viewing and editing docs outside of the users access and was denied each time. I'm closing this one out.
