### ISSUE TITLE
The style loading is delayed when launching a new form from the reports tab

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5805]
**Describe the bug**
When loading a form from the reports tab. The form seems to be squished to the top of the page and then the style eventually loads. Processing the same report from the people tab either seems to not have this issue. I've attached some screenshots that show and a video. 

**To Reproduce**
1. Go to reports tab
2. Open a new pregnancy report from standard config
3. The right hand side loads the report and the buttons are at the top. Then eventually the style loads. 

**Expected behavior**
Hopefully the page styling and loading can be cleaned up to not jump around a bit. 

**Screenshots**
Squished:

![image](https://user-images.githubusercontent.com/10531066/61239584-3b21e000-a70d-11e9-93b3-7e7bfcd71ae9.png)

After Loaded: 
![image](https://user-images.githubusercontent.com/10531066/61239518-0f065f00-a70d-11e9-9ff1-9a60e68cf1d1.png)

**Environment**
- Instance: gamma.dev
- Browser: Chrome
- Client platform: Linux
- App: Webapp
- Version: 3.6.0-beta.1

[stlye-delay.zip](https://github.com/medic/medic/files/3393670/stlye-delay.zip)

**Comment by garethbowen** [comment]
I've noticed this too, I think it's something to do with the redux refactor - "loading content" is set to false too early.

**Comment by garethbowen** [comment]
Spinners to test:

- creating a place
- creating a report
- loading a places children
- loading a places reports

**Comment by dianabarsan** [comment]
Ready for AT  on `5805-fix-setting-loading-content`

**Comment by newtewt** [comment]
I thought we had a loading spinner on the contact profile when loading the fields right?  Otherwise the spinners are showing and the layout looks right.

**Comment by dianabarsan** [comment]
@newtewt yea, there should be a spinner on the contact summary as well.

**Comment by garethbowen** [comment]
I've fixed the contacts profile issue and rebased to resolve the conflict. Ready for AT again.

**Comment by newtewt** [comment]
Cool looks good now!
