### ISSUE TITLE
Creating a user with a simple password using the API hangs

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5809]
**Describe the bug**

**To Reproduce**
1. Execute this command:
```
curl -d '{ "password": "secret", "username": "mary", "type": "district-manager" }' -H "Content-Type: application/json" -X POST http://admin:pass@localhost:5988/api/v1/users
```
2. Nothing happens. The request eventually times out with: `curl: (52) Empty reply from server`

**Expected behavior**
The password isn't complex enough so we should get a useful error message and code.

**Logs**
API logs:

```
2019-07-16 10:44:53 ERROR: UNHANDLED REJECTION! 
2019-07-16 10:44:53 ERROR:   Reason: { TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at ServerResponse.end (_http_outgoing.js:690:13)
    at ServerResponse.end (/home/gareth/src/medic/medic/api/node_modules/compression/index.js:107:21)
    at respond (/home/gareth/src/medic/medic/api/src/server-utils.js:33:7)
    at Object.error (/home/gareth/src/medic/medic/api/src/server-utils.js:69:5)
    at auth.check.then.then.catch.err (/home/gareth/src/medic/medic/api/src/controllers/users.js:62:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  [stack]:
   'TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object\n    at ServerResponse.end (_http_outgoing.js:690:13)\n    at ServerResponse.end (/home/gareth/src/medic/medic/api/node_modules/compression/index.js:107:21)\n    at respond (/home/gareth/src/medic/medic/api/src/server-utils.js:33:7)\n    at Object.error (/home/gareth/src/medic/medic/api/src/server-utils.js:69:5)\n    at auth.check.then.then.catch.err (/home/gareth/src/medic/medic/api/src/controllers/users.js:62:21)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
  [message]:
   'The "chunk" argument must be one of type string or Buffer. Received type object' } 
```

**Environment**
- Instance: localhost
- Browser: N/A
- Client platform: Ubuntu
- App: api
- Version: `master`

**Additional context**
This impacts all validation errors from the `/users` api and potentially some other apis too. I found this when it crashed my tests with an unhelpful message.

**Comment by garethbowen** [comment]
Ready for AT in `5809-handle-complex-error-messages`

**Comment by ngaruko** [comment]
**LGTM**
![image](https://user-images.githubusercontent.com/6979995/61496815-796f1600-aa11-11e9-8fba-329837635843.png)

**However** I think we need to trim the password @garethbowen . As it is, when the password is an empty string, the error message is `The password is too easy to guess....`
```curl -d '{ "password": "                   ", "username": "bede-5809", "type": "district-manager" }' -H "Content-Type: application/json" -X POST http://admin:pass@localhost:5988/api/v1/users
The password is too easy to guess. Include a range of types of characters to increase the score
```

And when a password contains blanks, a user still get created.
``` curl -d '{ "password": "               aps736b &*^8 : "bede-5800", "type": "district-manager" }' -H "Content-Type: application/json" -X POST http://admin:pass@localhost:5988/api/v1/users
{"user":{"id":"org.couchdb.user:bede-5800","rev":"1-f3d51792cd5ee6ff2d2235a1a3a08b01"},"user-settings":{"id":"org.couchdb.user:bede-5800","rev":"1-1e3e0d2a69326d5a1d9316a7d75113b4"}}
```

**Comment by garethbowen** [comment]
If we trim the password and it's still valid then the user will try and log in with the space at the end and it will fail. In other words, it is completely ok to have punctuation including whitespace at the end of a password and we shouldn't mess with it.

If you think it's possible to create passwords that aren't complex enough then that's another issue, but it looks like this one is working as intended.
