### ISSUE TITLE
Deleting a contact with messages causes the messages tab to error. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5812]
**Describe the bug**
Given a message is associated to a contact. When the contact is deleted and the user navigates to the messages tab. Then an error is shown. `Error fetching messages` Looking at the console there is an error trying to fetch the deleted contact id. 

```
Error fetching contact conversation Error: "Document not found: 2ffd2b25-41cf-423c-a7c1-586817f1f2fa"
    i https://gamma.dev.medicmobile.org/js/inbox.js:3
    l https://gamma.dev.medicmobile.org/js/inbox.js:3
    l https://gamma.dev.medicmobile.org/js/inbox.js:3
    $digest https://gamma.dev.medicmobile.org/js/inbox.js:3
    evalAsync https://gamma.dev.medicmobile.org/js/inbox.js:3
    completeTask https://gamma.dev.medicmobile.org/js/inbox.js:3
    r https://gamma.dev.medicmobile.org/js/inbox.js:3
```

**To Reproduce**
1. Create a message that is associated to a contact. 
2. Navigate to the contact page.
3. Delete the contact. 
4. Navigate to the messages page and see the error along with the message that is in the left hand list but does nothing when clicked on. 

**Expected behavior**
The message should be visible and no error displayed. 

**Logs**
Shown above ^^^^

**Environment**
- Instance: gamma.dev
- Browser: Chrome, firefox
- Client platform: Linux
- App: webapp
- Version: 3.6.0-beta.2

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by wtekeu** [comment]
@newtewt Shouldn't we delete the associated messages when we delete a contact?

**Comment by newtewt** [comment]
I would think the messages should remain because of history purposes but this might be a question for @abbyad

**Comment by abbyad** [comment]
@wtekeu what scenario are you thinking about where it would be beneficial to delete the associated messages? There is an open question about bulk deleting messages in https://github.com/medic/medic/issues/4112#issuecomment-516247067, which may be relevant. I would otherwise think that deleting a contact would not affect the associated messages -- those messages (and the contact's reports) would still be associated to the phone number.

**Comment by abbyad** [comment]
Looping in @derickl since he made the request to bulk delete messages.

**Comment by newtewt** [comment]
Looks good now. I can delete contacts and still see messages without error.
