### ISSUE TITLE
Loading an existing report is slower in 3.6.0

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5814]
**Describe the bug**
Loading an existing New Pregnancy report from the reports tab used to take 1 second on the fastest and 4 on the slowest. Where as now it's taking into 17 and 23 second averages on the tecno phones. 

**To Reproduce**
1. Clear app cache
2. log in to the app and replicate. 
3. Navigate to the reports tab
4. open the first new pregnancy.

**Expected behavior**
The performance should load fairly quickly. However, it seems we've slowed down a bit. 

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome, android app
- Client platform: android
- App: webapp
- Version: 3.6.0-beta.2

**Additional context**
Spreadsheet detailing the times here. 
https://docs.google.com/spreadsheets/d/13GW_gpZElcmW9AOs5r1EXwKligCDECdHVP_3aNcwqhw/edit#gid=1134415907

**Comment by kennsippell** [comment]
@newtewt Would you mind confirming if this is a regression in the first-load time only (as reported above), or if it also has impacted the not-first load times? I also got a report from @Fatoufall this morning that Muso has been complaining about performance of form load times in 3.5 (she will add specifics to this issue as they come in from Muso). But just wanting to confirm with you that there are no indications of regressions in form load times for 3.5

**Comment by dianabarsan** [comment]
@newtewt 
Do you maybe remember if, in the previous measurements, the report you were opening had scheduled tasks? 
The only thing that I can see that would account for the additional loading time is indexing an additional view (`registered_patients`), which is only indexed when loading a report when it has `scheduled_tasks`.

**Comment by dianabarsan** [comment]
I'm looking at, for example: https://gamma.dev.medicmobile.org/medic/be0b94f2-9c12-46c7-b2cd-8151dd0c6855 , which does not have a truthy `fields.patient_id` property versus https://gamma.dev.medicmobile.org/medic/99a6402c-de60-4a5b-813f-615112f1c74c which does. 

Doing an "initial load" on the 1st report takes 1 second while doing an initial load on the 2nd report takes 7 seconds (on my Nokia 7 Plus).

**Comment by newtewt** [comment]
@dianabarsan  I see the differences in speed you're referring to. I don't know the details of the report that I would have used last time. I am assuming this is likely the case. I used a report this time that would have had the patient ID.

@kennsippell  in 3.6 we started adding loading a form,  processing that form, and recording the time. I don't have a way to compare other then installing 3.5 and 3.4 and adding those times. I can do that if you'd like.

**Comment by dianabarsan** [comment]
@newtewt if it's not too much trouble, could you rerun the test on 3.5 using the same report (with patient_id and scheduled_tasks), please, to see if it's indeed a performance degradation? You wouldn't need to wipe the DB, just deploy 3.5 on top.

**Comment by newtewt** [comment]
@dianabarsan  These are the 3.5 numbers. Definitely looks like the difference is that patient id. The times are similar between the versions with the patient ids. 

21s57 -Tecno J5 With patient id
19s40 - with patient id
17s33 - with patient id
3s28 - without
3s52 - without 
3s25 - without


25s86 - Tecno WX3 with patient id
24s54 - with patient id
23s48 - with patient id
3s93 -  without
4s18 - without
4s14 - without

**Comment by dianabarsan** [comment]
So do you think we can close this since it's not actually a performance degradation ?

**Comment by newtewt** [comment]
Yeah I agree with that. I think a new issue for loading forms may come from @kennsippell
