### ISSUE TITLE
If an outbound task fails in mapping it causes all other tasks to fail

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5826]
Currently if one outbound task fails in mapping it causes all others to fail. This definitely shouldn't happen, but somewhere in refactoring it got lost.

Add a test and make sure.

**Comment by dianabarsan** [comment]
Ready for AT on `5825-outbound-delete-support`.

**Comment by newtewt** [comment]
Here's what I'm seeing.

**Comment by newtewt** [comment]
@SCdF  Here's what I'm seeing. 

I have created a few(10 or so) reports that have met the outbound relevantTo criteria. In my case I'm checking that the form is a pregnancy.
I am looking at fauxton while this is happening and running the mango query below to see if there are outbound tasks created.
Sentinel processes the outbound tasks and clears them. My query is shown empty.
Then I process another pregnancy.
Run the mango query and see two tasks created in the sentinel db. One is for my new report and the other is for a previous report. Sometimes it is the previously submitted report and other times it's a random one from before. 
Sentinel processes and on my simple express server I see two post calls. 




 ```
 {
   "selector": {
      "type": "task:outbound"
   }
}
```

**Comment by SCdF** [comment]
@newtewt since you've merged the PR and this is a different topic we might want to raise a separate ticket?

Anyway, can you do this again but get the sentinel logs? Specifically want I want to try to work out is: are the tasks getting resurrected somehow (the code is wrong), or are the reports being written to somehow and the tasks are being recreated (the code is right but our assumptions are wrong)

**Comment by newtewt** [comment]
@SCdF  yeah I will do that and log a separate ticket. I didn't realize there were two issues associated to one branch and merged after finishing the other ticket.
