### ISSUE TITLE
Reintroduce styling for `weeksPregnant` filter

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5840]
**Describe the bug**
The weeksPregnant filter outputs the number of weeks the patient has been pregnant. It's also supposed to add styling if the patient is near full term or if the edd is approximate.

**To Reproduce**
1. Configure a contact summary to include a field with the `weeksPregnant` filter, eg:
```json
...
        {
          "label": "weeks pregnant",
          "value": { "number": 38, "approximate": true },
          "width": 6,
          "filter": "weeksPregnant"
        },
...
```
2. Load a patient
3. Notice that the contact summary weeks pregnant field is unstyled.

**Expected behavior**
If the number of weeks is greater than or equal to 37 the text colour is green.
If the date is approximate the number has a "~" prefix.

**Screenshots**
![Screenshot from 2019-07-26 15-07-53](https://user-images.githubusercontent.com/2064938/61941437-31bf3000-afb7-11e9-97e4-d01ab2fad01c.png)

**Environment**
- Instance: localhost
- Browser: All
- Client platform: Ubuntu
- App: webapp
- Version: master

**Additional context**
This was added in https://github.com/medic/medic/commit/6746ee16b583c3878d2159cde0a18b84ac59e0e9 . The classes are still being added but the CSS has been removed at some point.

**Comment by garethbowen** [comment]
Ready for AT on `5840-styling-for-weeks-pregnant`

**Comment by newtewt** [comment]
Seeing the expected styling for weeks pregnant.
