### ISSUE TITLE
Access logging outputs the load balancer IP in production

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5845]
**To Reproduce**
1. Run this against any production instance and ignore the failure:
`curl -X POST https://<user>:<pass>@<instance>/api/v1/sms/africastalking/delivery-reports`
2. Look at the access logs for that instance
3. Find your request(s)
4. See that the IP doesn't match the IP address of the client (your machine)

**Expected behavior**
The logged IP address should match your client address.

**Logs**
```
Jul 28 11:15:58 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:15:57] REQ 492b5625-c7a1-4eba-923d-10cab3cc998b ::ffff:100.120.0.0 - POST /api/v1/sms/africastalking/delivery-reports HTTP/1.1
Jul 28 11:15:58 dev-test-cdc-mohke-dsru dev-test-cdc-mohke-dsru-medic-api-logs:  (dev-test-cdc-mohke-dsru-6bb57f6458-gdqrw) | [2019-07-28 08:15:57] RES 492b5625-c7a1-4eba-923d-10cab3cc998b ::ffff:100.120.0.0 - POST /api/v1/sms/africastalking/delivery-reports HTTP/1.1 403 - 2.310 ms
```

The important bit is the `100.120.0.0` on both of these lines.

**Environment**
- Instance: any production instance
- Browser: N/A
- Client platform: N/A
- App: api
- Version: master

**Comment by garethbowen** [comment]
According to [this issue](https://github.com/expressjs/morgan/issues/2) we just need to turn on [`trust proxy` in expressjs](http://expressjs.com/en/4x/api.html#app.settings.table). Make sure it's safe to trust proxy and then enable it and verify that the correct IP is logged.

**Comment by garethbowen** [comment]
Based on [this guide](https://expressjs.com/en/guide/behind-proxies.html) I consider it safe. Ideally we'd restrict the setting to just the IP of the load balancer but I don't trust that that won't change, so I've kept it wide open. This will only be an issue if someone finds a hole in our infrastructure so I'm willing to accept it for now.

**Comment by garethbowen** [comment]
Ready for AT in `5845-fix-access-log-ip`.

One of the builds failed for an unrelated reason but the build that publishes the app for testing passed so you're good to go.

**Comment by newtewt** [comment]
I'm seeing my internet IP being logged in medic-api logs when accessing gamma.dev.  @garethbowen  the build is broken so I cannot squash and merge.
