### ISSUE TITLE
Settings shared-lib throws an error if the credential is an empty string

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5847]
**To Reproduce**
1. Set up Africa's Talking but set the incoming api key to an empty string
2. Use the AT sandbox to send a message to your server
3. View the error in the logs

**Expected behavior**
There should be a warning about the api key not matching which is gracefully handled rather than an uncaught server error as below.

**Logs**
```
ERROR: Server error: { TypeError: Cannot read property '1' of null
    at parseResponse (/home/diana/projects/medic/shared-libs/settings/src/index.js:7:69)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  [stack]:
   "TypeError: Cannot read property '1' of null\n    at parseResponse (/home/diana/projects/medic/shared-libs/settings/src/index.js:7:69)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)",
  [message]: "Cannot read property '1' of null" } 
```

**Environment**
- Instance: localhost
- Browser: N/A
- Client platform: N/A
- App: @medic/settings
- Version: 3.6.0

**Comment by dianabarsan** [comment]
Ready for AT on `5847-handle-empty-credential`

**Comment by newtewt** [comment]
Looks good. No longer seeing a poor error and seeing the nice error.
