### ISSUE TITLE
Refreshing the tasks page after selecting a task does not load a task correctly

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5855]
**Describe the bug**
After selecting a task then refreshing will show an improperly formatted task. 

**To Reproduce**
1. Navigate to tasks page as an offline user
2. Select a task
3. Refresh the page. 
4. The page is formatted incorrectly.

**Expected behavior**
The task page shows correctly. 

**Logs**
No console logs

**Screenshots**
Poorly formatted
![image](https://user-images.githubusercontent.com/10531066/62233523-c1d5ee80-b396-11e9-8ac7-dbdd9e666088.png)
Correct format
![image](https://user-images.githubusercontent.com/10531066/62233544-cb5f5680-b396-11e9-892a-ad2153ad0e81.png)

**Environment**
- Instance: gamma.dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: 3.6.1

**Additional context**
Selecting another task or navigating from the current tab and back to tasks you can get the proper formatting.

**Comment by garethbowen** [comment]
That page shown on reload is designed to be shown if the task has a detailed description or if there is more than one possible action to take. This feature is seldom used but we should fix the styling of that page as well as making sure the form is loaded in this case.

**Comment by garethbowen** [comment]
Ready for AT on `5855-refresh-tasks-page`

**Comment by newtewt** [comment]
@garethbowen  when I click on a task now it attempts to load the form. However, the spinner just sits and never goes away. 


I'm on gamma.dev logged in as user ac1

**Comment by garethbowen** [comment]
Found it. That forever loading bug also exists in `master` but I've fixed it in this branch rather than creating a separate issue. Ready for AT again.

**Comment by newtewt** [comment]
:+1:  can refresh and see the task now. Also still able to process the form that's loaded.
