### ISSUE TITLE
Lazy load unread count to reduce visible load time

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5859]
During our bootstrap process, we spend a lot of time building six mapreduce indexes. Two of these are indexes used by `webapp/src/js/services/unread-records.js`: 

* `medic-client/data_records_by_type` is used to count the total number of reports and the number of messages
* `medic-user/read` is used to count the number of reports read by the logged in user

This count yields a red bubble over the tab. 

![Screenshot from 2019-08-01 00-38-00](https://user-images.githubusercontent.com/9014751/62274498-d9dc5b00-b3f4-11e9-8d7b-9749e7262090.png)

This decorative data isn't required before first render. Although we don't explicitly wait for it to complete before first render, it likely slows down startup performance by competing for resources in parallel with our critical path (building the other four indexes). 

This seems like an excellent candidate for lazy loading after the bootstrapping is completed.

**Comment by garethbowen** [comment]
Ready for AT in `5859-delay-startup-tasks`

**Comment by newtewt** [comment]
Looks good seeing the reports count load in late and the reports are still showing as expected.

**Comment by kennsippell** [comment]
Just a comment that it would be excellent if we got into the practice of measuring the performance impacts of changes which we make for performance reasons.
