### ISSUE TITLE
Add person icon is not monochrome

### ISSUE THREAD

**Issue by abbyad** [medic/medic#5877]
**Describe the bug**
The white monochrome icon for new person has a pink head.
![image](https://user-images.githubusercontent.com/789512/62645185-aed49880-b919-11e9-864f-d0d67600aedf.png)

**To Reproduce**
1. Go to People tab
2. Click on a place
3. In RHS see the add person icon in the FAB has a head the same color as the People tab.

**Expected behavior**
The icons used in the FAB are meant to be monochrome white.

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/62644185-8cda1680-b917-11e9-8349-15cdeea2a52a.png)

**Environment**
- Instance: gamma.dev running 3.6, cht.app running 3.4.0
- Browser: Chrome 75 on Windows 10, and also seen on Mac
- Version: tested on versions 3.4.0 and 3.6.0

**Comment by garethbowen** [comment]
Ready for AT on `5877-fill-icon-head`

**Comment by newtewt** [comment]
Looks good on mobile and web versions.

**Comment by jacqedwards** [comment]
Super excited that our person icon will have a head that matches their body! :)
