### ISSUE TITLE
Search for places in add user does not return custom_type persons.

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5888]
**Describe the bug**
When trying to search for associated contact in create users the view for ddocs/medic-client/views/contacts_by_type_freetext/map.js is emitting by `doc.type` and when we send the key to that view we are sending what's defined in contact_types. So either people(custom) or person in my case (watching the network calls in chrome). When I look at that view the custom types have a key of ["contact","people1"] so it never returns.

Tagging @garethbowen  as he did the original work on config place hierarchies so might know a quick win. 

The line where I think the problem is.

medic/ddocs/medic-client/views/contacts_by_type_freetext/map.js
```
Line 10 in 5fdb97c

 emit([doc.type, key], value); 
```
**To Reproduce**
1. Add a custom contact_type called people to your contact_types and make sure `"person": true`
2. Add a new contact of the custom type people
2. Log in as admin and go to add user page
2. TRy to associate the new contact created to the user. Nothing is returned in the box. 

**Expected behavior**
Any contact that is deemed a person should be available I would assume. 

**Environment**
- Instance: localhost
- Browser: chrome
- Client platform: Linux
- App: webapp
- Version: 3.7.0

**Comment by dianabarsan** [comment]
Ready for AT on `5888-configurable-hierarchy-search`

**Comment by newtewt** [comment]
Looks good. Checked the other searches that I could find as well and returning both the standard and custom types.
