### ISSUE TITLE
The "New action" popup dialog is partially invisible and in wrong location on narrow screens

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5892]
**To Reproduce**
1. Navigate to a person on desktop
1. Click "New action" dialog
1. You should see healthy dialog

**Working wider screen widths**
![Screenshot from 2019-08-13 22-34-45](https://user-images.githubusercontent.com/9014751/62996755-a0efad80-be1a-11e9-83ff-b1c365ebdc99.png)

**Broken on narrow screen widths**
![Screenshot from 2019-08-13 22-34-53](https://user-images.githubusercontent.com/9014751/62996753-9fbe8080-be1a-11e9-91af-800509df8b0c.png)

Note that horizontal grey bar at top of this screenshot is the border of the "new action" bar which appears/disappears when clicking the "New action" bar

**Comment by garethbowen** [comment]
Possibly a regression of #4655

**Comment by garethbowen** [comment]
Ready for AT in `5892-dropups-hidden-on-phones`

**Comment by newtewt** [comment]
Looking good on phones and squished browsers.
