### ISSUE TITLE
Report place filter doesn't load

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5894]
**Describe the bug**
Trying to filter reports by place gives a permanent spinner.

**To Reproduce**
1. Go to the Reports tab
2. Click on the place filter dropdown menu
3. The spinner never stops spinning

**Expected behavior**
The menu should load available places.

**Logs**
In the browser console:
```
Error loading facilities TypeError: listener is not a function
    at place-hierarchy.js:122
    at processQueue (angular.js:17914)
    at angular.js:17962
    at Scope.$digest (angular.js:19075)
    at Scope.$apply (angular.js:19463)
    at HTMLSpanElement.<anonymous> (angular.js:28819)
    at HTMLSpanElement.dispatch (jquery.js:5206)
    at HTMLSpanElement.<anonymous> (jquery.js:5014)
```

**Screenshots**
![Screenshot from 2019-08-14 05-38-47](https://user-images.githubusercontent.com/2064938/63011203-f0e27900-bedb-11e9-9276-e07d01a9d58b.png)

**Environment**
- Instance: local
- Browser: Chrome
- Client platform: ubuntu
- App: webapp
- Version: master (3.7.0)

**Comment by garethbowen** [comment]
Caused by a combination of #4423 and #3639

**Comment by SCdF** [comment]
In `5894-fix-place-hierarchy-service`. AT: report search filters should work as expected.

**Comment by newtewt** [comment]
Seeing the places load appropriately in the filter. Selecting works appropriately as well.
