### ISSUE TITLE
Reports without a patient_id don't get synced if the patient is moved to a new place

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5897]
**Describe the bug**
Reports without a patient_id don't get synced if the patient is moved to a new place

**To Reproduce**
1. Create offline `user-A` associated with person `CHW-a` which is a child of place `clinic-A`
1. Create offline `user-B` associated with person `CHW-b` which is a child of place `clinic-B`
1. Login as `user-A`
1. Go offline
1. Create new person `patient-1` (under `clinic-A`)
1. Register a pregnancy `report-1`
1. Go online. Sync twice to see Patient_ID on `patient-1`
1. Move `patient-1` to have parent `clinic-B` via `medic-conf --local move-contact -- --contact=patient-1-id --parent=clinic-B-id`
1. Login as `user-B` (clear site data before, since you may not be able to sync this change. You have to resync everything).
1. Sync

**Expected behavior**
`user-B` can see `patient-1` and `report-1`

**Observed behavior**
`user-B` sees `patient-1` but not `report-1`

**Environment**
- Instance: all
- Browser: all
- Client platform: all
- App: webapp
- Version: master

**Comment by kennsippell** [comment]
I've opened this as a `webapp` issue because I'm unsure if we should handle this in sentinel or just in the `move-contacts` action?

**Comment by kennsippell** [comment]
This has been fixed by @dianabarsan via https://github.com/medic/medic/pull/5878/files#diff-25c925dfdca170ec1f25eaed06f70ab3R32.

**Comment by kennsippell** [comment]
@dianabarsan, I'll let you decide if you just want to close this. Or if you'd like to move it to AT when #5443 is ready.

**Comment by dianabarsan** [comment]
This issue should be fixed in `5443-server-side-purge`.

**Comment by newtewt** [comment]
Looks good to me. I'm seeing the reports move when the patient_id isn't filled.
