### ISSUE TITLE
Need to update organization and /medic repo description

### ISSUE THREAD

**Issue by CescaGarrett** [medic/medic#5898]
The below changes are blessed by Marc, I just don't have the access needed to make them!

On the [main organization page](https://github.com/medic), I'd like to replace:

`Software toolkit combining smart messaging, decision support, easy data gathering and management, and health system analytics. Start with the medic repo.`

With: 

`We design, deliver, and support world-class open source software for health workers providing care in the hardest-to-reach communities.`

/medic I'd like to replace: 

`This is the core repo for Medic Mobile's community health application framework, which you can use to build responsive, offline-first community health apps. The framework is highly configurable, with support for interactive messaging, decision support, task management, health records, data collection, and analytics. http://medicmobile.org/tools`

With: 

`Medic Mobile's Core Framework makes it faster to build responsive, offline-first  digital health apps that equip health workers to provide better care in their communities. It is a central resource of the Community Health Toolkit.`

**Comment by garethbowen** [comment]
Done.
