### ISSUE TITLE
Task list in places view doesn't include the tasks of children

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5899]
**Describe the bug**
The list of tasks on the "place" page doesn't include tasks for the place's descendants.

Found here: https://github.com/medic/medic-conf/issues/205#issuecomment-522690663

**To Reproduce**
1. Deploy standard config (configurable hierarchy)
1. Create offline user which is associated to a place
1, Make some tasks appear for contacts. Maybe use the `tasks.js` contact below?
1. Navigate to the contacts tab and select the place.

**Expected behavior** - Should see all tasks for the area and descendants
**Observed behavior** - Only the tasks for the area

**Environment**
- Instance: dev
- Browser: Chrome
- Client platform: Linux
- App: webapp
- Version: master

**Additional context**
This is an easy way to make lots of tasks trigger for contacts:
```
module.exports = [
  {
    name: 'task',
    title: 'foo',
    actions: [{ form: 'example' }],
    events: [{ days: 10, start: 100, end: 1 }],
    appliesTo: 'contacts',
    appliesIf: function() {
      return true;
    },
    resolvedIf: function() {
      return false;
    }
  }
];
```

**Comment by garethbowen** [comment]
Ready for AT in `5899-tasks-on-places`

**Comment by newtewt** [comment]
:+1:  I'm seeing all the tasks associated to the descendants when viewing the tasks on the area.
