### ISSUE TITLE
Create new repo /cht-docs

### ISSUE THREAD

**Issue by CescaGarrett** [medic/medic#5913]
(Request blessed by Marc)

We want to create a new repo to house the finalized and CHT aligned documentation that will make up the new documentation site. I'll create the ReadMe + Contribute + Code of Conduct pages etc. For now, I just need the repo itself, please! ✨ 

Repo description: `Documentation for developing, configuring, and using Reference Applications and the Core Framework of the Community Health Toolkit.`

**Comment by CescaGarrett** [comment]
@abbyad are you able to create this for me?

**Comment by abbyad** [comment]
Yes, doing it today.

**Comment by abbyad** [comment]
It is now created, and private until ready to share more widely.

**Comment by abbyad** [comment]
Including details here for posterity:

Repo is [medic/medic.github.io](https://github.com/medic/medic.github.io), as per [pages.github.com](https://pages.github.com).

![image](https://user-images.githubusercontent.com/789512/64204366-a2355880-ce63-11e9-8c41-10478321df0d.png)
