### ISSUE TITLE
Improve infodoc replication timestamp accuracy

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5919]
Currently infodoc replication dates are generated or updated when sentinel hits the document. This isn't ideal for a few reasons:
 - If sentinel is down, disabled or simply behind in processing the dates won't be accurate 
 - If older docs that existed before infodocs gets updated sentinel can't tell if it's a new doc or an edit to an existing doc (and so what to set the initial replication date to)

**Comment by SCdF** [comment]
See this PR: https://github.com/medic/medic/pull/5822

AT:
 - Infodocs should still be created and updated as you'd expect.
 - Updating timestamps no longer require sentinel to be running
 - `initial_replication_date` should be set to now when a new document is written to through API (as any user)
 - `initial_replication_date` should be set to `unknown` if an existing document is written to through API (as any user) and no infodoc existed
 - In either above case `latest_replication_date` should be set to now, 
 - If a document doesn't have a infodoc and sentinel hits the document (you can simulate this by writing a new document directly to CouchDB) the initial replication date will be "unknown" (because we don't know when it was written)

For developers: this PR also allows you to run E2E tests where you need to manipulate the running state of api and sentinel. This lets you do things like setup the DB just right without sentinel reading what's going on and making modifications before you're ready for it to, or to test api and sentinel startup. For an example search for the "legacy data support" infodoc e2e tests.

**Comment by newtewt** [comment]
I'm seeing the info doc without sentinel running and the dates updating as expected. I'll recheck once the conflicts are resolved.

**Comment by newtewt** [comment]
Looks good after the rebase!
