### ISSUE TITLE
Theme page content does not scroll

### ISSUE THREAD

**Issue by abbyad** [medic/medic#5920]
Cannot fully view the contents of the Theme page since there is no way to scroll using mouse, keyboard, or scrollbar.

**To Reproduce**
1. Go to the [Theme page](https://gamma.dev.medicmobile.org/#/theme)
1. Try to scroll down
1. See that you can't view content below the fold

**Expected behavior**
I would expect to be able to scroll down the page to see the content of the theme page.

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/64196458-eb7cac80-ce51-11e9-9993-a24e1fb6e3d6.png)

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Chrome 76
- Client platform: Windows
- App: webapp
- Version: 3.6.0

**Comment by garethbowen** [comment]
Ready for AT in `5920-theme-page-scrolling`

**Comment by ngaruko** [comment]
LGTM.
The scrolling works. I will close this one. @abbyad feel free to have a look at the styling and the functionality and maybe raise a different issue if necessary - One thing I noticed is that when one clicks on the `Profile` tab the browser goes to `Messages` instead.
![image](https://user-images.githubusercontent.com/6979995/64316245-5f60b580-d008-11e9-935a-49180fed74aa.png)
