### ISSUE TITLE
Android App cannot load app on initial replication

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5931]
**Describe the bug**
When trying to log in for the first time in the app it fails with "Loading error, please check your connection."

**To Reproduce**
1. Using master
2. Clear app cache
3. try to log in

**Expected behavior**
User replicates and gets logged in to the app. 

**Logs**
Console error shows. 

```
inbox.js:3 Error bootstrapping SyntaxError: Unexpected token < in JSON at position 0(anonymous function) @ inbox.js:3(anonymous function) @ inbox.js:3
```

**Environment**
- Instance: gamma.dev or localhost
- Browser: App
- Client platform: Android
- App: Webapp
- Version: 3.7 / master

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by dianabarsan** [comment]
Ready for AT on `5931-same-origin-requests`

**Comment by newtewt** [comment]
Looks good now. I can use the app on phones and browsers.
