### ISSUE TITLE
Report review dropup styling is broken

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5933]
**Describe the bug**

![image](https://user-images.githubusercontent.com/35681649/64371147-90e97900-d028-11e9-945e-18ee6737b2e0.png)

Instead of:

![image](https://user-images.githubusercontent.com/35681649/64371209-b37b9200-d028-11e9-85d1-03c3b90502dd.png)

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Firefox, Chrome, Chromium
- App: webapp
- Version: 3.7

**Comment by dianabarsan** [comment]
Ready for AT on `5933-verification-styling`.

**Comment by newtewt** [comment]
Looks good to me.
