### ISSUE TITLE
Telemetry data are not saved under the right month

### ISSUE THREAD

**Issue by senseibara** [medic/medic#5949]
**To Reproduce**
Steps to reproduce the behavior ( example on muso ) :
1. Go to https://muso-mali.app.medicmobile.org/_utils/#database/medic-users-meta/_all_docs
2. Search telemetry and click on any result 
3. Telemetry docs of august will start like telemetry-2019-7 instead of telemetry-2019-8, metadata month is also set to 7.

**Expected behavior**
The month should be 8 instead of 7.

**Comment by wtekeu** [comment]
Ready for AT `5949-fix-telemetry-month`

**Comment by ngaruko** [comment]
LGTM
![image](https://user-images.githubusercontent.com/6979995/66813163-c58a1200-ef90-11e9-9160-f72a9fa02cf7.png)

**Comment by garethbowen** [comment]
@ngaruko What month are those docs for? Did you roll your system clock forward to December?
