### ISSUE TITLE
Reports page's filter reset button gets cut off on Tecno Y4

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5951]
![image](https://user-images.githubusercontent.com/583851/64976542-6fe71a80-d8a9-11e9-8c1e-5dd2ea204ea5.png)

I can't remember if we used to hide these various filters on phones (and like contact only have free text search), but it's not happening now and it's not clear what permission I'd change to make that happen.

If we're supposed to display all of the filters we should either tighten everything up so it fits on the Y4 or drop it as a supported phone (ie set a minimum horizontal resolution that excludes this phone)

**Comment by garethbowen** [comment]
Ready for AT in `5951-adjust-filter-width`

**Comment by newtewt** [comment]
Looks good on Tecno Wx3, J5, and smaller desktop views.
