### ISSUE TITLE
Error when loading reports as an offline user

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#5959]
**Describe the bug**
Offline users cannot Load reports and have no actions available the in the contact profile.

**To Reproduce**
1. Login as an offline user that is not a district level (so they don't have a complete lineage available)
2. Go to reports.
3. The reports page is stuck loading and there are errors in the console:
`Error fetching relevant forms SyntaxError: Unexpected token u in JSON at position 0`

**Expected behavior**
Reports page should load. Available forms should be desplayed.

**Logs**
```
angular.js:15567 Error fetching relevant forms SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at deepCopy (lineage-model-generator.js:66)
    at lineage-model-generator.js:68
    at processQueue (angular.js:17945)
    at angular.js:17993
    at Scope.$digest (angular.js:19112)
    at angular.js:19432
    at TaskTracker.completeTask (angular.js:21231)
    at angular.js:6812
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35681649/65255611-dfa61100-db06-11e9-855b-5a6ecfb42964.png)

**Environment**
- Instance: local
- Browser: Chrome
- App: webapp
- Version: 3.7.0 (master)

**Comment by dianabarsan** [comment]
Ready for AT on `5959-fix-lineage`

**Comment by ngaruko** [comment]
LGTM
**Before**.. 
![image](https://user-images.githubusercontent.com/6979995/65400917-0de26400-de19-11e9-8013-8a2a08e2de2b.png)
**After**
![image](https://user-images.githubusercontent.com/6979995/65400950-32d6d700-de19-11e9-9a38-b095e10d957c.png)
