### ISSUE TITLE
API sometimes generates an empty model.xml and form.html

### ISSUE THREAD

**Issue by SCdF** [medic/medic#5961]
```
1) Add new health center tests :  should add new health center

  - TimeoutError: Wait timed out after 15025ms

  - Failed: Wait timed out after 10013ms

2) Add new person tests :  should add new person

  - TimeoutError: Wait timed out after 15006ms

  - Failed: Wait timed out after 10001ms

3) Creating contacts with standard config should create a new district hospital

  - TimeoutError: Wait timed out after 15014ms
```

I see variations of these ones a lot. I have seen 1) locally before as well (but didn't look at it at the time) but haven't been able to reproduce the others.

**Comment by SCdF** [comment]
(cc. @dianabarsan again not sure if you were looking at these either)

**Comment by dianabarsan** [comment]
I managed to replicate one of these locally - the should add new person  -  and this is what I have: 

![add_new_person_tests_should_add_new_person](https://user-images.githubusercontent.com/35681649/65262148-5b598b00-db12-11e9-8a89-632f09a3293c.png)

The browser logs:

```
[SEVERE] http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9 52976:40 
"Error loading contact form." 
TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.
    at http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:197610:38
    at processQueue (http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:55355:37)
    at http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:55403:27
    at Scope.$digest (http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:56522:15)
    at http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:56842:26
    at TaskTracker.completeTask (http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:58641:7)
    at http://localhost:4988/js/inbox.js?_sw-precache=5fadeff6dda2f93c0add9346dc9633d9:44222:19
```

No errors in API log. According to the logs, the form XML was generated correctly:
```
2019-09-19 16:10:41 [34mDEBUG[39m: Generating html and xml model for enketo form "form:contact:person:create" 
```
But looking at the actual doc in the DB, the `model.xml` attachement is empty (shown with length:0 below):

![image](https://user-images.githubusercontent.com/35681649/65262619-6bbe3580-db13-11e9-97c2-226e83d59130.png)

So these could end up being legit fails?

**Comment by dianabarsan** [comment]
In the same session, `add new health center` also failed, same error in the browser console, same length 0 `mode.xml` attachment:

![image](https://user-images.githubusercontent.com/35681649/65262977-29492880-db14-11e9-8742-216b71abdf01.png)

**Comment by dianabarsan** [comment]
Ok, I think I see a pattern. Both of these forms has been generated more than once. 
The 1st iteration has correct attachments: (rev = 2)

![image](https://user-images.githubusercontent.com/35681649/65263263-e76cb200-db14-11e9-996a-4540707ff820.png)

But on next edit (rev 3), both form html and model xml are empty:

![image](https://user-images.githubusercontent.com/35681649/65263310-05d2ad80-db15-11e9-9b72-f2675e6bc088.png)

**Comment by dianabarsan** [comment]
Since these tests fail quite consistently,  I have more information. 
It appears that the actual `xsltproc` result is empty.
https://github.com/medic/medic/blob/master/api/src/services/generate-xform.js#L36 
The `formXml` we provide looks correct. `stderr` is also empty. 

@garethbowen have you seen anything like this?

**Comment by garethbowen** [comment]
No that's new to me. It's possible the process is terminating due to a signal which we're not logging: https://nodejs.org/api/child_process.html#child_process_event_exit

We should probably also fail if the stdout is empty.

**Comment by garethbowen** [comment]
Changing to a bug because I think this would also affect an actual deployment under load.

**Comment by dianabarsan** [comment]
Ready for AT on `5961-listen-for-xsltproc-close`. 
Not sure how to properly AT this. What happens during tests and exposed this bug is that the forms were uploaded in bulk immediately after API startup (https://github.com/medic/medic/blob/master/tests/conf.js#L125). 
The difference, maybe, compared to a regular startup, where forms are already present, is that instead of updating them in sequence, they were updated as soon as the change listener fired (so likely at the same time). Unsure if doing an `upload-app-forms` via `medic-conf` would have triggered the same behavior - as those are uploaded sequentially.

**Comment by newtewt** [comment]
I've checked that all the create and edits work appropriately with the change. Due to the other known issue I cannot check that app forms work. My feeling is to hold this open until the other issue is fixed and then get it rebased to confirm.

**Comment by garethbowen** [comment]
This issue is making it hard for anything else to get merged because it fails lots of tests. I'm going to make the executive decision to merge it now only partially ATed to unblock development.
