### ISSUE TITLE
The icon in condition cards is displaying too large

### ISSUE THREAD

**Issue by binokaryg** [medic/medic#5963]
**Describe the bug**
The icon in condition cards is displaying too large - should be constrained to 30 x 30 px.
The size of the icon being displayed is the same size that we uploaded (60 x 61 px), but we should fix the code in the condition cards so that all icons uploaded to a condition card are constrained to display at 30x30.

**Screenshots**
![image](https://user-images.githubusercontent.com/20041732/65271229-76d98b80-db3c-11e9-943e-cb4ab603d2f0.png)

![image](https://user-images.githubusercontent.com/20041732/65271199-66291580-db3c-11e9-8b02-233a9f59604d.png)

**Environment**
- Instance: cht.app.medicmobile.org
- Browser: Chrome
- App: webapp
- Version: 3.6.1

**Additional context**
This issue was raised by @amandacilek during the testing of CHT reference app.

**Related issues**
#3719, #3720

**Comment by wtekeu** [comment]
Ready for AT `5963-icon-too-large`

**Comment by ngaruko** [comment]
LGTM ...
**_Master_**
![image](https://user-images.githubusercontent.com/6979995/66972243-7f4bc480-f0f0-11e9-88bd-359bded0437b.png)

**_Branch_**
![image](https://user-images.githubusercontent.com/6979995/66972377-f2edd180-f0f0-11e9-9861-ea31116dbecc.png)
