### ISSUE TITLE
Wrap text in contact summary and condition cards

### ISSUE THREAD

**Issue by binokaryg** [medic/medic#5967]
**Describe the bug**
If a field in a contact summary or condition card is too long and does not has whitespace, it flows over and does not look good.

**To Reproduce**
1. Go to a contact profile
2. Edit the profile and add very long notes without spaces in between
3. Save the profile
4. See the problem

**Expected behavior**
The text should wrap nicely as it does in the forms.

**Screenshots**
Contact Summary and Condition Card:
![image](https://user-images.githubusercontent.com/20041732/65301661-24c65380-db98-11e9-99ff-f1126ea83e1d.png)

Form Summary:
![image](https://user-images.githubusercontent.com/20041732/65301589-f183c480-db97-11e9-9616-f39a9cf99bfc.png)

**Environment**
- Instance: cht.app.medicmobile.org
- Browser: Chrome
- Client platform: Windows
- App: webapp
- Version: 3.6.1

**Comment by wtekeu** [comment]
Ready for AT `5967-wrap-text-in-contact-summary`

**Comment by ngaruko** [comment]
LGTM
**Before (`Master`)**
![image](https://user-images.githubusercontent.com/6979995/66883449-798bab80-f02a-11e9-81a1-5210ece51a6e.png)

**After (`branch`)**
![image](https://user-images.githubusercontent.com/6979995/66883483-9cb65b00-f02a-11e9-82c2-a2bea77449d1.png)
