### ISSUE TITLE
CHT Reference App's delivery form causes "Invalid XML" in latest master

### ISSUE THREAD

**Issue by kennsippell** [medic/medic#5971]
**Describe the bug**
The `delivery` form from the CHT-Reference-App loads in v3.6.1, but not cannot load in v3.7. Console shows error "Invalid XML"

**To Reproduce**
1. Deploy the latest CHT Reference App to 3.6.1 (#5914) ([delivery.xml](https://raw.githubusercontent.com/medic/medic/279c910a329e8ea4da53f1127768ea3db421a0a8/config/default/forms/app/delivery.xml))
1. Create a new female patient contact 
1. Navigate to the contact's page and click "new report > delivery"
1. The form loads and all is well
1. Upgrade to 3.7
1. Navigate to the contact's page and click "new report > delivery"

**Expected behavior**
The form should still load

**Logs**
User sees: "Error loading form. Please try again or check with an administrator."

Console shows:
```
Error loading form Error: Invalid XML: 
  <model>
    <instance>
        <delivery xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" delimiter="#" id="delivery" prefix="J1!delivery!" version="2019-09-04 07:45:50">
          <inputs>
            <meta>
              <location>
                <lat/>
                <long/>
                <error/>
                <message/>
              </location>
            </meta>
            <source>user</source>
            <source_id/>
            <user>
              <contact_id/>
              <name/>
              <phone/>
            </user>
            <contact>
              <_id/>
              <name/>
              <short_name/>
              <patient_id/>
              <date_of_birth>0</date_of_birth>
              <sex/>
...
```

**Screenshots**

**Environment**
- Instance: devmachine running latest master
- Browser: Chrome
- Client platform: Ubuntu
- App: webapp
- Version: master

**Additional Notes**
I don't think you need to upgrade to reproduce the bug, the repro steps just validate that this is (was?)  a valid form xml.

**Comment by garethbowen** [comment]
Possibly caused by this: #5961

**Comment by garethbowen** [comment]
I've reproduced this error on `master` so it's a different bug. The xml attached to the doc looks like...

```xml
  <model>
    <instance>
...
      </instance>
  </model>
</root>
```

So it's invalid because of the trailing `</root>`. Looking into it now.

**Comment by garethbowen** [comment]
Ready for AT in `5971-allow-nested-root-nodes`

**Comment by ngaruko** [comment]
LGTM
