### ISSUE TITLE
Guided Tour does not show control buttons

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#5973]
**Describe the bug**
There are no control buttons (previous, next, end tour). 
**To Reproduce**
1. Go to Menu >> 
2. Click on 'Guided Tour'
3. Pick any option

**Observed behavior**

There are no control buttons (previous, next, end tour). No way to move between tabs or to exit the tour. 

**Expected behavior**
The dialog box should show  3 buttons (`previous`, `next`, `end tour`).

**Logs**
No errors in console.

**Screenshots**

![image](https://user-images.githubusercontent.com/6979995/65402203-12127f80-de21-11e9-9489-c5688ca7110a.png)

**Environment**
- Instance: local
- Browser: Firefox, Chrome
- Client platform:  MacOS
- App:  webapp, admin
- Version: 3.6.*

**Comment by garethbowen** [comment]
Looks like a known issue: https://github.com/sorich87/bootstrap-tour/issues/723

**Comment by garethbowen** [comment]
It looks like the library is abandoned. I've made a quick fix (suggested in the issue linked above) but we should consider migrating to a different library at some point.

**Comment by SCdF** [comment]
PR in: `5884-dont-overwrite-forms-2`

AT: tour should have next / previous buttons and they should work!

**Comment by newtewt** [comment]
Tour is working again on desktop and mobile.
