### ISSUE TITLE
Language select modal Submit button never enabled

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5978]
**Describe the bug**

The Submit button of the language select modal is never enabled.

**To Reproduce**

1. Create a brand new user. It's important that they haven't logged in before or you won't see the language dialog.
2. Log in as the new user.
3. See the Submit button is disabled, and no matter what you do it won't enable.

**Expected behavior**

The default language should be selected, and the button should be enabled. You should not be able to deselect the language. If you switch to another language the button stays enabled.

**Screenshots**
![Screenshot from 2019-09-24 09-54-14](https://user-images.githubusercontent.com/2064938/65465812-4afa3500-deb1-11e9-9df5-1599384746f5.png)

**Environment**
- Instance: localhost
- Browser: Chromium
- Client platform: Ubuntu
- App: webapp
- Version: master

**Comment by garethbowen** [comment]
This was caused by this change: https://github.com/medic/medic/commit/d9ae1aaedd454e95fbd081b474e4d9a866b3e88d#diff-a4686eb7ba73af65c80b653e33cf0150R9

**Comment by garethbowen** [comment]
Ready for AT in `5978-fix-typo`

**Comment by ngaruko** [comment]
LGTM
On `master`
![image](https://user-images.githubusercontent.com/6979995/65551063-1cde2900-df75-11e9-9062-65112c8f71f8.png)

On the branch
![image](https://user-images.githubusercontent.com/6979995/65551189-6af32c80-df75-11e9-92ad-546209c7a372.png)
