### ISSUE TITLE
Uploading a custom translation with special characters breaks the admin page. 

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5982]
**Describe the bug**
Using medic-conf if you upload a translation that has a space of ) in the name will cause issues. Spaces will break the individual language and ) will break all language selections. 

**To Reproduce**
1. Create a translation file named `messages-dec)opy.properties`
2. Upload to your instance via `medic-conf upload-custom-translations`
3. Navigate to Admin App > Languages. 
4. Click on a language and nothing happens.  

**Expected behavior**
The language should display or possibly we adjust medic-conf to not allow poor names. 

**Logs**
```
jquery.js:1560 Uncaught Error: Syntax error, unrecognized expression: #locale-dec)opy-body
    at Function.Sizzle.error (jquery.js:1560)
    at Sizzle.tokenize (jquery.js:2216)
    at Sizzle.select (jquery.js:2643)
    at Function.Sizzle [as find] (jquery.js:862)
    at jQuery.fn.init.find (jquery.js:2896)
    at getTargetFromTrigger (collapse.js:163)
    at Collapse.<anonymous> (collapse.js:144)
    at HTMLAnchorElement.proxy (jquery.js:10502)
    at Function.each (jquery.js:367)
    at jQuery.fn.init.each (jquery.js:202)
```
**Screenshots**

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: admin
- Version: 3.7.0

**Additional context**
Add any other context about the problem here. What have you tried? Is there a workaround?

**Comment by wtekeu** [comment]
Ready for AT `5982-custom-translation-bug-in-admin` (medic-conf)

**Comment by ngaruko** [comment]
LGTM
**_Master_**
![image](https://user-images.githubusercontent.com/6979995/66979313-86330100-f109-11e9-9c10-d8fd1d0ff815.png)

**_Branch_**
Errors thrown if there are undesired characters in the file name
![image](https://user-images.githubusercontent.com/6979995/66983040-242bc900-f114-11e9-955f-761849970ce9.png)
