### ISSUE TITLE
Bump dependencies for 3.8.0

### ISSUE THREAD

**Issue by garethbowen** [medic/medic#5983]
Same as usual... except this time document how you did it, pitfalls to avoid, and update the release manager instructions so you never have to do it again.

**Comment by dianabarsan** [comment]
Ready for AT on `5983-bump-dependencies`. 
Please do a smoke test of all apps (webapp, admin, api and sentinel) to catch obvious problems.

**Comment by garethbowen** [comment]
Merged. No AT required as any bugs will be found in regression testing.
