### ISSUE TITLE
Form context is filtering on the admin console

### ISSUE THREAD

**Issue by newtewt** [medic/medic#5987]
Not all forms display on the form page of the admin console. It seems that the context is being applied and filtering since the admin user doesn't meet all the criteria. 

**To Reproduce**
1. Upload the CHT config to your instace. 
1. Log in as admin
2. Navigate to app settings > forms
3. Notice not all forms are displayed. 

**Expected behavior**
The admin should see all forms regardless of context on the admin console. 

**Environment**
- Instance: localhost
- Browser: Chrome
- Client platform: Linux
- App: admin
- Version: master

**Additional context**
The context for the form is 

```
{
    "icon": "icon-pregnancy",
    "title": "Pregnancy registration",
    "context": {
        "person": true,
        "place": false,
        "expression": "contact.type === 'person' && summary.alive && !summary.muted && summary.show_pregnancy_form && user.parent.type === 'health_center' && (!contact.sex || contact.sex === 'female') && (!contact.date_of_birth || (ageInYears(contact) >= 12 && ageInYears(contact) <= 49)) && user._id != contact._id"
    }
}
```

**Comment by garethbowen** [comment]
Ready for AT in `5987-show-all-xforms-in-admin`

**Comment by ngaruko** [comment]
Are json forms meant to show here as well @garethbowen ? There seems to be none.

![image](https://user-images.githubusercontent.com/6979995/66014065-ecc0f800-e529-11e9-9062-af8af30a8dc4.png)

**Comment by garethbowen** [comment]
@ngaruko Yes, if you have any installed they should show there. The CHT reference app might have none...

My config:

![Screenshot from 2019-10-02 15-37-08](https://user-images.githubusercontent.com/2064938/66014227-8a1c2c00-e52a-11e9-8563-ea41c065fc6a.png)

**Comment by ngaruko** [comment]
LGTM
**Before**
![image](https://user-images.githubusercontent.com/6979995/66014673-34e11a00-e52c-11e9-8e4f-fde1f9878f67.png)

**After**
![image](https://user-images.githubusercontent.com/6979995/66014716-5f32d780-e52c-11e9-92d0-08315ea769ed.png)
