### ISSUE TITLE
Review and clean XLSForms for CHT reference app

### ISSUE THREAD

**Issue by abbyad** [medic/medic#6005]
The XLSForms for the reference app (config/default) need to be reviewed for consistency in data and formatting. This should be completed as part of the initial launch of the config to avoid additional work for backwards compatibility.

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.7.x`

**Comment by abbyad** [comment]
The meta fields are empty due to broken XPath and need to be updated.

**Comment by dianabarsan** [comment]
Broken meta fields fix has been merged into master and backported to `3.7.x`

**Comment by newtewt** [comment]
Verified these changes are there in a local instance of the latest 3.7.0-beta.2.
