### ISSUE TITLE
Deleting a purge database without restarting API could block users from replicating

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic#6012]
**Describe the bug**
When deleting a purge database without restarting API, the service will continue to use the PouchDB object connected to the deleted database and throw errors on every request.

**To Reproduce**
1. Deploy 3.7. Enable purge and allow purge to run.
2. Login with an offline user. 
3. Delete all purge databases (or just the one your user would query).
4. Login with the same offline user.
5. Observe errors in the console when doing an initial replication: 
```
VM243 inbox.js:3 GET https://gamma.dev.medicmobile.org/api/v1/users-info 502
(anonymous) @ VM243 inbox.js:3
(anonymous) @ VM243 inbox.js:3
Promise.then (async)
(anonymous) @ VM243 inbox.js:3
(anonymous) @ VM243 inbox.js:3
(anonymous) @ VM243 inbox.js:3
i @ VM243 inbox.js:3
t @ VM243 inbox.js:3
(anonymous) @ VM243 inbox.js:3
```

**Expected behavior**
Users should be able to login and replicate even if the purge database had been deleted.

**Logs**
API logs show:
```
Oct 10 10:33:37 gamma-dev gamma-dev-medic-api-logs: (gamma-dev-5b986f7cd8-c92gg) | [2019-10-10 14:33:36] 2019-10-10 14:33:36 ERROR:   Reason: { error: 'not_found',
Oct 10 10:33:37 gamma-dev gamma-dev-medic-api-logs: (gamma-dev-5b986f7cd8-c92gg) | [2019-10-10 14:33:36]   reason: 'Database does not exist.',
Oct 10 10:33:37 gamma-dev gamma-dev-medic-api-logs: (gamma-dev-5b986f7cd8-c92gg) | [2019-10-10 14:33:36]   message: 'Database does not exist.' } 
Oct 10 10:33:37 gamma-dev gamma-dev-medic-api-logs: (gamma-dev-5b986f7cd8-c92gg) | [2019-10-10 14:33:36] 2019-10-10 14:33:36 ERROR: UNHANDLED REJECTION! 
Oct 10 10:33:37 gamma-dev gamma-dev-medic-api-logs: (gamma-dev-5b986f7cd8-c92gg) | [2019-10-10 14:33:36]   status: 404,
Oct 10 10:33:37 gamma-dev gamma-dev-medic-api-logs: (gamma-dev-5b986f7cd8-c92gg) | [2019-10-10 14:33:36]   name: 'not_found',
```

**Environment**
- Instance: gamma.dev.medicmobile.org
- App: api
- Version: 3.7

**Additional context**
Restarting API after deleting purge databases fixes the issue.

**Comment by dianabarsan** [comment]
Ready for AT on `6012-catch-database-deletes`

**Comment by newtewt** [comment]
:+1:  I can log in fine after the databases are deleted. Also purging is still working as expected.

**Comment by dianabarsan** [comment]
Also backported to `3.7.x`
