### ISSUE TITLE
Target Revisions: CHT reference app

### ISSUE THREAD

**Issue by helizabetholsen** [medic/medic#6016]
Following conversation with @ranjuts and @kanikamedic, we'd like to make the following revisions to the targets included in 3.7.0.

- [ ] **Priority** is to remove the "Newborn Mortality" target from this release. We need to review and redefine this target prior to introduction.

- [ ] Rename the following targets - "Births" to "Live Births" and "Deliveries in facility" to "In-facility deliveries"

An additional flag, though no action required at this time, is that we will need to review and consider changing our definitions for ANC 1+, 4+, 8+ to account for facility-based ANC and community-based ANC. We'd like to incorporate partner feedback into that definition as well, so will wait to refine on the next iteration.

cc @abbyad

**Comment by abbyad** [comment]
Included in 3.7.0 project since it is bundled with #6017 and there is no additional testing.

**Comment by ranjuts** [comment]
Adding a calcluation update for the Deaths widget (which might require a config update as detailed below)We need to not count stillbirths in this count. That may require us updating the form config (delivery form) to either include whether or not the deceased baby was stillborn in baby's person record or not create the person record when its a stillbirth. Check lines 108 - 124 in the delivery xls to make this update. +nyika@medicmobile.org please reach out on slack if you need further clarification. Preference is to not create a person record when its a stillbirth, however, if its easier technically to create the record regardless and mark as stillbirth that should be okay too.

**Comment by dianabarsan** [comment]
Merged into `master` and backported to `3.7.x`

**Comment by newtewt** [comment]
I see the target removed and the translation changes in the 3.7.0-beta.3.
