### ISSUE TITLE
Add Target does not work on `gamma.dev`

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#6019]
**Description**
Add Target does not work on `gamma.dev` but seems to work on local.

**To Reproduce**
1. Go to '[target page](https://gamma.dev.medicmobile.org/admin/#/targets)' 
2. Click on 'Add target'
3. Nothing happens in the UI

**Expected behavior**
Edit target form should open
**Logs**
```
Transition Rejection($id: 14 type: 6, message: The transition errored, detail: Error: Transition Rejection($id: 13 type: 4, message: This transition is invalid, detail: The following parameter values are not valid for state 'targets-edit': [id:undefined])) stateService.js:37
invalidTransitionHook@https://gamma.dev.medicmobile.org/admin/js/main.js:3580:15
invokeCallback@https://gamma.dev.medicmobile.org/admin/js/main.js:8074:65
require<[52]</TransitionHook</TransitionHook.prototype.invokeHook@https://gamma.dev.medicmobile.org/admin/js/main.js:8079:26
require<[52]</TransitionHook</TransitionHook.invokeHooks@https://gamma.dev.medicmobile.org/admin/js/main.js:8047:41
require<[50]</Transition</Transition.prototype.run@https://gamma.dev.medicmobile.org/admin/js/main.js:7880:41
require<[43]</StateService</StateService.prototype.transitionTo@https://gamma.dev.medicmobile.org/admin/js/main.js:6486:46
require<[43]</StateService</StateService.prototype.go@https://gamma.dev.medicmobile.org/admin/js/main.js:6386:21
clickHook/</transition_1<@https://gamma.dev.medicmobile.org/admin/js/main.js:982:32
timeout/timeoutId<@https://gamma.dev.medicmobile.org/admin/js/main.js:46692:31
completeTask@https://gamma.dev.medicmobile.org/admin/js/main.js:46330:7
Browser/self.defer/timeoutId<@https://gamma.dev.medicmobile.org/admin/js/main.js:31911:19
```
**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/66724035-3fc97200-ee7d-11e9-8ad2-c18504b1108e.png)

**Environment**
- Instance: gamma.dev.medicmobile.org
- Browser: Firefox, Chrome
- Client platform: MacOS
- App: admin
- Version: 3.7.0-beta.1 & 3.7.0-beta.2

**Additional context**
Logged in as `medic`.  Seems to work on `local`

**Comment by garethbowen** [comment]
Ready for AT in `6019-add-state-default-parameter`

**Comment by ngaruko** [comment]
LGTM
Tested on `6019-add-state-default-parameter` branch, local install...
![image](https://user-images.githubusercontent.com/6979995/66787568-b4b1b000-ef40-11e9-979b-edf8b717ebf0.png)

**Comment by dianabarsan** [comment]
Also backported to `3.7.x`
