### ISSUE TITLE
Current password validation error on Update password form

### ISSUE THREAD

**Issue by ngaruko** [medic/medic#6020]
**Describe the bug**
 The `current password` validation assumes an empty string as an input, which brings `incorrect password` instead of `password required` error.

**To Reproduce**
1. Go to '[user Settings ... ](http://localhost:5988/#/user)'
2. Click on 'update password'
3. Skip the `current password` input
4. Fill in the rest correctly and click the `Submit` button
>> The error message is `Password is not correct.`

**Expected behavior**
A `Password is a required field` error should show.

**Screenshots**
![image](https://user-images.githubusercontent.com/6979995/66729010-d5c4c300-eea4-11e9-99b7-5a49bc1bdb00.png) || 
![image](https://user-images.githubusercontent.com/6979995/66729018-e70dcf80-eea4-11e9-9aa9-3ac9081f2e46.png)

**Environment**
- Instance: local, gamma.dev.medicmobile.org
- Browser: Firefox, Chrome
- Client platform: MacOS
- App: webapp
- Version:  3.7.*

**Additional context**
I suspect this has to do with #5635

**Comment by dianabarsan** [comment]
Ready for AT on `6020-current-password-validation-error`

**Comment by newtewt** [comment]
Seeing the appropriate error as expected above.
