### ISSUE TITLE
ADD NO_LABEL TO Contact Objects in the CHT Reference APP

### ISSUE THREAD

**Issue by nomulex** [medic/medic#6032]
This should help get rid of contact labels in the display.
![image](https://user-images.githubusercontent.com/3070004/66980148-953d9300-f0b8-11e9-8e2e-dde27a9f004e.png)

**Comment by dianabarsan** [comment]
Ready for AT on `6032-add-NO-LABEL`

**Comment by newtewt** [comment]
Looks like those extra contact labels are no longer showing. 

![image](https://user-images.githubusercontent.com/10531066/67294284-a0773100-f4b3-11e9-8d10-dfd8d0fa960a.png)
