### ISSUE TITLE
Version tooltip showing incorrect version

### ISSUE THREAD

**Issue by abbyad** [medic/medic#6048]
The tooltip on the header logo should show the current version of the core framework but is showing a previous version number.

**To Reproduce**
1. Go to the About page which shows the actual version number
1. Hover over logo in top left to see the tooltip
1. Check that they are the same 

**Expected behavior**
The tooltip should show the same version as the about page's version.

**Screenshots**
![image](https://user-images.githubusercontent.com/789512/67304746-4e89d780-f4c2-11e9-8c48-f36abe4ab6ec.png)

**Environment**
- Instance: cht.app
- Browser: Chrome 77
- Version: 3.7.0-beta.3

**Comment by dianabarsan** [comment]
Ready for AT on `6048-correct-version`

**Comment by newtewt** [comment]
Seeing the udpated tool tip when running locally.
